### ISSUE TITLE
Figure out how to make React Dev Tools work at Chrome

### ISSUE THREAD

**Issue by bebraw** [survivejs/webpack_react#10]
From #9.

> I know this is completely irrelevant: I am using your code (from this example 06) for trying to learn and I added the "React Dev Tools for Chrome" to debug, etc.

> However, the "Top Level" continuously refreshes inside React Tools. So I cannot do anything debug-wise! It appears as if it is created and re-created continuously. Do you have any idea what the case may be? Thanks!

**Comment by af7** [comment]
Could it be related to ALT? Or to React in general?

Does this mean that something makes the react to component to continuously re-render? (that would be REALLY bad, as nothing changes unless the user acts on something, so no render should be caused).

**Comment by bebraw** [comment]
@af7 React Dev Tools are working for me as expected. I tried against various phases of the project (04, 05, 06). There's an `Warning: getDOMNode(...) is deprecated in plain JavaScript React classes.` at the console but by the looks of it this is a bug at Dev Tools (https://github.com/facebook/react-devtools/pull/80) that will get fixed once they release a new public version.

Can you try getting rid of `node_modules`, reinstalling the dependencies (`npm i`) and giving it another go? Is it possible for you to try it on another operating system? I'm on OS X btw.

**Comment by bebraw** [comment]
Traced this down to https://github.com/facebook/react-devtools/issues/73 and https://github.com/facebook/react-devtools/pull/85 . Closing.
