### ISSUE TITLE
Immutable chapter?

### ISSUE THREAD

**Issue by Foxandxss** [survivejs/webpack_react#100]
I am seeing immutable more and more in React. That could be a good fit for the kanban app.

What do you think?

**Comment by bebraw** [comment]
Yeah, I agree. It's one of those topics that should be discussed to show what's the point.

**Comment by bebraw** [comment]
A couple of references:

* https://facebook.github.io/react/docs/update.html
* https://facebook.github.io/immutable-js/
* https://www.npmjs.com/package/icepick

**Comment by bebraw** [comment]
Let's skip this one. Better to do a focused blog post in order to avoid splintering the book too much.
