### ISSUE TITLE
A bit more info on the Flux introduction

### ISSUE THREAD

**Issue by Foxandxss** [survivejs/webpack_react#101]
When moving the app from "only components" to Flux, you're explaining the Flux idea on those 3 paragraphs. I think you should also explain the main idea of Flux, the unidirectional data flow.

I see you mention it a bit later on the book, but I think you're assuming that people knows about that fact.

So maybe a little reword on the "Introduction to Flow" where you name the data flow and the different parts a bit (like you're doing right now).

What do you think?

**Comment by bebraw** [comment]
Can you have a look at https://github.com/survivejs/webpack_react/blob/master/manuscript/06_react_and_flux.md and let me know what you think? I keep on repeating the main points there now. Hopefully that's more effective. :+1:

**Comment by bebraw** [comment]
Should be cool now. We've definitely done some iteration on that. :+1:
