### ISSUE TITLE
Suggestions for enhancing absorption in newer developers

### ISSUE THREAD

**Issue by Cryptolemming** [survivejs/webpack_react#102]
Hi,

firstly great book - you put together a terrific resource showing the utility of many varying tools.  Could not have been easy to produce.

Some things you might want to consider for enhancing clarity if you find the time:

- suggest an IDE early on
- provide more verbal dissection of the transition notes -> kanban app and of the Flux workflow in general
  - as the work progressed it seemed you were in a greater rush to finish the book perhaps (could just be me) and the very important / more complicated contentious transition from notes to Flux (actions, stores, localstorage) could use some deeper explanations.
  - verbally connect more dots for the reader and take a little more time explaining each.
- provide external resources - in the chat you link to a react-webpack book - similar links to help connect dots without rendering the book too contentious would help both sides.

Thank you

**Comment by Foxandxss** [comment]
Yo,

I don't think that a IDE suggestion is in place, that is more a personal preference than anything else. Maybe a side note of what IDEs / editors supports Flow is nice to have.

I totally agree with the point of "Provide more information on the flux transition". I also feel that the parts where the "Action and store" stuff are explained are a bit rushed.

Action needs more information of what an action really is and why are we defining them in there (And also explain the syntax from alt to create them in that way).

In stores, I already have an issue talking about them, but yes, needs more work in that regard.

**Comment by Cryptolemming** [comment]
Side of IDE's works.

**Comment by bebraw** [comment]
@Cryptolemming Thanks a lot for your comment! I've reworked the material heavily based on feedback and I've tried to make it more approachable. Now there are more explanations and I managed to make the project a little simpler conceptually. Could you have a look at https://github.com/survivejs/webpack_react/blob/master/manuscript/06_react_and_flux.md and let me know what you think?

I set up issues (#143, #144) based on your other suggestions.

**Comment by bebraw** [comment]
@Cryptolemming The new version is out there now. See http://survivejs.com/webpack_react/react_and_flux/ . The Leanpub version was updated as well.

Let me know if you find any further issues and we can get those sorted out in subsequent releases. :+1:
