### ISSUE TITLE
Support for the alt chrome extension

### ISSUE THREAD

**Issue by Foxandxss** [survivejs/webpack_react#105]
Since you named it, in the snippet where we add alt itself, you could put something like:

```javascript
import Alt from 'alt';
//import chromeDebug from 'alt/utils/chromeDebug';

const alt = new Alt();
//chromeDebug(alt);

export default alt;
```

And then say something llke "Uncomment those lines if you added the alt chrome extension and you want to use it".

**Comment by bebraw** [comment]
Cool idea! Thanks.
