### ISSUE TITLE
Change .bind(this) to arrow function

### ISSUE THREAD

**Issue by Foxandxss** [survivejs/webpack_react#106]
Previously you commented that you preferred to use arrow functions inside event handlers to avoid the .bind(this) but on the store snippet on the flux chapter, you changed it:

```javascript
<Notes items={notes} onEdit={this.itemEdited.bind(this)} />
```

Instead of

```javascript
<Notes items={notes} onEdit={(id, task) => this.itemEdited(id, task)} />
```

I am happy with both approaches to be honest, but not in mixing them.

**Comment by bebraw** [comment]
I discussed this at Reactiflux. Ideally autobind (#84) would work but it doesn't. What if we added some clarity to the system by dealing with bindings at `constructor`. That would lead to a couple of an extra lines there but it would clean up rendering somewhat. I.e. we would have bindings like `this.addNote = this.addNote.bind(this);`. It's a little verbose but it's explicit. What do you think?

Once [property initializers](https://facebook.github.io/react/blog/2015/01/27/react-v0.13.0-beta-1.html#es7-property-initializers) become stable those are a better alternative. Even then the changes would be minimal if we went with constructor based bindings.

**Comment by Foxandxss** [comment]
To be honest @bebraw I don't really care about which way you pick to bind the functions. The main issue here is in one snippet you use one style, the next snippet has a different style and the third snippet goes back to the first style.

So you should pick one way and stick to it :P

**Comment by bebraw** [comment]
Got it. I agree it's confusing.

The advantage of pushing the bindings to `constructor` is that it will be easy to move to property initializers later on just by removing a bit of code and tweaking method definitions. I should remember to mention about that at the text.

**Comment by Foxandxss** [comment]
Sounds good to me :+1:
