### ISSUE TITLE
Typing Chapter

### ISSUE THREAD

**Issue by bebraw** [survivejs/webpack_react#108]
I feel discussing Flow so early might confuse things. Perhaps it should be discussed after the linting chapter given it's an advanced concept? What do you think?

I could go into more detail there and discuss propTypes too. Generally the chapter would be just about typing and how to apply it to your project, what benefits it provides, what gotchas there are and so on.

Issues to discuss:

* flow, flowtype, proptypes, typing in general
* runtime checking vs. static checking

**Comment by Foxandxss** [comment]
I can see that. I had to skip it because major IDEs doesn't support it.

A bonus chapter of "Adding typing to React with Flow" sounds really good to me.

**Comment by bebraw** [comment]
The Flow bits will be removed once I get the great Flux rework done. It will go to a bonus chapter of its own later on.

**Comment by bebraw** [comment]
First version done.
