### ISSUE TITLE
Feedback on "React and Flux"

### ISSUE THREAD

**Issue by Foxandxss** [survivejs/webpack_react#109]
I am going to give my feedback of the entire chapter. There are a few extra issues in here that worth checking as well (#101, #103, #104, #105).

Starting with the fact that the book is meant for people who doesn't know React or Flux, I find the introduction to Flux to be a little bit poor. I would expand it a bit more.

The relay part, as I said on #103 I would remove it entirely, or at least reword it (check the issue).

The issue in here is that the port of the notes app to Alt has no explanations whatsoever.

So far we know that "Actions" is something we trigger on Views to modify Stores, ok, that is not bad, but you simply paste a snippet in there and you move on.

You should explain more about creating Actions. Something along the lines... "Here we can see how we can generate some actions with Alt. In the actions we don't actually write code for creating/update/remove those notes, we use simply use them as a way to communicate intentions".

Then you define a Store, snippet in place. First I would explain a bit more the "Store" concept in here. Something along the lines: "As we explained earlier, the Store is the place where we put the state of something, in this case, the notes. So here we map all those actions we created earlier to manage that state".

Then you could explain a few lines of code like you did with `bindActions` (but that part of "we use a factory is a bit confusing (what factory?)").

I would explain that `this.notes = [];` is actually the state (what alt does behind the curtain in here, #104).

The other three methods can be easily explained in a one liner: "We then implement our previous 3 actions in here to update the internal state of the Store". Maybe it is worth explaining the syntax you used for the `update` parameters.

Next, creation of `app/libs/alt.js`. We don't know Alt, so I guess a bit of explanation of why we need that is in place.

Gluing all together. Using the classic "As you can see" is not a good idea (and I know that myself, I do that a lot, grr). You can't pretend that the reader is able to see it as you see it.

So here you should explain why are we listening (and unlistening!) changes. So a explanation in here of flux saying that a Store sends change events every time its state changes and that is how the Component updates itself is a good idea. On the other hand, you call some actions in there so a reminder of the flux architecture could be in place: "Components will never update a store, you need to send the proper action that will eventually hit the store, update it and since we are listening to those changes, the component get updated".

"On component design". I didn't see your point there, I skipped it to be honest.

"What's the Point?" That is well explained.

The localstorage snippet, the easiest one to understand and the one with the good explanations :P

Let's continue from the HOC thing.

Decorators are stage 1 IIRC, and they are not something we used to use in Javascript, so it needs a much much better explanation of what is a decorator and why do we need it.

The debug thing on "persist", I didn't understand it. (ComponentWillUnmount doesn't work in here?).

Same issue applies to "connect", we still need to know more about decorators at this point. Also you have to explain "why" are we creating those two decorators. What is the need and why do we want to do it. Users don't want to blindly follow some instructions without knowing **why** are they doing it.

After that you clean App to use this new decorators, but I was really confused at this point and I was just coding without knowing why.

Now the explanation of decorators come in, but a bit late perhaps.

Adding the wrappers. An explanation of what we are doing would be nice, we can't see in here what is your point.

And yes, much better now using proper `@decorator` syntax. Sad that Webstorm doesn't have support for it yet ;(

Last but not least the AltContainer. What is that? You think it is a good idea to use it, you use it and you finish the chapter. I am sorry but we can't see that control you say, so I would property explain what an AltContainer is, why do we need it and how it replaces the connect decorator. Then I would explain the component, its attributes and what we should put in there.

Alright, that is enough for this chapter.

Cheers.

**Comment by bebraw** [comment]
> Starting with the fact that the book is meant for people who doesn't know React or Flux, I find the introduction to Flux to be a little bit poor. I would expand it a bit more.

Expanded considerably. I re-iterate now on the main points throughout the chapter to get the point across.

> The relay part, as I said on #103 I would remove it entirely, or at least reword it (check the issue).

Removed. Relay can be discussed at a possible later chapter. It was just distracting here.

> You should explain more about creating Actions. Something along the lines... "Here we can see how we can generate some actions with Alt. In the actions we don't actually write code for creating/update/remove those notes, we use simply use them as a way to communicate intentions".

There are two examples of how to set it up now and I make an analogy with CRUD. I changed naming accordingly to get the point through. https://github.com/survivejs/webpack_react/blob/master/manuscript/06_react_and_flux.md#defining-crud-api-for-notes

> Then you define a Store, snippet in place. First I would explain a bit more the "Store" concept in here. Something along the lines: "As we explained earlier, the Store is the place where we put the state of something, in this case, the notes. So here we map all those actions we created earlier to manage that state".

Added stronger description. Perhaps a little terse so this can likely be improved. https://github.com/survivejs/webpack_react/blob/master/manuscript/06_react_and_flux.md#defining-store-for-notes

> Then you could explain a few lines of code like you did with bindActions (but that part of "we use a factory is a bit confusing (what factory?)").

Explained/simplified in the above.

> I would explain that this.notes = []; is actually the state (what alt does behind the curtain in here, #104).

Going to solve this separately at #104. Missed at first pass.

> The other three methods can be easily explained in a one liner: "We then implement our previous 3 actions in here to update the internal state of the Store". Maybe it is worth explaining the syntax you used for the update parameters.

Above. I have something like `It maps each Action to a method by name. We trigger appropriate logic at each method then.` now where it refers to `bindActions`.

> Next, creation of app/libs/alt.js. We don't know Alt, so I guess a bit of explanation of why we need that is in place.

This is the first thing I go through now given it's so fundamental for getting everything to run. https://github.com/survivejs/webpack_react/blob/master/manuscript/06_react_and_flux.md#porting-notes-application-to-alt

> Gluing all together...

Pushed to #145. I need to study this in detail and see if I can split it up somehow. I agree it's not an ideal solution. Too much code at once.

> "On component design". I didn't see your point there, I skipped it to be honest.

Dropped.

> The localstorage snippet, the easiest one to understand and the one with the good explanations :P

I actually expanded on this a lot. The nice thing is that I don't have to get back to this later at the book and it simplified later chapters somewhat. It's good enough on the first pass. https://github.com/survivejs/webpack_react/blob/master/manuscript/06_react_and_flux.md#implementing-persistency-over-localstorage

> Let's continue from the HOC thing...

I dropped HOC altogether. Now I jump straight to decorators to cut the chase. See https://github.com/survivejs/webpack_react/blob/master/manuscript/06_react_and_flux.md#extracting-connection-decorator . Given there's only one decorator to implement, it's much simpler and you can see the benefit fast (less code at `App`).

> Last but not least the AltContainer. What is that? You think it is a good idea to use it, you use it and you finish the chapter. I am sorry but we can't see that control you say, so I would property explain what an AltContainer is, why do we need it and how it replaces the connect decorator. Then I would explain the component, its attributes and what we should put in there.

Moved to #146 so I can work on this separately.

Thanks for the comments! That was useful. :+1:

**Comment by bebraw** [comment]
Closing as we've gone through this quite thoroughly. Thanks a lot for feedback. :+1:
