### ISSUE TITLE
Loading initial state from Components

### ISSUE THREAD

**Issue by Foxandxss** [survivejs/webpack_react#114]
I see the calls like:

```javascript
LaneActions.init(getInitialData('LaneStore'));
```

on a component level. Talking about Flux philosophy and stuff. Isn't this better to be done on the store itself? Upon initialization, retrieve its initial data.

Maybe I am wrong, but maybe as an extra, an explanation of why to do this in here could be good.

**Comment by bebraw** [comment]
Yeah, that's a valid point. It belongs to store level. I'll rethink this a bit.

**Comment by bebraw** [comment]
Solved by getting rid of these. Now initialization happens at Store level.
