### ISSUE TITLE
Lane.jsx implementation, old "bind" style

### ISSUE THREAD

**Issue by Foxandxss** [survivejs/webpack_react#115]
I saw you changed how you `.bind()` your stuff, but on "From Notes to Kanban" where you implement `Lane.jsx`, you forgot to update how you bind functions.

There is one:

```javascript
<button onClick={() => this.addNote()}>+</button>
```

And one:

```javascript
<Notes onEdit={this.noteEdited.bind(this)} />
```

Cheers.

**Comment by Foxandxss** [comment]
Also after the snippet there is a box where you tell that there is no need to use .bind for the render, but seeing the latest changes, that box should go away.

**Comment by Foxandxss** [comment]
I also noted that the source code needs to be updated.

On the other hand, when we add `Editable` to `Lane`, it also uses the old style.

**Comment by bebraw** [comment]
Thanks a lot! `Lane` and `Editable` should be in the constructor bind format now.
