### ISSUE TITLE
Feedback on "From Notes to Kanban"

### ISSUE THREAD

**Issue by Foxandxss** [survivejs/webpack_react#128]
As I did with #109, I will give a overview of this chapter to talk about the rough edges I see.

This chapter relies on "React and Flux" to have better explanations because some of the code in here does the same.

### Extracting Lanes

First, you modified  `App.jsx` to now use `alt.takeSnapshot()` but there is no reason behind that and I think that `takeSnapshot` was mentioned like once as a curiosity so this needs much more explanation and reasoning behind the change.

When you modify the storage, it is always a good idea to note what changes did you do on it. Something like "We added a function here so we can grab the initial data from a storage in one place". I think it is a good practice not to assume that the reader knows your intentions (even if it is dead simple).

### Going from Note Singletons to Instances

When changing `NoteActions` to export a function that will generate a new set of actions, I would like an explanation in there.

After the big snippet of `Lane`, a general discussion of the changes is in place. (The verbal explanation we talked about).

### Implementing Edit/Remove for Lane

This section is pretty good, there is more verbal explanations of all the steps and it is really easy to follow.

**Comment by bebraw** [comment]
## Extracting Lanes

* I redid whole snapshot thing.

## Going from Note Singletons to Instances

* Dropped. I ended up with this https://github.com/survivejs/webpack_react/blob/master/manuscript/07_from_notes_to_kanban.md#making-lanes-responsible-of-notes - It's still quite chunky and it feels like I could split it in two (separate sections for attach/detach perhaps?).

## Implementing Edit/Remove for Lane

* https://github.com/survivejs/webpack_react/blob/master/manuscript/07_from_notes_to_kanban.md#implementing-editremove-for-lane - I go through the basic idea before implementing a thing now. The format is always "what's going to happen next, do it, what should you see" as discussed.

**Comment by bebraw** [comment]
Probably safe to close now. We've gone through it quite thoroughly. :+1:
