### ISSUE TITLE
Figure out a viable funding model

### ISSUE THREAD

**Issue by bebraw** [survivejs/webpack_react#131]
I've opened the situation more at [the blog](http://survivejs.com/blog/reaching-towards-the-next-level/). In short for me to develop these kind of resources full time I'll need to make $100 per day, every day. After taxes and side costs (about half) that's a sustainable situation for me.

As a Finn donations won't work due to legislation. Same goes for Kickstarter and the like as you end up on legally gray zone and that's something I prefer to avoid.

So far I've learned that the commercial version of the book offered through [Leanpub](https://leanpub.com/survivejs_webpack_react) doesn't bring in enough for this to work. I am of course very grateful to everyone who has pitched in! Thank you guys!

## Alternative Model - Early Access for Leanpub

I think some kind of a compromise has to be found. What if I gave Leanpub readers a little edge? As a lot of bonus content remains to be developed and I need to fund that somehow, what if I did it like this:

* Leanpub readers get early access to the new chapters. Before that I'll go through the content with my tech editors so you get better quality out of the box.
* I will keep the new chapters hostage until financial goals are met (think Kickstarter) or a time limit has been reached (disappointing sales, might as well release)

Eventually the content would be made public but now there would be a certain amount of exclusivity available for my financial supporters. It's true there's some uncertainty in the model but it seems like a good alternative to the current.

Before moving onto something like this I'm committed to pushing the current chapters as far as I can but after that some kind of a change is needed to keep this viable.

**Comment by webmaven** [comment]
Consider setting up on [Gratipay](http://gratipay.com) to receive ongoing voluntary payments.

**Comment by bebraw** [comment]
@webmaven Yeah, voluntary payments would be great if only I were not a Finn. It's illegal here (needs permit and you need to be a non-profit).

I'm currently researching other models and I'll try that Leanpub early access alternative for sure. I may also offer some kind of a subscription but I'll need to think carefully about how to structure that.

**Comment by Cryptolemming** [comment]
Also, if you can - do accept Bitcoin.

**Comment by webmaven** [comment]
@bebraw, in the US, we have something called a 'fiscal sponsor' (like the Software Freedom Conservancy) that can act as a hosting non-profit organization for projects that are too small to become one on their own. Does something similar exist in Finland?

**Comment by bebraw** [comment]
@webmaven Thanks for the idea. Maybe something like that could work through [COSS](http://coss.fi/) (open source association in Finland).

If I go at it alone, I will have to avoid the D word (donation) according to a lawyer. That means subscription based models will work as long as I can provide something in return.

**Comment by omidfi** [comment]
Not directly about the book, but what about teaching or holding workshops? React is hot in Helsinki as well, I guess some companies would pay for training their employees. Have you tried that?

**Comment by bebraw** [comment]
@omidfi Yeah, I actually had a small, local training related session here at Jyväskylä. It's not the ideal location for something like this, though. I touched base with a company from Helsinki and agreed to a little presentation at December. We'll see where that goes. Distance is bit of an issue but it's manageable.

Considering the book, now my main goal is to improve distribution (Amazon, iBooks) and see how that works out. At the very least I get something for my bookshelf. I'm not counting for this to make a big difference but it's worth a shot.

Thanks for the suggestion. :100:

**Comment by omidfi** [comment]
Well you've made something awesome, and gave it out for free. It's amazing. The more noise you make about it, more people might come in and help, and also keep it going so that you don't give up and the community will see more of your books in the future! No need to be shy about it :) 

Good that you've tried and hopefully it works out well. 
Do you know Kyle Simpson? @geitfy he also gave out You Don't Know JS for free, but he published it with Orielly, and he has lots of workshops here and there about JavaScript. 

By the way, I think you can contact HelsinkiJS, or Oleg it's organizer and try to see how he might be able to help. Also nodejs helsinki, Lauri is a nice guy. Introducing the book...

**Comment by bebraw** [comment]
Yeah, I'm aware of @getify. I know O'Reilly is going to publish two React books very soon. See my [overview of React books](http://survivejs.com/blog/react-books/). I'm literally going to be crunched by competition. ;)

I actually tried pitching the book to a publisher for two months before they said no. Incidentally the said publisher will bring an offering of its own to the market next year.

HelsinkiJS might work but by the looks of it they haven't been very active lately. I could be wrong about that, though.

**Comment by getify** [comment]
Are you allowed to sell "units" of your time? Like, could you set up a site similar to how patreon works, where you promise for each $5 someone pledges to you, you'll actually give them something tangible of your time, like a tweet, a github commit, a mention in a blog post, etc?

That way they're not just donating, but actually "paying" you for "services", just at a greatly uneven rate such that they can help you and you can still benefit and not lose on your time? Make it so every dollar given is equivalent to a "unit" of your time, and give out these services based on units of time (a tweet is 5 units of time, a blog post mention is 10, etc).

**Comment by bebraw** [comment]
@getify Absolutely, thanks for the idea. As long as I avoid the word donation, it's fine.

**Comment by omidfi** [comment]
@bebraw yes they had a long summer holiday, but at least on their facebook group many are active and next meetup is already scheduled I guess. I could at least share the link to your book on the facebook page, if you are not willing to do it yourself :) 

Reading Kyle's comment I was thinking a visual grid the books homepage, on which you have filled it with squares, equal to hours or its equivalent in dollars into the book. Anyone can pay something and buy some squares and as soon as all the squares are sold the book becomes available for free. And in this case, the bonus chapters can become free...

**Comment by bebraw** [comment]
@omidfi It would be great if you could post something as I don't use Facebook.

I have to think carefully about selling time/tweets/whatever. Most likely I'll need some kind of a proxy in between as I don't want to deal with VATMOSS myself.

**Comment by omidfi** [comment]
@bebraw I forgot to write here. I posted on HelsinkiJS and many were excited about the book. I hope it helped somehow :)

**Comment by bebraw** [comment]
@omidfi Thanks for mention. :+1:

**Comment by eMerzh** [comment]
not sure if it fit your projects, your ideas and / or your philosophy  but you can also think about patreon :
https://www.patreon.com/become-a-patreon-creator

**Comment by bebraw** [comment]
@eMerzh Patreon is one alternative, yup. To keep it legal, I have to stay away from donation driven schemes. There are ways to package it so it's not a donation anymore. Patreon tends to work really well if you have some name already. :+1:

The current model (one time sale) works well enough for now. But I can understand having a source of recurring income would be very valuable.

Thanks for the suggestion!

**Comment by bebraw** [comment]
I think it's safe to close this now as everything is up and running. 👍 

Thanks for the ideas guys!
