### ISSUE TITLE
Is there any Kanban explanation or link in the book?

### ISSUE THREAD

**Issue by Foxandxss** [survivejs/webpack_react#136]
If I am not wrong, I haven't see a reference to what Kanban is in the book. I have been using kanban for years so I knew all about it, but I think that a link to Wikipedia (if there is any article about it there) or a link + minimum explanation/idea is needed.

You can use the preface, first chapter or something like that.

What do you think?

**Comment by bebraw** [comment]
Yeah, valid point! I'll expand on this at the introduction, add a nice image and a couple of links.
