### ISSUE TITLE
Tiny problem in "From Notes to Kanban"

### ISSUE THREAD

**Issue by spdufeu** [survivejs/webpack_react#139]
First, fantastic book, thank you for creating it! I'm working my way through it and have come across a tiny problem in this chapter. 

In the section "Going from Note Singletons to Instances" where Lane.jsx is refactored, the notes themselves are no longer rendered as the alt container has no contents.

At least, they started being rendered again when I changed it to

```javascript
    <AltContainer
        stores={[this.store]}
        inject={ {
            items: () => this.store.getState().notes || []
        } }>
            <Notes onEdit={this.noteEdited} />
    </AltContainer>
```

I've never created a PR before, but if you agree (and are willing to put up with my inevtiable noob mistakes), I'm more than willing to give it a try!

**Comment by bebraw** [comment]
Thanks a lot for your comment!

I'm currently doing heavy rework on the Flux related chapters that will fix this issue. During this process I will simplify the architecture a little. I will actually end up using singletons but with a twist. In short it's going to look something like this:

* LaneStore - contains a list of lanes. each lane has a name and a list of note **ids**
* NoteStore - contains a list of all notes in the system. each lane has a task and an **id**

After this change the logic will be id based. For instance `Lane` will consume `NoteStore` and then filter its contents based on the ids.

This will get rid of some of the current issues and make it easier to port the system to [redux](https://github.com/gaearon/redux) later on.

So take the current Flux chapters with a grain of salt. My current release target is on Friday but it's possible the content is available sooner. I'll let you know.

**Comment by bebraw** [comment]
So, as promised I redid the chapter. You can find the updated chapters at `master`. I haven't pushed the site or updated the Leanpub version yet but it's probably safe to close this now.
