### ISSUE TITLE
Styling React - A side note on a sentence.

### ISSUE THREAD

**Issue by Foxandxss** [survivejs/webpack_react#141]
While explaining the reasons behind having the CSS separated from the JS, you say:

```
If the user isn't running JavaScript, no styling will be applied to the markup at all.
```

It is a good point, but is it really a good point for us? If there is no Javascript, no styling is the less of our problems :P

**Comment by bebraw** [comment]
Yeah, the actual bigger reason is that without the separation you end up with a flash of content. There's an actual term for that but I can't recall it at the moment.

Note that when isomorphic rendering is used this actually may be a valid reason. At least then you'll be able to show some content to the user even if it's without some of the logic.

**Comment by Foxandxss** [comment]
If I am not mistaken, same problem as with angular. If you load the bundle in the body, the page will load the HTML and then load the bundled css, hence the flash

**Comment by bebraw** [comment]
Yeah, this is one of the major benefits React has over Angular 1. You can prerender the markup on the server side and set up an initial payload. So from web browser's perspective it's like a good old static page. After that React will pick it up, use the markup and data. This is powerful as you avoid some of the initial queries and can display something faster to the user. Isomorphic rendering would make a fine chapter on its own.

**Comment by Foxandxss** [comment]
Angular 2 will have universal support, hihi.

**Comment by bebraw** [comment]
Yup, almost everyone does that these days. :+1:
