### ISSUE TITLE
Push all webpack build related aspects to the deployment chapter?

### ISSUE THREAD

**Issue by bebraw** [survivejs/webpack_react#150]
It would be valuable to make deployment chapter work as a reference for **all** deployment related issues. So when you get some problem (want to minify, split bundles etc.), you would check it out. Perhaps some of the current build config should go there instead (better flow).

**Comment by Foxandxss** [comment]
Yes, from "Developing with webpack" you should remove the instructions for the "build" run script and the **BUILD** branch on the webpack config.

At the end of the day, the chapter is about **Developing** and not **Deploying** :)

**Comment by bebraw** [comment]
Yeah, I agree with the idea. Just had a look to see what doing this change would mean. We would have to

* Merge **Getting Started** and **Developing with Webpack** -> **Developing with Webpack**
* **Developing with Webpack** could link verbally to **Deploying Applications** (that probably should be renamed as **Deploying with Webpack** or similar)
* The CSS splitting configuration from **From Notes to Kanban** would move to **Deploying Applications**. This would be a good change because **From Notes to Kanban** feels long now and **Deploying Applications** feels short.

The biggest question I have in mind is how to deal with build configuration for generating the demos but I have a feeling I can resolve this at `project_source` root somehow. After all webpack is flexible. I'll probably just set up some custom configuration and that's it.

I think these changes would improve the book flow further and make it work a little better.

**Comment by Foxandxss** [comment]
Ok, I will talk point per point:

* How long is each chapter? We don't want a big big chapter. So for me it depends on how long.
* I wouldn't leave **Deploying Applications** outside the "project" part so I wouldn't link it. After all, deployment is the "last" step of a project but still in the project. So I would simply remove all build stuff like I said in my previous message and then for the last chapter of the project part, I would explain all the deployment stuff.
* I have yet to check that to make an opinion.

About the DEMO stuff, no idea, I haven't check that yet.

**Comment by bebraw** [comment]
What if we went with a structure like this?

```
Frontmatter.txt
00_introduction.md
Mainmatter.txt
Webpack.txt
01_webpack_compared.md
02_developing_with_webpack.md
03_webpack_and_react.md
React.txt
04_implementing_notes.md
05_react_and_flux.md
06_from_notes_to_kanban.md
07_implementing_dnd.md
08_building_project.md - New chapter (old build parts reused (old first chapter + CSS bits). from zero to decent build, includes React build bits from **Webpack and React**)
Advanced.txt
09_linting_in_webpack.md
10_deploying_applications.md
11_authoring_libraries.md
12_styling_react.md
Backmatter.txt
13_troubleshooting.md
```

The biggest advantage of this structure is that you get to develop faster and building related aspects get pushed to a single chapter. Now the structure feels more logical even.

**Deploying Applications** is too separate from the rest to warrant moving it to an earlier part. It's more about general techniques after all.

**Comment by Foxandxss** [comment]
I need more time to say anything.

**Comment by bebraw** [comment]
Sure, take your time. :+1:

**Comment by Foxandxss** [comment]
The merge of the two webpack is a :+1: for me, they are pretty short on the PDF.
