### ISSUE TITLE
Getting Started - First index.html

### ISSUE THREAD

**Issue by Foxandxss** [survivejs/webpack_react#153]
In the index you create it just for the sake of making the hello world work, I see:

```html
<script src="build/bundle.js"></script>
```

Shouldn't it be:

```html
<script src="bundle.js"></script>
```

They are on the same directory.

**Comment by bebraw** [comment]
Yeah, that should be fixed already. One of today's fixes.

**Comment by Foxandxss** [comment]
My bad, forgot to pull.
