### ISSUE TITLE
Webpack and React - First two paragraphs

### ISSUE THREAD

**Issue by Foxandxss** [survivejs/webpack_react#155]
Let me write some comments

> Facebook's React is one of those projects that has changed the way we think about frontend development. Thanks to React Native the approach isn't limited just to web. Although simple to learn, React provides plenty of power.

Both ideas in here are nice, but it presents to ideas. I would "connect" them both better.

Something along the lines "... the way we think about frontend development. **Also**, thanks to react native....".

> Webpack provides a good starting point for serious React development. React itself "solves" just the view portion of web development. It will take some getting used to but conceptually it is quite simple once you get your mind around it. Some practices, such as styling, are still under debate as we will see in later chapters.

Again two ideas in here. I would maybe split them. First you say that webpack is awesome for React and immediately after talk about what react does.

In the next section you intro React so you are basically doing the job twice.

WDTY?

**Comment by bebraw** [comment]
Yeah, sounds good.
