### ISSUE TITLE
React and Flux -

### ISSUE THREAD

**Issue by nii236** [survivejs/webpack_react#156]
At the [HOC section](http://survivejs.com/webpack_react/react_and_flux/#pushing-persistency-to-a-hoc), the constructor is missing a line.

Original:

```
  constructor(props) {
    super(props);

    this.addItem = this.addItem.bind(this);
    this.itemEdited = this.itemEdited.bind(this);

    NoteActions.init(storage.get(noteStorageName));

    this.state = NoteStore.getState();
  }
```

It was missing the following line, which was causing the `storeChanged()` function to be `undefined`:

```
this.storeChanged = this.storeChanged.bind(this);
```

**Comment by bebraw** [comment]
Thanks for the report! The HOC part will be eliminated in an upcoming revision (due today!). I'll close this issue once that's up.

Here's [a little sneak peek](https://github.com/survivejs/webpack_react/blob/62e360446535db32a88865c139b9766297f32634/manuscript/06_react_and_flux.md) to show how it will work out. Much simpler.

**Comment by bebraw** [comment]
Fixed as there's no HOC section anymore. :+1:
