### ISSUE TITLE
Figure out better ways to show code changes

### ISSUE THREAD

**Issue by bebraw** [survivejs/webpack_react#159]
Perhaps some form of highlighting per new line or so could work. Bolding and such are options. Ideas are welcome.

**Comment by Foxandxss** [comment]
Leanpub offers a special set of comments you can add in your code to highlight code.

I can't see those highlights properly on my OSX's adobe reader so I dropped that idea for my book.

**Comment by bebraw** [comment]
Closing as this is duplicate of #224.
