### ISSUE TITLE
05_react_and_flux - could not find any reference to 'libs/find_index'

### ISSUE THREAD

**Issue by hliyan** [survivejs/webpack_react#168]
app/stores/NoteStore.js
```javascript
import alt from '../libs/alt';
import NoteActions from '../actions/NoteActions';
import findIndex from '../libs/find_index';
```

**Comment by bebraw** [comment]
@hliyan I think the problem was that I put `findIndex` to wrong location at https://github.com/survivejs/webpack_react/commit/de8216c1d123cd58fd20bbd1c5fd49140b26c94b . Maybe that's it?

**Comment by hliyan** [comment]
Hi! Can you point me to the place where app/libs/find_index.js is created in the tutorial? I think I may have skipped over it at some point. I did a text find within the page but couldn't locate it. Or do I need to do an `npm install find-index`?

**Comment by bebraw** [comment]
Here, http://survivejs.com/webpack_react/implementing_notes/#editing-notes  .

That said moving to `find-index` might be a worthwhile idea as that would cut some custom code out of the project.

**Comment by hliyan** [comment]
Sorry! My bad. Closing. Thanks.

**Comment by hliyan** [comment]
Gah, serves me right for following the tutorial via master branch than your site! I was mid tutorial when your revised chapter came in yesterday/day before yesterday.

**Comment by bebraw** [comment]
Sorry about that! The last few days were a little tight and filled with changes. :)

I'll set up an issue about `find-index`. It would be a nice idea to simplify that.

**Comment by hliyan** [comment]
No problem. I'll just re-do step 05. Do you think you can version the book so that when someone starts the tutorials he can pick the latest snapshot and stick to it till then end?

**Comment by bebraw** [comment]
@hliyan That's a valid point. The current release was bit of a mess due to the huge amount of changes. We could push breaking work to a dev branch and then do a bigger update once. There's rough versioning already but nothing very consistent.
