### ISSUE TITLE
Webpack and React - Developing First React View - npm i --save instead --save-dev

### ISSUE THREAD

**Issue by sdelrio** [survivejs/webpack_react#171]
On <http://survivejs.com/webpack_react/webpack_and_react/> at section *Developing First React View*, why not use `--save-dev`like the other `npm i` on previous sections?, so it will be included in our node_modules.

> Hit `npm i react --save` at the project root to add React to our project. As a next step we can start  developing our Kanban application. First we should define App. This will be the core of our application. It represents the high level view of it and works as an entry point. Later on it will orchestrate it all.

**Comment by bebraw** [comment]
Yeah. It's on purpose.

I like to push application level dependencies there as it's convenient. Later in the book this information is used to generate vendor bundle.

Thanks for bringing this up. I'll make sure to clarify this point! :+1:

**Comment by sdelrio** [comment]
Thanks to you. So fast response

**Comment by bebraw** [comment]
No problem. Poke me at [gitter](https://gitter.im/survivejs/webpack_react) for questions. :+1:
