### ISSUE TITLE
More use of Alt's util decorators?

### ISSUE THREAD

**Issue by nii236** [survivejs/webpack_react#175]
I just ran through the quick tutorial located [here](https://underthehood.myob.com/changing-of-the-guard-in-web-technologies/) and noticed that there were handy utils in Alt for connecting to stores, creating stores, creating actions, and binding actions to stores.

They seem pretty handy, maybe Survive JS could make more use of these pre-built decorators?

Decorator code [here](https://github.com/goatslacker/alt/blob/master/src/utils/decorators.js).

**Comment by bebraw** [comment]
Yeah, that's a valid point given we discuss decorators already.

**Comment by Foxandxss** [comment]
I would a bit wary with implementing decorators. They are a bit confusing to people and this book is to learn how this work. If we start deleting code to use built-in decorators, people will learn less.

I am not saying that this is true in this case, just to be a bit wary.

**Comment by bebraw** [comment]
Yeah. We can mention it as an alternative. Incidentally this would be right after we discuss decorators in the book so it would be the ideal place for such.
