### ISSUE TITLE
Rework Flux introduction

### ISSUE THREAD

**Issue by Cryptolemming** [survivejs/webpack_react#182]
Hi again,

sorry to miss your previous edit before posting. Don't mean to nitpick it's amazing you're editing and adding things so quickly. The intro is rather important I think because it delivers the initial spark of cognition and awareness while setting the tone for the rest of the contentious material to come. Here is a suggestion for redrafting the intro - there might be something in here you like. Cheers.

--

Relying solely on React View components can be sufficient for small applications. Eventually however it will become quite painful and restrictive. Enter Flux application architecture. Flux was designed to help bring clarity to React applications.
## Introduction to Flux

Flux is the uni-directional data flow everyone is talking about these days. Contrary to the bi-directional data flow of Angular - Flux relies on a communication and storage loop which flows in only one direction. It does this through the use of Actions, Dispatchers, and Stores.

For illustrative purposes - we can begin the conceptual journey of Flux with the View layer. When a User manipulates our application's UI - an Action is triggered. This excited Action will then trigger a Dispatcher to then influence state living within our Stores. The Stores will then update the View layer with this new state information and data. Round and round this activity loop goes - delivering a robust and efficient UX. When our applications operate more efficiently - our users are happier - and that is the ultimate goal.

We are happier too however - Flux - in all its uni-directional splendor - offers much in the way of UDX as well! That cyclical nature of data transformation makes debugging much easier - with fewer points of fragility versus a bi-directional exchange such as the one offered by Angular. The end result is a very refreshing developer experience - creating another important loop - happy developer - happy user.

Back to Stores - as mentioned much of our state will be housed here. That is not to say View components won't retain some state information - that is certainly a possibility sometimes. But by removing state from the View component - we can manipulate Stores directly with Actions. This applies to concerns such as API communicaiton, caching, i18n etc. For example - we could direct an Action to trigger an API query which updates our Stores based on the result.

flux data flow (from fb page)

It is important to note that implementing Flux architecture may increase the amount of code in your application. However - its goal is not to minimize your codebase. Flux was designed to enhance productivity across large teams - with a foundation in explicit rather than implicit.

As of this writing - there are already many Flux implementations available. This link provides helpful comparisons for some of the more popular ones. We will be using Alt in this book.

**Comment by bebraw** [comment]
Hey, no need to close this. I liked the proposal. :+1:

**Comment by Cryptolemming** [comment]
Okay, great.  Glad to help :)

**Comment by bebraw** [comment]
@Cryptolemming Please have a look at the new version at the repo. I integrated some ideas of yours into it. Hopefully it's a bit more like it now. :+1:
