### ISSUE TITLE
Implementing a Basic Note Application - Explanation before text

### ISSUE THREAD

**Issue by Foxandxss** [survivejs/webpack_react#183]
Normally when I want to introduce a new snippet, I follow the next rule:

I introduce the next snippet, something like: "We will now implement the notes of our application:"

I put the snippet.

Now the user will be familiar with it so I can explain the stuff we did in there.

-----

That is a valid rule. You could potentially give a "preview" of what is he/she going to see, but something small and easy to remember.

So let's talk about "Connecting Data with App"

The user knows nothing about react, nor its ideas, so you start with:

>The next step is connecting this data model with our App. As it will be quite a bit of code I've included whole solution below. We'll improve the solution later on. The current solution is the simplest way to render a list of notes.

This is fine, this is what I was referring with "Introduce a new snippet". Not that I am fan of including whole solutions at once but this one is rather small.

The problem now is that you explain a lot of new features the user is not familiar with and you practically describe the entire snippet without seeing it.

>We will use a special feature of JSX in form of {}. 

Ok, that is good, could work if we had a short "Introduce a new snippet" section and we added it like "and here we will see how to use a special feature of JSX in form of {}".

But not here.

>Within these braces we can mix JavaScript with JSX.

Now you start explaining something we still don't understand (what is that `{}` all about).

>In this case we will render a bunch of li elements. Each contains a Note.

At this point the user will likely want to read the snippet because he would be already lost. It is adding something in top of something they don't understand which is in top...

Lastly you say:

>In order to tell React in which order to render the elements, we'll set key property for each. It is important that this is unique or otherwise it won't be able to figure out the correct order in which to render and it will give a warning about this.

This is just add more stuff into the user brain.

---

The potential issue with adding all this information before a snippet is that you're forcing the user to remember this things literally in their head without really understanding. Then they do the snippet and they have to go back again to that text.

It is better to simply introduce the snippet in a simple way (like you did in the first paragraph) and maybe excite the user a bit "We will see how awesome JSX is" (to say something).

Then you put the snippet, the users code it and they will notice that `{notes.map(...)}` and then will note that `key` thing.

They will code it, they will try to apply their logic to it (which is fine, that trains them).

Now is time to put those snippets. Something along this lines (with an extra explanation of why we do this in this way):

"React doesn't have a mechanism (like a component) to render a list of items. Instead thanks to our ability to write Javascript code into our JSX, we can use Javascript's `.map` function to iterate the array to generate a new `<Note />` with each item.

We can do that thanks to a special feature of JSX in form of `{}`. Within these braces we can mix Javascript with JSX. There is where we put or .map function. (I think that at this point there is no real need to explain why we decided to move the .map function to an external function).

So for each note, we will generate a `<li>` item containing a `<Note />` component.

Notice the `key` attribute on the `<li>`. Why do we need that? In order to tell React in which order to render the elements, we need to set a `key` property in each element. It is important that this is unique or otherwise it won't be able to figure out the correct order in which to render and it will give a warning about this.

Last but not least, in order to pass the note's task to each `<Note />` we will use an attribute that we decided to call `value`."

This last bit of "we decided to" is important, because you decided to use `value` as the attribute name and people will likely think that `value` is a built-in thing in react. To be honest I would picked a different attribute name than "value" to confuse less.

**Comment by bebraw** [comment]
I think we went through these together quite thoroughly. It should be much better now. Thanks. :+1:
