### ISSUE TITLE
Getting error in DragManager

### ISSUE THREAD

**Issue by winkler1** [survivejs/webpack_react#2]
Hi-
 Wanted to see the end result, so jumped to project_source/08_polishing_kanban/kanban_app, do `npm run dev`, get this at DragDropManager:30  ("this.backend = createBackend(this);")
Uncaught TypeError: undefined is not a function

Thanks -- looking forward to checking out this book and recommending it to team members!

**Comment by bebraw** [comment]
@winkler1 Yeah, that chapter is heavily work in progress and pretty broken at the moment. Thanks for letting me know, though!

Part of the problem is that [react-dnd](https://github.com/gaearon/react-dnd/) is still under development (no stable version with ES6 support out yet) but I'm hoping this will change soon. Same goes for baobab.

**Comment by winkler1** [comment]
Gotcha, thanks. Would be great to get an online demo to draw attention when things stabilize! :)

 This is challenging work you're undertaking - cutting edge stuff - how do you deal with having a series of checkpoint dirs like "08_polishing_kanban". Eg: if the react-dnd version changes, do you have to update it in 8 places?

**Comment by bebraw** [comment]
> Gotcha, thanks. Would be great to get an online demo to draw attention when things stabilize! :)

Absolutely. A companion site with content/demos is something I'm thinking about.

> This is challenging work you're undertaking - cutting edge stuff - how do you deal with having a series of checkpoint dirs like "08_polishing_kanban". Eg: if the react-dnd version changes, do you have to update it in 8 places?

Yeah. If I change something early on it ripples through. Unless it's a big change (naming etc.), it's not too much work.

**Comment by bebraw** [comment]
Companion site and demos are up. See http://survivejs.com/webpack_react/implementing_dnd/ for a sample.
