### ISSUE TITLE
Show how to implement Flux yourself and push Alt to a separate chapter?

### ISSUE THREAD

**Issue by bebraw** [survivejs/webpack_react#200]
The good thing about discussing Flux through Alt is that it's fairly simple. The problem with this approach is that if the book goes to print, it will become obsolete as soon as Alt changes its API. Showing how to implement Flux yourself would remedy this problem but would add more complexity to the example. We could push possible Alt discussion to a chapter of its own in this case.

What do you think?

**Comment by Foxandxss** [comment]
Uhmmm, I have mixed feelings. On the one hand, it sounds good, but on the other hand I am not sure that it is really needed.

To be honest I would drop alt for redux :P

**Comment by bebraw** [comment]
> Uhmmm, I have mixed feelings. On the one hand, it sounds good, but on the other hand I am not sure that it is really needed.

I suppose the real question is how much extra complexity would it add. It would feel right to be library agnostic and leave the choice to the reader.

> To be honest I would drop alt for redux :P

Yeah, that's one option. Redux is Flux inspired and doesn't exactly implement it as discussed by Facebook.

I imagine ideally we would have book structure like this:

1. Setting up Webpack - As is
2. Developing Kanban Application - As is, we just get something concrete together here
3. Alternative Architectures - Redux, Baobab, Relay, Isomorphism(?)
4. Advanced Techniques - As is

This means we could push interesting technologies like Redux into the third part and show pros/cons against our demo app. I expect it will end up with around 4-5 brief chapters and it's likely something that sets up apart a bit.

**Comment by Foxandxss** [comment]
It is your book at the end of the day, but this is almost transforming it into a different book. I am happy with the way it sits now, some changes on concrete stuff but not in content.

**Comment by bebraw** [comment]
Yeah. I suppose the problem is where to draw the line. I wouldn't expect it to be a long part. It's more about making people aware of possible options. It feels like the current edition takes you from apprentice to journeyman when we should be aiming for master instead. That's where advanced knowledge about architecture would come in as it would allow the readers to make better choices. That said there's enough to do even without an extra part so we can leave this idea hanging for now.

**Comment by Foxandxss** [comment]
Title are titles, no book will get you to master.

The problem with explaining raw flux is that you need to add and explain lot and lot of extra boilerplate (Dispatcher, subscribe to events, desubscribe, emit changes, register actions from dispatcher, etc).

It is something that is good to know, that is true, but I am not so sure if it is the right thing to do.

**Comment by dbunskoek** [comment]
I would switch Alt with Redux, and call it a day :) Redux is gaining a lot of traction these days, as are all other technologies you explain in your book. Alt was a bit of an outlier from the get-go, but it was interesting to see such a small-footprint Flux implementation. If only it were used by more people :)

**Comment by arackaf** [comment]
I would definitely leave Alt, or switch to a competing library if you're really so inclined.  

Rolling your own flux implementation would be really cool, and would make a neat chapter to follow Alt; first the reader learns how to use a Flux library, then how to make one from scratch.

**Comment by bebraw** [comment]
Thanks for the pointers guys! I will have to port the application to Redux, see how that goes and make a decision based on that.

There's probably room for a little guide about React related architectures so dropping the part in favor of that could be a good idea. No need to bloat this book too much. :+1:

**Comment by ab2qik** [comment]
As effort has already been put into writing about Alt i'd say leave it in. In addition to Alt a write up on Redux followed by a Flux/dispatcher from scratch would be good coverage. May sound a little bloated but you'd  present a Facebook approach to Flux/dispatcher and then something cutting edge. According to Abramov, v.1.0 due very soon which would mean a bit more stability in code base.

**Comment by arackaf** [comment]
^^ that sounds like great advice.  And if you already have Alt coverage I'd make sure Redux adds serious value.  As you said, you want to avoid bloat, and your time's probably pretty valuable too :)

**Comment by taitsmp** [comment]
Personally I was happy to see Alt covered in SurviveJS.  This is one of the reasons I bought this book.  I follow Alt relatively closely and I agree that there appear to be API changes coming soon. You are right to be concerned.  However, I do think you'll be able to make tweaks and keep up with changes without too much effort.  

Both seeing an app built in Reflux or rolling your own simple flux framework would be interesting topics.

**Comment by bebraw** [comment]
Yeah, the problem with running after the newest cool thing is that it gets old pretty soon. I think I've found a good compromise, though. The blog is perfect for this sort of extra content!

For instance I collaborated with the author of [mobservable](https://mweststrate.github.io/mobservable/) this week. We built [a little demo](https://github.com/survivejs/mobservable-demo) together based on the examples discussed at the book. A blog post will go out next week.

I imagine I could do the same thing with other solutions. Eventually we should end up with a series of implementations based on the same idea and end up with a way to benchmark solution. I know Kanban is not the best possible example but it's complex enough to exercise certain capabilities (reference handling and so on) in more detail than TodoMVC.

**Comment by taitsmp** [comment]
I know you're trying to provide the best possible product and I appreciate that.  I bought the book b/c I felt you did a great job of choosing relevant topics.  I was really happy to learn more about webpack, react-dnd, alt, and more all in one place!  Keep up the good work.

**Comment by bebraw** [comment]
I'll be retaining the Alt portions as is. The plan is to develop some supporter specific content and then go for a wider Amazon release. I've outlined [the plans in more detail](http://survivejs.com/blog/survivejs-17/#the-current-plan) at the blog.

Going for a bigger rewrite to integrate redux or such wouldn't work given there's only limited amount of time. Given a few months it's the same situation again. :)

That said I will want to cover alternative approaches through the book blog. It will work as a more freeform way to explore the topics. This also helps in marketing. That's one of those areas where I'm sorely lacking at the moment.

Thanks for the feedback guys!
