### ISSUE TITLE
You can exit Node.js cli by hitting CTRL-C twice. (isn't Ctrl-d better)

### ISSUE THREAD

**Issue by kim0** [survivejs/webpack_react#201]
As a Unix admin by profession .. ctrl-d seems much better to me. It signifies end of input thus the interpreter has no reason to exist anymore. It's the standard way to end any stdin, which what we're typing into node is

**Comment by bebraw** [comment]
Great point. Thanks for pointing this out. I'll fix this for the next release.

**Comment by bebraw** [comment]
Done at `dev`. Thanks!
