### ISSUE TITLE
Sourcemap instructions for  v1.6

### ISSUE THREAD

**Issue by brownieboy** [survivejs/webpack_react#204]
Juho,

This is for the Developing With Webpack chapter, page 19 of the PDF (version 1.6).

You say that you're about to modify webpack.config.js to enable sourcemaps, by way of the devtool parameter.  But in the example webpack.config.js file that immediately follows, the devtool parameter is set to "eval".  Looking at the Webpack documentation, shouldn't this be set to "source-map" instead?  

I certainly couldn't see any sourcemap info in my browsers when devtool was set to "eval"!

As a suggestion, you might also want to say a few words about how you actually *see* the original, source-map generated files in Chrome and Firefox.  It won't be immediately obvious to all developers, I think.  For example, there's checkboxes that need to be ticked to make them visible, and I can't remember if that feature is enabled by default for either browser.  (Lord knows what IE does.)

**Comment by bebraw** [comment]
Yeah, `eval` is used specifically because this is a development configuration. I use `source-map` for production configuration later on in the book. `eval` will generate `//@ sourceURL` statements to the JavaScript bundle for the browser to pick this up.

I altered the description based on your pointers (61e87070a9abfcb9ff49c53ca6c4c5552e3dc99d). Please check that out.

Thanks a lot for the comment. It's so easy to miss these kind of details. :+1:

**Comment by brownieboy** [comment]
Thanks for the reply, Juho (bebraw),

Is this an issue of build speed then?  Reading around some forums, build times appear to be much quicker when using devtool: "eval" than for when it's set to "source-map", or for any one of its options that are kind of in between those two (see documentation at http://webpack.github.io/docs/configuration.html#devtool ).  There's an interesting discussion of this topic at https://github.com/webpack/webpack/issues/168, FYI.

I can't see what other advantage that "eval" generated "source map" might have; they're barely readable to this developer!!  For small, test examples, where build time differences are negligible, I think I'd use "source-map".

Also, as related question, when using webpack-dev-server are sourcemaps supposed to update, on the fly, when you update the underlying source code modules?  I ask because it's not happening for me, whether I use "source-map" or "eval" for my devtool setting.

Keep up the good work by the way.  (And yes, I bought your book!)

**Comment by bebraw** [comment]
> Is this an issue of build speed then?

Yeah, I think this is the main reason why it's the default in so many places.

> I can't see what other advantage that "eval" generated "source map" might have; they're barely readable to this developer!! For small, test examples, where build time differences are negligible, I think I'd use "source-map".

I asked about the defaults. Apparently @taion likes to use `eval-source-map`. Based on the docs the initial build will be slow but rebuild fast. It also yields original source as output so maybe this would be a good compromise? I don't mind changing it to a good default to avoid frustration.

> Also, as related question, when using webpack-dev-server are sourcemaps supposed to update, on the fly, when you update the underlying source code modules? I ask because it's not happening for me, whether I use "source-map" or "eval" for my devtool setting.

Yeah, I would expect sourcemaps to update as well. We might have some debugging to do here.

**Comment by brownieboy** [comment]
> We might have some debugging to do here.

I'm stripping this back to basics with a simple "Hello, world!" app; not even any React in it at this point.  So far, webpack-dev-server is updating my single source map, on the fly, as you would expect.

I'll start adding stuff back in and see if/when it fails to update the source map.

**Comment by bebraw** [comment]
> I'm stripping this back to basics with a simple "Hello, world!" app; not even any React in it at this point. So far, webpack-dev-server is updating my single source map, on the fly, as you would expect.
>
> I'll start adding stuff back in and see if/when it fails to update the source map.

Ok, cool. Keep me in the loop. :+1:

**Comment by brownieboy** [comment]
Here's the stripped down "Hello, World" test app that I mentioned: https://github.com/brownieboy/webpack-dev-server-test

In my testing, the source maps don't update correctly whenever react-hot is used as a loader for webpack-dev-server.

If I don't use react-hot then the source maps do update correctly, but at the expense of proper hot loading: i.e every rebuild causes a full page refresh.

Please look this over and let me know if you think I've set up anything incorrectly.

**Comment by bebraw** [comment]
@brownieboy Can you confirm this behavior against https://github.com/gaearon/react-hot-boilerplate ?

**Comment by taion** [comment]
`eval-source-map` is generally preferred for development - it's a lot faster than full-fledged source maps, but still gives you mappings to line/column numbers for debugging, unlike `eval`.

**Comment by bebraw** [comment]
@taion Thanks for confirmation! :+1: That's the current recommendation at https://github.com/survivejs/webpack_react/commit/ea3b67a87a5fedb3274b419ac38e4e36768c065b .

**Comment by brownieboy** [comment]
Source maps don't update correctly with the react-hot-loader for any devtool value that I've set.  I've just added a fourth test, for "eval-source-map":  https://github.com/brownieboy/webpack-dev-server-test

TL:DR:
* Source maps don't update at all when devtool is set to "eval" or "eval-source-map".
* Source map will update for devtool = "source-map", but only for the first update/rebuild.  Subsequent update/rebuilds do not changed the source maps.
* Source maps update correctly for any devtool value when "react-hot" is not used as a loader, but at the expense of a full page refresh.  (So not really hotloading at all.)

**Comment by brownieboy** [comment]
@bebraw,

I've tested against https://github.com/gaearon/react-hot-boilerplate as per your suggestion.

The results are pretty much the same as I saw in my own, earlier testing: source maps are not updated when react-hot is used as a loader.

The only difference that I saw was for the source-map test _without_ react-hot being used.  In that case, the page didn't reload, so the source map didn't update.  The console generated the message "[HMR] The following modules couldn't be hot updated: (They would need a full reload!)" for that case.

**Comment by brownieboy** [comment]
I've just posted this as a new issue on the react-hot-loader repository: https://github.com/gaearon/react-hot-loader/issues/180

**Comment by bebraw** [comment]
@brownieboy Thanks for your efforts. Hopefully some solution will be found! I subscribed to that issue.

**Comment by gaearon** [comment]
We can't update sourcemaps anyhow, it's browser's job.
I guess you can star this Chrome issue: https://code.google.com/p/chromium/issues/detail?id=492902.

**Comment by brownieboy** [comment]
As per the comment from @gaearon, this looks to be a bug in Chrome (and also Firefox).

Apple Safari is the only browser that I've tested which updates source maps correctly.  I haven't tested IE at all.

I'm going to close the issue here then.
