### ISSUE TITLE
React and Flux - NoteStore requires import of Note component

### ISSUE THREAD

**Issue by rusmo** [survivejs/webpack_react#206]
When first implementing the NoteStore, I had to add an import of the note component to get the Note.checkEnter() and Note.finishEdit() functions working again.

in app/stores/NoteStore.js:

import alt from '../libs/alt';
import note from '../components/Note'; // added this line
import NoteActions from '../actions/NoteActions';

Hope this helps,
Will.

**Comment by bebraw** [comment]
Thanks. That sounds interesting.

I'll leave this open for now. Let's have another look after I get `1.7` out. There's a nice bunch of changes coming up and it's possible this issue has disappeared in the process.

**Comment by bebraw** [comment]
@rusmo `1.7` is out now. Can you have another look?

**Comment by rusmo** [comment]
I've moved on in the tutorial, and am now stuck on a different issue. Is there an easy way to reset my repo to the beginning of a section? If there is I may be able to spend some time on this later in the week.

Thanks!

**Comment by bebraw** [comment]
Sure. Pick up the state you need based on the previous chapter from [project_source](https://github.com/survivejs/webpack_react/tree/master/project_source).

If you want personal help, poke me through [gitter](https://gitter.im/survivejs/webpack_react). If I'm around, I'll help you out.

**Comment by bebraw** [comment]
@rusmo Any luck? Note that I published a new version (`1.8.0`) so you might have another look.

**Comment by bebraw** [comment]
@rusmo I'm closing this for now. Feel free to re-open if you can repro in the current version. :+1:
