### ISSUE TITLE
typon on page 16

### ISSUE THREAD

**Issue by jorda0mega** [survivejs/webpack_react#212]
There is a typo on page 16 (or at least it didn't work for me) where the following line

```javascript
"scripts": {
"start": "webpack-dev-server"
}
```
should read
```javascript
"scripts": {
"start": "webpack-dev-server --hot --inline"
}
```
in order to have HRM working on chrome. Without those parameters I kept getting an exception where HRM was not available

**Comment by bebraw** [comment]
Hi,

Thanks for the report. I assume it's this section: http://survivejs.com/webpack_react/developing_with_webpack/#setting-up-webpack-dev-server- .

Did you put those `devServer` and `webpack.HotModuleReplacementPlugin` bits to your config?

Which operating system are you using? I can try to give it a go myself.

**Comment by jorda0mega** [comment]
correct. that is the section I was referring to. Yeah, I setup both of those but was still getting a an error on chrome. [this](https://github.com/webpack/webpack/issues/1151) issue helped. I am using Yosemite. Let me know if you need more info.

**Comment by bebraw** [comment]
@jorda0mega Ok. Can you push the failing version of the project to GitHub? Incidentally I'm on Yosemite too but I'm failing to reproduce the problem. I would love to understand what I'm doing differently. :+1:

I did some digging btw. It all starts at https://github.com/webpack/webpack-dev-server/blob/master/bin/webpack-dev-server.js#L49 . By the looks of it that catches `devServer` configuration from `webpack.config.js`. After that it does some checks against `argv` to override those values. Finally it does some extra work based on the `inline` setting.

Based on that the biggest mystery to me is that why `webpack.config.js` `devServer` configuration wouldn't be equal to `webpack-dev-server --hot --inline`.

On a related note it looks like `webpack-dev-server` checks against terminal colors automatically using [supports-color](https://www.npmjs.com/package/supports-color) so `colors` flag can be safely dropped. Colors will just work.

**Comment by jorda0mega** [comment]
Seems like it was indeed cached. I cannot reproduce anymore on the current setup. Let me see if I can try rolling back to when it first appeared. Sorry for having you dig into this issue. I will try to find something on my end. Thanks for the responsiveness :)

**Comment by bebraw** [comment]
@jorda0mega It's ok. I already learned something new during this and we'll get a better book as a result. :+1:

**Comment by bebraw** [comment]
I did the `colors` fix for `dev`. That will make it to the next release.
