### ISSUE TITLE
GraphQL/Relay Chapter

### ISSUE THREAD

**Issue by bebraw** [survivejs/webpack_react#22]
Way too early for this but better have a stub here.

**Comment by xgrommx** [comment]
@bebraw As alternative now exists a similar library https://github.com/RickWong/react-transmit for GraphQL/ Relay.

**Comment by bebraw** [comment]
Nice. Thanks for linking!

**Comment by bebraw** [comment]
Closing this as it's duplicate with #76. If we write a backend chapter, it's better to cover all of this there.
