### ISSUE TITLE
Developing with Webpack - Highlighting lines updated

### ISSUE THREAD

**Issue by montogeek** [survivejs/webpack_react#224]
Hi!
You show me your book a few weeks ago over a Slack channel and today I start to reading it, so far so good, thanks for make it! <3

There is one thing that I want to improve in the book, it's difficult to follow which lines changed in the code examples since the last code example, there is some `...` to mark the old code but is not intuitive and forgettable.

I want to implement [Prism.js](http://prismjs.com/plugins/line-highlight/), a code highlighter, where you can highlight specific lines or a group of line or a combination of both.

I personally will through all the chapters updating which lines changed.

I do not know how this can affect the Leanpub version.

Thanks!

**Comment by bebraw** [comment]
Yeah, I agree that's one of the main pain points. It would be great to resolve this.

Leanpub actually provides something for this. See https://leanpub.com/help/manual#leanpub-auto-code-samples . That could be a starting point. If that works, we can preprocess the examples as needed to fit whatever format we need.

I suppose ideally we could resolve the whole issue without any client-side JS. Now I just render the examples through highlight.js when generating the site and apply CSS to it. If the same can be achieved based on the Leanpub syntax, that would be the best.

If Prism can be tweaked to do this, that would be just awesome.

**Comment by stevepiercy** [comment]
FWIW, here's marking lines in code blocks https://leanpub.com/help/manual#leanpub-auto-marking-lines-as-deleted-or-added-to-a-code-block

In Pyramid's SQLAlchemy + URL Dispatch Wiki tutorial, we use .rst through Sphinx and highlighting with Pygments. Here's an example of highlighting ("emphasize-lines", "lines", and "line-nos" in .rst).
http://docs.pylonsproject.org/projects/pyramid/en/latest/tutorials/wiki2/authorization.html#add-authentication-and-authorization-policies

And one from my site.
http://www.stevepiercy.com/articles/virtual-urls-with-apache-and-lasso-saving-the-environment-variables/#mod-rewrite-with-define-atbegin-for-lasso-8

**Comment by bebraw** [comment]
@montogeek FYI, the site is running on Prism so we are half-way there now.

**Comment by montogeek** [comment]
Great!

**Comment by omidfi** [comment]
just wanted to +1 the idea that we need to improve this :)

**Comment by montogeek** [comment]
Hi! Today I come to this gist. GitHub Flavored Markdown allows you to use the `diff` command to show differences in the code:

Live example:
Use the `diff` code highlighting tag.
```
  ```diff
  - foo
  + bar
```

Example:

```diff
-function () {
+function greet() {
   console.log('Hello world');
 }
```

https://gist.github.com/staltz/728a18877948f059d570

**Comment by bebraw** [comment]
@montogeek Thanks for the idea! The great thing about this is that it would work with the site without tweaking. Just need to see what it looks like in book form. :+1:

**Comment by bebraw** [comment]
Quick update on this. I managed to bend Prism to support Leanpub add/delete syntax. Here's a sneak peek:

![screenshot 2015-12-14 19 34 10](https://cloud.githubusercontent.com/assets/166921/11788483/ee9708e4-a299-11e5-81e4-87d9f602caf7.png)

**Comment by montogeek** [comment]
Nice!

**Comment by bebraw** [comment]
I went through the material and applied highlighting where it made sense. I will do some further testing on this to make sure the changes are ok. Overall it should be easier to follow what's going on even if it's not as simple to copy/paste always.

**Comment by zweicoder** [comment]
Should the highlighting be working on the `.md` files in the repo? Cause I'm only seeing the raw text like this 
![image](https://cloud.githubusercontent.com/assets/3684550/12353676/bfeeb2e4-bbcb-11e5-8b9a-a016eddb67ca.png)

**Comment by bebraw** [comment]
@zweicoder Nope. It relies on custom syntax at the moment and there's no way to do any sort of custom formatting within GitHub code blocks.

Maybe a good alternative would be to host the `dev` branch output online? It would take some setup but might be worth it. I'm not sure if this is a priority thing yet, though. :smile:

**Comment by zweicoder** [comment]
@bebraw haha it's okay, I'll just read it from the site :) Nice work btw!

**Comment by bebraw** [comment]
@zweicoder Ok, cool. Feel free to contact me directly if you have any questions/comments. Just pushing it forward constantly. :+1:
