### ISSUE TITLE
React and Flux - Missing import 'array.prototype.findindex'; in NoteStore.js

### ISSUE THREAD

**Issue by leevigraham** [survivejs/webpack_react#229]
Following the tutorial I couldn't see anywhere that NoteStore.js should `import 'array.prototype.findindex';`
 Without it `Uncaught TypeError: notes.findIndex is not a function` is thrown.

**Comment by bebraw** [comment]
Interesting! What browser are you using?

The idea is that `findIndex` should get shimmed at `app/main.jsx` but for a reason I don't understand yet that's failing.

**Comment by leevigraham** [comment]
Looks like I took it out of main.jsx for some reason :disappointed:

**Comment by bebraw** [comment]
No worries. Thanks for the effort! :+1:
