### ISSUE TITLE
React and Flux - Style issue on Alt image

### ISSUE THREAD

**Issue by davegomez** [survivejs/webpack_react#239]
As you can see on this screenshot there's a style issue related to the Alt image you have in your book at 845px width for instance.

http://i.imgur.com/5wK9aKi.png

Nevertheless is easily fix changing these rules:

```
.post__content img {
    max-width: 100%;
    width: 100vw;
}
```

**Comment by bebraw** [comment]
Good catch. Fixed on the site.
