### ISSUE TITLE
Open default browser automatically

### ISSUE THREAD

**Issue by davegomez** [survivejs/webpack_react#240]
I wonder if you are interested in adding the possibility to open the default browser automatically once the Webpack bundle is compiled.

A friend just develop a small plugin to accomplish this when you use Webpack Dev Server as you do in your book.

You can find the plugin here https://github.com/baldore/open-browser-webpack-plugin

Hope you like it!

**Comment by bebraw** [comment]
Yeah, this is a worthwhile idea.

I would also love to get a bell plugin for webpack. The idea is simple, just hit the bell on error. It sounds trivial but actually helps a lot if you like to use multiple desktops. But that's for another day.

**Comment by bebraw** [comment]
Thanks. I added a tip about this so people can configure the plugin if they like.
