### ISSUE TITLE
nav in mobile breakpoint

### ISSUE THREAD

**Issue by Guria** [survivejs/webpack_react#241]
* there is no way to hide menu once opened
* floating nav items occupies to much space
![](http://pix.toile-libre.org/upload/original/1442320303.png)

**Comment by bebraw** [comment]
Good catch. Thanks. I'll need to figure out something for that.

**Comment by bebraw** [comment]
Thanks! It should be fixed now.

If you find more glitches like this, please report directly at the [site issue tracker](https://github.com/survivejs/site/issues). :)
