### ISSUE TITLE
Developing with Webpack - gitignore

### ISSUE THREAD

**Issue by Guria** [survivejs/webpack_react#242]
There is [good recommendation](http://technicalpickles.com/posts/configure-git-to-globally-ignore-some-files/) to put [os and editor specific ignores](https://gist.github.com/octocat/9257657) to [global .gitignore](https://help.github.com/articles/ignoring-files/#create-a-global-gitignore) instead of projects one.

**Comment by bebraw** [comment]
Thanks! That's a good point.

**Comment by bebraw** [comment]
Fixed in the next revision. :+1:
