### ISSUE TITLE
Chapter on using 3rd party libraries (css/js) and linting concerns

### ISSUE THREAD

**Issue by kevinduffey** [survivejs/webpack_react#244]
So.. I was using React bootstrap libraries, but we are also looking at using Foundation. Ideally what would be great is a chapter on how you can incorporate any 3rd party JS/CSS library like foundation, bootstrap, maybe even roll your own, but still be able to use it within React.

A big issue I am seeing is that the linting setup is flagging all the 3rd party JS/CSS with issues like double quotes over single quotes, spacing, etc. I basically am thinking of not using any linting because I cant get past the errors to get work done. 

So perhaps a chapter around this process would be a good addition?

**Comment by bebraw** [comment]
A whole chapter would be a bit much. I'll see if I can find suitable spots in the current material for these sort of tips.

**Comment by bebraw** [comment]
> A big issue I am seeing is that the linting setup is flagging all the 3rd party JS/CSS with issues like double quotes over single quotes, spacing, etc. I basically am thinking of not using any linting because I cant get past the errors to get work done.

Probably the important thing here is that if you set up ESLint, make sure to set its ignore rules carefully.

I pushed the 3rd party idea to my blog stash. It would make a nice little post for sure.
