### ISSUE TITLE
More visual cues for DnD

### ISSUE THREAD

**Issue by jvanzyl** [survivejs/webpack_react#245]
The examples for React DnD on their site give the user more visual cues as to what is being done during the DnD operations. When you click and move items around their outlines follow the mouse around so you can see where the source is moving which makes it easier to see what target you're going to drop it on. I'm not sure if there are options that can be set, but in the Kanban example app you click and move the mouse and all of a sudden the note moves. It would be nice to see how to implement the other notes moving out of the way to make way note being dropped in its new location.

**Comment by bebraw** [comment]
Yeah, that's a valid point. I can imagine a little section just for this.

**Comment by bebraw** [comment]
There's a little bug in React DnD blocking this type of work. See https://github.com/gaearon/react-dnd/issues/292 . Hopefully that gets resolved so we can get a better implementation in place.

**Comment by gaearon** [comment]
I don't think it's a bug; should work with custom `isDragging` function.
https://github.com/gaearon/react-dnd/issues/292#issuecomment-144781478

**Comment by bebraw** [comment]
Implemented in the next version. Now it shows a blank space at note target while you are dragging. Much cleaner this way.

Thanks guys!
