### ISSUE TITLE
material-ui

### ISSUE THREAD

**Issue by tschnoelzer** [survivejs/webpack_react#246]
Hi team,

I would like to integrate material-ui into kanban. It should be straightforward but can't find a way. Any clue? perhaps a new chapter for the book?!?!

best
Timo

**Comment by bebraw** [comment]
Probably not a chapter. Most likely a demo and a blog post. ;)

I know there are multiple Material UI libs for React. Can you look into those? We could do a little comparison.

**Comment by tschnoelzer** [comment]
I found this callemall/material-ui to be good organized. Personally I have some angular / dart experience and be new to react. this material implementation is component based and should be easy to integrate.

**Comment by tschnoelzer** [comment]
Actually it was a misunderstanding in the use of "createClass" and an ES6 Class of the books example. I had to put the 

App.childContextTypes = {
       muiTheme: React.PropTypes.object
};

below the class definition and 

getChildContext(){
        return {
            muiTheme: ThemeManager.getCurrentTheme()
        };
}

inside.

The point was, that I missed to bind the method in the Constructor:

this.getChildContext = this.getChildContext.bind(this);

With this, all was up and running! 

For me this explanation was helpful: 
http://www.newmediacampaigns.com/blog/refactoring-react-components-to-es6-classes

When sleep2work ratio gets better again, I will provide a simple demo. I expect material design to become more and more relevant to nowadays projects ...

**Comment by bebraw** [comment]
Yeah, that `this.getChildContext = this.getChildContext.bind(this);` is easy to miss. This should get nicer in the future with property initializers. Then we can do something like `getChildContext() => {` for the same effect.

Great to hear you got it working.

**Comment by bebraw** [comment]
Feel free to link me to the demo once you get one done. I feel this could be a good topic for a blog post but it's a bit much for the book itself. Blog is perfect for additional material like this. :+1:
