### ISSUE TITLE
Implementing a Basic Note Application -

### ISSUE THREAD

**Issue by Swelly** [survivejs/webpack_react#247]
I love this guide, it's by far the best intro to React I've found. But I'm having an issue (http://survivejs.com/webpack_react/implementing_notes/#pushing-notes-to-the-app-state-) I am getting the error

##### "Uncaught Error: Invariant Violation: App.render(): A valid ReactComponent must be returned. You may have returned undefined, an array or some other invalid object."

But my app is exactly as is in your guide with some added packages for Sass loading
https://github.com/Swelly/kanban_app

**Comment by Swelly** [comment]
I never called a return on the App.jsx render function -_- sorry for that.

**Comment by bebraw** [comment]
Great to hear you got it. :+1:
