### ISSUE TITLE
06_from_note_to_kanban : LaneStore.js missing findLane function

### ISSUE THREAD

**Issue by oiledCode** [survivejs/webpack_react#249]
In the code shown for NoteStore you call 

````
const targetId = this.findLane(laneId);
````

now it is fairly simple to understand what findLane does, since is the same concept used earlier, but IMHO I think the implementation should be in the code shown in the book for the sake of clarity.
What do you think?

**Comment by bebraw** [comment]
I can see the problem. I should add a stub function to that code example and mention we'll be implementing it in a later section.

Thanks for bringing this to my attention. I'll get it fixed in the next revision.

**Comment by oiledCode** [comment]
Always for the sake of clarity, it would be cool if either the explanation of waitFor is expanded or a reference to an article is given. 

I say this because you advice to avoid its use where possible and, from my perspective of learner / reader, I would like to understand why. 

The reader can always do a simple search on google, but a good reference for me is one of the reason why you choose to read a book instead of checking some tutorial on the net.

BTW I am happy so far of having purchased your book, so thanks for your efforts in writing it :+1:

**Comment by bebraw** [comment]
Another valid point, I'll expand on `waitFor`. I agree it's a big fail if you have to Google things. :+1:

Feedback like this is very useful. Thank you.

**Comment by bebraw** [comment]
This will get sorted out in the next version.
