### ISSUE TITLE
5.1 Flux dataflow diagram description missing action

### ISSUE THREAD

**Issue by stevepiercy** [survivejs/webpack_react#252]
The narrative in https://github.com/survivejs/webpack_react/blob/dev/manuscript/05_react_and_flux.md is missing something for the View -> Action -> Dispatcher segment. I'm not entirely clear what it should be, but after reading the official docs, then it made sense to me. I don't want to copy/paste from the official docs, of course, but I'm not sure how to improve it while retaining your voice.

**Comment by bebraw** [comment]
I clarified the dispatcher bit so you can understand better why one is needed. It is possible it can be cleaned up further. Perhaps introducing *action creators* is the key?

**Comment by stevepiercy** [comment]
I think so. I think you've covered the left-to-right part of the diagram (Action -> Dispatcher -> Store -> View), but not the part that arcs up and goes right-to-left (View -> Action -> Dispatcher). How does a View create an Action, and how does that get fed into the Dispatcher, closing the loop? Additionally the sentence

> This completes the loop as Views listening to the Stores receive the data.

is confusing to me because at that point the flow is at the terminus of the left-to-right part of the diagram and has not yet emitted an Action.

![flux diagram](https://github.com/survivejs/webpack_react/raw/ed651a5205372b949ccc5db8b124fca166fd1858/manuscript/images/flux.png)

**Comment by bebraw** [comment]
> is confusing to me because at that point the flow is at the terminus of the left-to-right part of the diagram and has not yet emitted an Action.

Yeah, that's a puzzling one. I don't have a clear understanding of why it's in the diagram exactly. I always thought this meant you can trigger actions **outside** of views (i.e., app init(?), testing). It would be great to figure out the exact reason behind that one.

**Comment by stevepiercy** [comment]
The [official docs for Flux](https://facebook.github.io/flux/docs/overview.html) are pretty clear. They use two diagrams to (1) illustrate the basic, simplest flow, and (2) the more complex, optional flow where "views may cause a new action to be propagated through the system in response to user interactions".

**Comment by bebraw** [comment]
I wonder if it would make sense to add that uni-directional image there (first diagram) and discuss that looping part separately. So first we establish the idea of uni-directional flow and then generalize from that once the idea has been established.

**Comment by stevepiercy** [comment]
Sounds reasonable to me.

**Comment by bebraw** [comment]
Ok, updated. Technically there's more going on actually (action creators and all that) but I suppose it's enough if it gets the basic message across and why all those parts are needed.

I'll leave this open for now as you probably want to have a look.

**Comment by stevepiercy** [comment]
I've rewritten line 21. Hopefully that glues it all together. Please check to make sure I didn't make something become missing or repeated.

**Comment by bebraw** [comment]
It's good now. Much better than the version we started from. Thanks a lot. Feel free to close. :smile:

**Comment by stevepiercy** [comment]
:shipit:
