### ISSUE TITLE
Can't view source map in safari - Chapter 3.4 Activating Hot Loading for Development

### ISSUE THREAD

**Issue by idisblueflash** [survivejs/webpack_react#260]
I learned a lot from your book, thanks. And I met a small problem on Chapter 3.4. I can't use safari with source map after I finished wepack.config.js with this chapter.

for example: 
I added a ```console.log(x)``` to fake a typo mistake. In safari, I got:

```ReferenceError: Can't find variable: x ... undefined:24```

but Chrome works:

```Uncaught ReferenceError: x is not defined main ... index.jsx?283d:13```

when I clicked ```index.jsx?283d:13``` it brings me to the right place.

I need your help.

**Comment by bebraw** [comment]
Can you try some of the [other options](https://webpack.github.io/docs/configuration.html#devtool)?

I know source maps have issues in certain browsers and usage scenarios. There are problems with hot loading in particular.

**Comment by idisblueflash** [comment]
I tried all options in [other options](https://webpack.github.io/docs/configuration.html#devtool), only source-map works on both Safari 8.0.8 and Chrome 45.0.2454.101 on my Mac book air. With other options, Chrome works fine.

**Comment by bebraw** [comment]
@idisblueflash One alternative is that it's broken for Safari. Two more things to try:

1. Upgrade to Safari 9
2. Try [react-hot-boilerplate](https://github.com/gaearon/react-hot-boilerplate)

Let me know how it goes.

**Comment by bebraw** [comment]
@idisblueflash Any luck with this?

**Comment by idisblueflash** [comment]
I did a quick check with Safari 9 this morning:
Three options (source-map, cheap-source-map, cheap-module-source-map) works on Safari 9.0.

**Comment by bebraw** [comment]
Alright, great to hear Safari 9.0 works well! Closing. :+1:

**Comment by glosee** [comment]
So no plan for Safari 8 support theN?
