### ISSUE TITLE
Uncaught TypeError: Cannot read property 'WebSocket' of undefined

### ISSUE THREAD

**Issue by vamsiampolu** [survivejs/webpack_react#262]
I have added alt to the project and I have added `app/libs/alt.js`, `app/libs/persist.js` and `apps/libs/storage.js`. This is my `webpack.config.js` file. The bundle is valid but the page will not load.

```js
var webpack = require('webpack');
var path = require('path');
var HTMLWebpackPlugin = require('html-webpack-plugin');
var root = path.resolve(__dirname);
var merge = require('webpack-merge');
var TARGET = process.env.npm_lifecycle_event;
process.env.BABEL_ENV = process.env.npm_lifecycle_event;
var common = {
	entry:path.resolve(root,'app'),
	output:{
		path:path.resolve(root,'build'),
		filename:'bundle.js'
	},
	resolve:{
		extensions:['','.js','.jsx']	
	},
	plugins:[
	  new webpack.HotModuleReplacementPlugin(),
	  new HTMLWebpackPlugin({title:'Kanban App'})
	]	
};


//Extending the webpack configuration.

if(TARGET==='start'|| !TARGET) {
	module.exports = merge(common,{
		devtool:'eval-source-map',
		devServer:{
			historyApiFallback:true,
			hot:true,
			inline:true,
			progress:true,
			port:3100,
			colors:true
		},
		module:{
			loaders:[
				{
					test:/\.css$/,
					loaders:['style','css'],
					include:path.resolve(root,'app')
				},
				{
					test:[/\.jsx$/],
					loaders:['react-hot','babel']
				},
				{
					test:[/\.js$/],
					loaders:['babel']
				}
			]
		}
	});
}
```

**Comment by bebraw** [comment]
Hi,

I just updated the book. *react-hot* was dropped in favor of [babel-plugin-react-transform](https://github.com/gaearon/babel-plugin-react-transform). Can you try to update your setup to work against it?

You can also try running the book code examples and report me the results.

**Comment by vamsiampolu** [comment]
https://github.com/gaearon/react-hot-loader/issues/133 solved the issue.

**Comment by bebraw** [comment]
Ah, cool.

Btw I recommend moving to the Babel plugin as react-hot-loader has been deprecated. :+1:

**Comment by vamsiampolu** [comment]
Thanks @bebraw  I remove `react-hot-loader`  in favor of  `babel-transform-hot-loader` , I have also added the `react-transform-catch-errors` as suggested. It's all good  for now. My `.babelrc` is here.

> Should we enable `sourceMaps` in `babel` as well as `webpack`?

```js
{
	"stage":1,
	"sourceMaps":true,
	"env": {
	  "start":{
	  	"plugins":[
	  		"react-transform"
	  	],
	  	"extra":{
	  		"react-transform":{
	  			"transforms":[
	  				{
	  					"transform":"react-transform-hmr",
	  					"imports":["react"],
	  					"locals":["module"]
	  				},
	  				{
	  					"transform":"react-transform-catch-errors",
	  					"imports":["react","redbox-react"]
	  				}
	  			]
	  		}
	  	}
	  }
	}
}
```

**Comment by bebraw** [comment]
@vamsiampolu I found https://github.com/babel/babel/issues/2484 . Apparently `sourceMaps` doesn't do anything useful at the current version. Note that `react-transform-catch-errors` seems to work in a useful way only when you set `devtool: 'eval'` in Webpack!

I'll keep an eye on this as it would be great to have a setup that works reliably with redbox. I'm afraid it's not ideal yet due to tooling issues...
