### ISSUE TITLE
Implement a link checker

### ISSUE THREAD

**Issue by bebraw** [survivejs/webpack_react#263]
It would be very useful to have something to lint web links. Just need to get each, poke, and let know if something is broken.

**Comment by omidfi** [comment]
It's possible using a simple node script or a gulp task like this: http://stackoverflow.com/questions/24463719/is-there-a-link-checker-for-gulp

However my favorite way is using this chrome extension: 
https://chrome.google.com/webstore/detail/check-my-links/ojkcdipcgfaekbeaelaapakgnjflfglf

**Comment by bebraw** [comment]
Yeah, it's not a hard script to write now that I think of it. Just need to get all links through *marked* and hit them like in that SO link of yours. Might as well get this done. :)

**Comment by bebraw** [comment]
Done. Managed to find a little glitch to fix even. It has been hooked up with Travis so we can catch snafus before it's too late.
