### ISSUE TITLE
Styling React -jss

### ISSUE THREAD

**Issue by kof** [survivejs/webpack_react#264]
You forgot to mention jss, which has some significant differences to all other implementations.

**Comment by bebraw** [comment]
Yeah, that's a valid point.

I have to review the chapter and see what the current status of the solutions is.

**Comment by bebraw** [comment]
I dropped smart-css in favor of JSS. These solutions seem to move fast.

The change will be included in the next release. Thanks.

**Comment by kof** [comment]
Thanks, if you have any questions or something I am glad to help.

**Comment by bebraw** [comment]
Great to hear.

I probably need to devote some time for developing a proper example for each option covered and show how they work with Webpack. All in all, the whole styling situation is still in bit of a Flux with React.
