### ISSUE TITLE
chapter 6, From Notes To Kanban - why lane.notes instead of note.laneId?

### ISSUE THREAD

**Issue by chadoh** [survivejs/webpack_react#265]
In [chapter 6.3](http://survivejs.com/webpack_react/from_notes_to_kanban/#making-lanes-responsible-of-notes-), you guide me through setting up an architecture that seems very strange to me (I come from a Rails background, fwiw).

Creating a new Note with a `laneId` attribute super easy, and would avoid the complexity of `attachToLane` and `waitFor`. 

Maybe your intention is to teach about `waitFor`?

Full disclosure: I actually got stuck on this chapter, destroyed all my changes, and started the chapter again. This part is still making me scratch my head the second time through!

**Comment by bebraw** [comment]
> Creating a new Note with a laneId attribute super easy, and would avoid the complexity of attachToLane and waitFor.

This would work perfectly if we didn't have to worry about the ordering of Notes within a Lane. If we go this route, we still need to solve the ordering issue somehow and I didn't see any neat way to do it. It still needs to go somewhere and an array of ids seemed like a good solution here. It pays off in the DnD chapter.

> Maybe your intention is to teach about waitFor?

Yeah, I put some special emphasis on `waitFor` in `1.9.0`. I don't like `waitFor` particularly but it's needed here for synchronization. Interestingly solutions like Redux drop the requirement entirely.

Another reason for the current structure is the fact that I tried to keep a possible backend in mind. Something like a sorting operation would become a `PUT` over the `lanes` resource.

> Full disclosure: I actually got stuck on this chapter, destroyed all my changes, and started the chapter again. This part is still making me scratch my head the second time through!

I don't mind reworking the chapter. I'm particularly interested in knowing what are the most problematic parts. If we can make the timing work, it could be fun to do a little pair coding session on this over Twitch or something.

**Comment by chadoh** [comment]
> This would work perfectly if we didn't have to worry about the ordering of Notes within a Lane. If we go this route, we still need to solve the ordering issue somehow and I didn't see any neat way to do it.

Again coming from my Rails background, the common way to do this would be a `position` attribute on the `note` field. Which I'll admit, makes reordering perhaps slightly more complex than using your approach, since you'd have to update potentially _all_ notes in a given lane when one of them is dragged from the bottom to the top.

>  Interestingly solutions like Redux drop the requirement entirely.

I still haven't looked into Redux—sounds cool!

> Another reason for the current structure is the fact that I tried to keep a possible backend in mind. Something like a sorting operation would become a PUT over the lanes resource.

Here again, my Rails background is informing my thought process. There are [gems that make sorting very easy using a `position` column that lives on the Thing Being Sorted, rather than the Thing Holding The Sorted Items](https://github.com/swanandp/acts_as_list).

I might be mistaken in thinking this, but I believe the `parent_id` approach is a more standard RDBMS approach. It seems less error-prone to me, even though one ends up needing this `position` column on the child elements.

> If we can make the timing work, it could be fun to do a little pair coding session on this

That sounds cool! How long do you think it would take? I'm in GMT-0400, which doesn't seem too different from Suomi. My mornings are your afternoons. Maybe Monday for an hour? I've never used Twitch; I usually use G+ Hangouts.

**Comment by bebraw** [comment]
> Again coming from my Rails background, the common way to do this would be a position attribute on the note field. Which I'll admit, makes reordering perhaps slightly more complex than using your approach, since you'd have to update potentially all notes in a given lane when one of them is dragged from the bottom to the top.

Yeah. There's always some tradeoff. I can see position working. My primary fear is indeed ordering related complexity.

> I might be mistaken in thinking this, but I believe the parent_id approach is a more standard RDBMS approach. It seems less error-prone to me, even though one ends up needing this position column on the child elements.

We could try to craft a `parent_id` based solution just for reference if nothing else. I'm particularly interested in seeing what it does to the ordering logic. Beyond ordering within a lane itself, we have to deal with moves from lane to lane. For example this operation will cause a cascade or updates over all notes that are after the target. Same goes for originating lane.

I recall we maintain bi-directional linking in [cerebral-demo](https://github.com/survivejs/cerebral-demo). [mobservable-demo](https://github.com/survivejs/mobservable-demo) goes through pure references! There are many ways to approach this.

One way to "solve" it would be to discuss these alternatives in the book itself in more detail. There's some discussion already but going deeper might not hurt.

> That sounds cool! How long do you think it would take? I'm in GMT-0400, which doesn't seem too different from Suomi. My mornings are your afternoons. Maybe Monday for an hour? I've never used Twitch; I usually use G+ Hangouts.

I don't mind dedicating an hour or two myself. I did a Twitch session with a reader earlier and learned a lot as a result.

G+ hangout would work for me. You can probably find me easily there. I'll try to remember to be around.

**Comment by bebraw** [comment]
Probably safe to close now. I added reasoning for the current solution to the introduction of the chapter. There are so many ways to approach design.
