### ISSUE TITLE
02_developing_with_webpack.md ambigous sentence 

### ISSUE THREAD

**Issue by omidfi** [survivejs/webpack_react#270]
It seems like something is wrong with this sentence: 

This approach is that it allows you to see all relevant configuration at one glance.

**Comment by bebraw** [comment]
Good point. Should be `This approach allows you to see all relevant configuration at one glance.`. I'll fix this for the next version. Thanks!

**Comment by bebraw** [comment]
By the looks of it I've fixed this at the dev branch already. I did some rework there so the sentence likely went away altogether.
