### ISSUE TITLE
03_webpack_and_react / ENV babel ENV ambiguity (dev branch)

### ISSUE THREAD

**Issue by omidfi** [survivejs/webpack_react#271]
Hi,
On Dev branch in configuring environmental variables for babel, this line of code: 

  process.env.BABEL_ENV = process.env.npm_lifecycle_event;

Seems to be a bit unclear. Needs a bit of tinkering to get where it belongs. Can't we just mention where it should be applied?

**Comment by bebraw** [comment]
Thanks. I simplified that portion (didn't lose anything of value). It should be clearer now.

I also changed the recommendation from `stage` config to `optional`. This way you know better what features are used within the code base and avoid trouble later on as the language develops.
