### ISSUE TITLE
ch3 - what is package i used for? in package.json

### ISSUE THREAD

**Issue by omidfi** [survivejs/webpack_react#272]
in package.json [here](https://github.com/survivejs/webpack_react/blob/dev/project_source/03_webpack_and_react/kanban_app/package.json) there is a line for npm package called i, at version 0.3.3. However it's not mentioned in the book so far. 

And also generally, would that be good to add  comments  to package.json?

**Comment by bebraw** [comment]
Thanks! Fixed. I must have hit `npm i i` at some point...

> And also generally, would that be good to add comments to package.json?

The problem is that there's no standard way to add comments to JSON. If it was, I would definitely do it.
