### ISSUE TITLE
chapter 3, HMR not working

### ISSUE THREAD

**Issue by omidfi** [survivejs/webpack_react#273]
Updating modules on the page is exciting, but I can't get it working, it just falls back to the whole page reload. Logging this error messages in the console: 

```bash
[HMR] Cannot apply update. Need to do a full reload!
dev-server.js?b7b7:19 
[HMR] Error: Aborted because 223 is not accepted
    at hotApply (http://localhost:8080/bundle.js:356:31)
    at hotUpdateDownloaded (http://localhost:8080/bundle.js:269:13)
    at hotAddUpdateChunk (http://localhost:8080/bundle.js:249:13)
    at webpackHotUpdateCallback (http://localhost:8080/bundle.js:5:12)
    at http://localhost:8080/0.07644271ee71915e9b8a.hot-update.js:1:1
Navigated to http://localhost:8080/
```

I tried to solve it reading Webpack docs, and following some Stackoverflow posts. It's probably not important, and not related to the book, I'm just posting this so that you know.

**Comment by bebraw** [comment]
Can you push your project at GitHub so I can have a look? Which OS are you using?

This might easily have something to do with React 0.14 as react-transform doesn't have an official support for that yet but we'll see.

**Comment by omidfi** [comment]
Yes here it is: 
https://github.com/omidfi/kanban_app/commit/a047aa9d9f2fea72f0208cd8ab1a826aab31c0d4

Ubuntu 14.04

**Comment by bebraw** [comment]
Got it. The problem is that

```javascript
import React from 'react';
import Note from './Note.jsx';

export default () => {
  return <Note />;
}
```

isn't supported by *react-transform* yet.

Note that I went back to the old, class based form today and that's the one I'll be using in the next release until *react-transform* is fixed.

**Comment by omidfi** [comment]
Thank you :+1:

**Comment by phaistonian** [comment]
@bebraw hey :)

Curius as how to figured out what the issue is.

I am (still) strugglng with similar "not accepted" issues and I am unable to find a starting point to fix this.

**Comment by bebraw** [comment]
@phaistonian Can you set up a simplified example for me to study? Please note that you'll need Babel 5 for it to work. Babel 6 isn't supported yet.

**Comment by phaistonian** [comment]
@bebraw oh I am on babel 6.

How to revert back to 5

(I could try that and take it from there)

**Comment by bebraw** [comment]
@phaistonian You'll have to install 5.x versions explicitly. I.e. `npm i babel-loader@5.x`. I think you'll need to revert your configuration to the older form (drop presets etc.). I know it's bit of a work.

An alternative would be to solve it on Webpack side for now. Simply configure [react-hot-loader](https://github.com/gaearon/react-hot-loader). I cannot guarantee it will work with Babel 6 but it might be worth a go given it's probably pretty fast to test.

**Comment by phaistonian** [comment]
Reverted to 5.x, no luck.

`rm -rf node_modules` and `npm install` again, no luck.

I wish there was a way to figure out at least where to look for / at.

As for the example, it's a huge project (hunderds of files) so I am not sure how to ..simplify this :)

**Comment by bebraw** [comment]
@phaistonian I have a working setup at the kanban app. Perhaps there's some way for you to simplify the project so you can understand what breaks it. This would allow you to verify the basic setup at least.

**Comment by phaistonian** [comment]
The config is almost identical to yours.

Thing is, HMR is working one week, and breaks the next one.

It's kind  of hit and miss thing.

Again: I don't get why there's not way to actually figure out what breaks it :(

**Comment by bebraw** [comment]
@phaistonian Can you put your Webpack config and `.babelrc` to a gist? There are a couple of subtle things that are easy to miss.

**Comment by phaistonian** [comment]
Sure :)

[Here](https://gist.github.com/phaistonian/dabee53dc3aa608fb69c)'s the webpack config file.

No `.babelrc` since I am passing the arguments directly in webpack config.

**Comment by bebraw** [comment]
@phaistonian Pretty much the only difference I can see is that I'm using [inline mode](https://webpack.github.io/docs/webpack-dev-server.html#inline-mode) with the dev server. Maybe hot loader simply doesn't work with Babel 6...

**Comment by phaistonian** [comment]
I 'd bet it was working yesterday on my laptop (also on babel 6).

Oh well

Thank you, again :)

**Comment by phaistonian** [comment]
@bebraw Updated to babel 6 (took me a while).

Smoother, but I still don't get HMR on styles (removed react-hot-loader until it's supported).

**Comment by phaistonian** [comment]
@bebraw Well, I did make it work by switching from webpack-dev-server (approach) to using webpack-hot-middleware.

Took me a while to make the changes but:

* things seem faster now
* hot reload works like a charm
