### ISSUE TITLE
ch4 debugger example could be more elaborated

### ISSUE THREAD

**Issue by omidfi** [survivejs/webpack_react#274]
I tried putting the debugger in different places in the jsx file, but it didn't invoke a breakpoint in chrome. 

Could we add an example? Or explain more?

**Comment by bebraw** [comment]
I can add a little code example. Here's good reference btw: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/debugger .

**Comment by omidfi** [comment]
Yeah I've used it in plain JavaScript, but in JSX it seems to be different or I'm missing something.

**Comment by bebraw** [comment]
@omidfi Note that it cannot used *within* JSX I think. I recall using the statement at method level, though. Probably need to have another look. Can you paste some sample code to show how you are using it?

**Comment by omidfi** [comment]
Exactly inside my JSX, I started to move it basically up and down the whole files. As in the course of the book reader is editing this file when debugger is mentioned, to me it makes sense to apply it there just for the sake of curiosity:

```javascript
import uuid from 'node-uuid';
import React from 'react';
import Note from './Note.jsx';

const notes = [
  {
    id: uuid.v4(),
    task: 'Learn Webpack'
  },
  {
    id: uuid.v4(),
    task: 'Learn React!'
  },
  {
    id: uuid.v4(),
    task: 'Do laundry'
  }
];

export default class App extends React.Component {
  debugger;
  render(){
    return (
      <div>
        <ul>
          {notes.map(this.renderNote)}
        </ul>
      </div>
    );
  }
  renderNote(note){
    return(
      <li key={`note${note.id}`}>
        <Note task={note.task} />
      </li>
    );
  }
}
```

**Comment by bebraw** [comment]
`debugger;` needs to be within a method. Otherwise there's no way it could get triggered. It is the same as if you added a break point there manually I.e.

```javascript
render(){
  debugger;
  ...
}
```

should work.

**Comment by omidfi** [comment]
I'm sure I tried it first in there, but didn't work. Now it works. Thanks for inspecting!
