### ISSUE TITLE
http://localhost.com:8080/webpack-dev-server/bundle fails

### ISSUE THREAD

**Issue by SteveALee** [survivejs/webpack_react#278]
In [Chapter 2 Developing with Webpack](https://github.com/survivejs/webpack_react/blob/master/manuscript/02_developing_with_webpack.md) it suggests "Or we can run the application from localhost:8080/webpack-dev-server/bundle instead of root." but for me this just times out.

**Comment by bebraw** [comment]
Does [the source version of the chapter](https://github.com/survivejs/webpack_react/tree/master/project_source/02_developing_with_webpack/kanban_app) time out as well? I couldn't see the issue there myself.

**Comment by SteveALee** [comment]
"npm install" for that fails in the node-gyp for bufferutil.vcxproj. I'll have to figure out why.

**Comment by bebraw** [comment]
Ok, I know things may be more difficult on Windows. I don't have any specific advice to give at this point. Keep me updated. :+1:

**Comment by SteveALee** [comment]
I thought was pesky old MAX_PATH but seems there is more going on. Time to switch to a VM ;)

**Comment by ask10000** [comment]
I too faced problems with bufferutil.vcxproj. I had to repair my Visual Studio Express edition and it worked.

**Comment by SteveALee** [comment]
@ask10000 Thanks. I'll try that. I'm using 2015 community

**Comment by ttamminen** [comment]
I can confirm that the provided source code works on Windows machine, so @SteveALee and @ask10000 there is still hope! 

Building addons on Windows machine can be sometimes pain in a butt. I wrote [an article](http://www.triplet.fi/blog/set-up-working-node-addons-node-gyp-environment-on-windows/) how to set up working dev environment on Windows machine, I hope it helps.

**Comment by SteveALee** [comment]
@tramlines thanks. I installed the VS update 2 and repaired but have not retrided the install. You article us great as it confirms I was doing it right. 

Fyi @Microsoft have started a resource at https://github.com/Microsoft/nodejs-guidelines and I'm sure they would appreciate a PR for the native modules section.

**Comment by SteveALee** [comment]
@ttamminen sorry, auto complete messed up your Id above

**Comment by bebraw** [comment]
Time to close this one.
