### ISSUE TITLE
Implementing Drag and Drop -

### ISSUE THREAD

**Issue by nngrey** [survivejs/webpack_react#279]
I have been working through this tutorial for a couple weeks now. It is excellent. One of the best online learning experiences I have had. I'll try to provide more useful feedback when I am done, but I wanted to share one small complaint. Today, when I started the drag and drop section, I noticed large arrows on each side of the screen, overlapping the text. Visually, I find them a little annoying, but perhaps that is because they are new (I think they are new?). More importantly, they interfere with my ability to cut and past code. I am using a 13 inch MacBook Pro with an up to date version of Chrome.  

![screenshot 2015-11-03 18 58 31](https://cloud.githubusercontent.com/assets/4781197/10928420/166d6898-825d-11e5-9140-26c86dcf0501.png)

**Comment by bebraw** [comment]
It's a new feature I'm experimenting with, yup. I disabled the arrows on low resolutions for now so they don't get in the way. There is probably a neater way to deal with next/previous chapter navigation. Now it's at the end of the page at least.

Thanks for the report!
