### ISSUE TITLE
Setting the Note in edit mode on add

### ISSUE THREAD

**Issue by ask10000** [survivejs/webpack_react#282]
Wonderful example of React+Webpack. Though, I got to say that thinking in React will take some time!

I am trying to understand how should I set up the Note in editable mode as soon as user clicks the add button. Currently when the add button is clicked, a new Note or Editable entry is created and saved - with "New Task" name. I would like to render it in editable mode as soon as a new Note is created. What would be the right place to achieve this? I thought it should go in Editable.js, but not sure if this is the right place to achieve.

**Comment by bebraw** [comment]
The problem is that in the current implementation `Editable` maintains its `editing` state and we don't have enough control over it to achieve what you want.

A natural way to approach the problem would be to extract the state and push control over it to a higher level. You could, for instance, define a callback based API and replace those `setState` bits with them. I think we need just `onBeginEdit` and `editing` prop to pass the desired state. We might also want to rename `onEdit` as `onFinishEdit` to communicate the intent better.

I have to think about including this change in the book. At least there could be a mention about how to deal within something like this.

**Comment by ask10000** [comment]
I was on the line of thought that I can simply set `editing: true` when creating the new task in `Lane.js` would help.
```
  addNote(laneId) {
    NoteActions.create({task: 'New task', editing:true});
    LaneActions.attachToLane({laneId});
  }
```
But it seems that although the `task: 'New task'` prop gets passed into state, `editing: true` doesn't go to the state. Not sure what I am missing.

**Comment by bebraw** [comment]
`NoteActions.create({task: 'New task', editing:true});` is one option, yup.

> But it seems that although the task: 'New task' prop gets passed into state, editing: true doesn't go to the state. Not sure what I am missing.

How did you change `Editable`? You need to resolve the state issue there somehow for the design to make sense.

**Comment by ask10000** [comment]
Currently in the example, the constructor of `Editable` sets the `editing` prop as `false`. I was thinking that following change would help.
```javascript
    this.state = {
        //something like this would work???
        editing: props.editing
    };
```

**Comment by bebraw** [comment]
Please note that the constructor will get called only when the component gets instantiated.

If you want to modify the component state based when a prop changes, [componentWillReceiveProps](https://facebook.github.io/react/docs/component-specs.html#updating-componentwillreceiveprops) would be the place to do that.

**Comment by bebraw** [comment]
@ask10000 Any luck? I could write a blog post showing one approach. The more I think about it, the more it makes sense to extract the state out of the component. That gives the maximum amount of control.

**Comment by ask10000** [comment]
Hi @bebraw 
No, I haven't been able to crack this with the approach you mentioned. Will be great if you can add something on this line in the guide or a blog post, Thanks a bunch!

**Comment by bebraw** [comment]
@ask10000 Ok, no worries. I'll get to it at some point (leaving this issue open till I do that).

**Comment by bebraw** [comment]
@ask10000 I extracted `editable` state from `Editable`. You have a lot more control over its behavior now. This pushes some of the logic up, but it was the right thing to do. Thanks!
