### ISSUE TITLE
Implementing Drag and Drop - list example

### ISSUE THREAD

**Issue by PetaPetaPeta** [survivejs/webpack_react#286]
In the first paragraph of the section `Adding Action and Store Method for Moving` you have the following text:

> The logic of drag and drop is quite simple. Suppose we have a list A, B, C. In case we move A below C we should end up with B, C, A. In case we have another list, say D, E, F, and move A to the beginning of it, we should end up with B, C and A, D, E, F.

I think it could be made more clear that [A, B, C] is a lane and that each letter represents a note.

**Comment by bebraw** [comment]
Yeah, that's a fair point. I'll get this fixed. :+1:

**Comment by bebraw** [comment]
Fixed.
