### ISSUE TITLE
SurviveJS - Webpack and React v1.9.10 -

### ISSUE THREAD

**Issue by ngault** [survivejs/webpack_react#287]
Great to see CSS Modules and, especially, Relay covered.  I'd like to see Relay built out further.

Why not make Redux the Flux implementation, as opposed to Alt?  I honestly believe you're sales by featuring Alt.  A couple of friends that I referred SurviveJS to found the choice of Alt strange.

**Comment by ngault** [comment]
This wasn't intended as an  "Issue", sorry.  But I wanted to make the point somewhere...

**Comment by ngault** [comment]
*

**Comment by bebraw** [comment]
No worries. Thanks for the comment!

About Redux, it didn't exist when I started out so Alt came into the book through legacy. Note that I have a [Redux version](https://github.com/survivejs/redux-demo) of the book example. It's not too far from Alt interestingly!

Lately I've been thinking about porting those Alt chapters to it. I feel that could be something worthwhile especially given how popular Redux is these days.

There's a lot of high quality material about Redux out there but perhaps this would be a worth doing anyway. The tweaks needed aren't that difficult and it would give me a perfect excuse to reward my Leanpub readers. ;)

**Comment by ngault** [comment]
It's great to hear from the author.  Thanks for a superb piece of work.

I do feel your book could be a much greater success if you took a slight turn, as follows: rather than making a static "edition" (as found in print publishing), keep it a "living", evolving ebook, continually updated with the best/latest React-related technologies...and linked to code.

Unlike AngularJS, which is a complete framework, React on its own requires several other pieces, notably Flux and, likely, something like Relay.  My point is that any React book that omits these complementary pieces will be much less useful.  Yours is the only React book that meets the challenge, but you'll need to update it frequently as  these complementary pieces (including, in the future, CSS Modules, Redux, Relay) are still nascent.  

Prediction: these technologies will coalesce into a "stack" within 12 months, analogous to MEAN in the Angular world.  Yours should be the first book, and it should be combined with a repo ...perhaps the future Antwar?  Witness the redux-starter repo by erikras.  A living ebook about your own version of this would, IMHO, exceed in attention anything in the MEAN world...

Cheers
Nick Gault

**Comment by bebraw** [comment]
> I do feel your book could be a much greater success if you took a slight turn, as follows: rather than making a static "edition" (as found in print publishing), keep it a "living", evolving ebook, continually updated with the best/latest React-related technologies...and linked to code.

Yeah, I've been going against the mainstream in this effort. It truly has been a living effort so far. There is no other way with something like this given how fast things change.

I will try to make "static" milestones (paper book) to support the effort but the plan is to keep the book living. Otherwise it just gets old very fast.

> Unlike AngularJS, which is a complete framework, React on its own requires several other pieces, notably Flux and, likely, something like Relay.  My point is that any React book that omits these complementary pieces will be much less useful.  Yours is the only React book that meets the challenge, but you'll need to update it frequently as  these complementary pieces (including, in the future, CSS Modules, Redux, Relay) are still nascent.

:+1: That's the benefit of using a framework. In library approach you have to bring a lot of opinions of your own to the table. Both approaches have their merits.

> Prediction: these technologies will coalesce into a "stack" within 12 months, analogous to MEAN in the Angular world.  Yours should be the first book, and it should be combined with a repo ...perhaps the future Antwar?  Witness the redux-starter repo by erikras.  A living ebook about your own version of this would, IMHO, exceed in attention anything in the MEAN world...

Yeah, i expect React and associated technology will gain momentum. There are early signs of that visible. I agree keeping it living is a very worthwhile goal. As long as I have stamina to develop the book and surrounding material, everyone benefits. :)
