### ISSUE TITLE
Module parse fail:  Unexpected token <

### ISSUE THREAD

**Issue by ammark47** [survivejs/webpack_react#291]
I've added the files I think are relevant. Let me know if you need something else
https://gist.github.com/ammark47/523e679d63b78b444c29

ERROR in ./app/js/RRouter.jsx
Module parse failed: /Users/AmmarKarim/Desktop/StreetsAhead/Homepage/app/js/RRouter.jsx Line 16: Unexpected token <
You may need an appropriate loader to handle this file type.

**Comment by bebraw** [comment]
I think you are missing the jsx loader. Set up a rule for it at common. Basic idea:

```js
      {
        test: /\.jsx?$/,
        loaders: ['babel'],
        include: PATHS.app
      }
```

This is a good case to cover at troubleshooting. Thanks for the idea.

**Comment by ammark47** [comment]
Thanks. It almost worked for RRouter.jsx but for some reason, I'm running into the same problem when I'm importing a component.

ERROR in ./app/js/HomeView.jsx
Module parse failed: /Users/AmmarKarim/Desktop/StreetsAhead/Homepage/app/js/HomeView.jsx Line 14: Unexpected token <
You may need an appropriate loader to handle this file type.
| 	render(){
| 		return (
| 				< div>
| 					< BigPic />
| 					< Major />
 @ ./app/js/RRouter.jsx 11:15-36

and 

ERROR in ./app/js/app.jsx
Module parse failed: /Users/AmmarKarim/Desktop/StreetsAhead/Homepage/app/js/app.jsx Line 15: Unexpected token <
You may need an appropriate loader to handle this file type.
| 	render(){
| 		return ( 
| 				< div>
| 					< Navs />
| 					< RouteHandler/>
 @ ./app/js/RRouter.jsx 10:10-26

**Comment by bebraw** [comment]
@ammark47 Ok, no worries. Can you push your project to GitHub so I can have a better look?

**Comment by ammark47** [comment]
No problem. As soon as I get the chance :)
