### ISSUE TITLE
Chapter 4.9 removing notes missing line

### ISSUE THREAD

**Issue by kocur4d** [survivejs/webpack_react#293]
On Page 58 when you introduce `renderTask` and `renderDelete` functions inside of `class Note` we still need to update the `render` function to call `renderTask` instead of `renderNote`:

was:

 `{ editing ? this.renderEdit() : this.renderNote() }` 

to:

 `{ editing ? this.renderEdit() : this.renderTask() }`

or I missed something:)

**Comment by bebraw** [comment]
Correct.

I think I'll just rename `renderTask` simply as `renderNote` to keep it neat. What do you think?

I could also drop the ternary and do it like this:

```javascript
render() {
  if(this.state.editing) {
    return this.renderEdit();
  }

  this.renderNote();
}
```

That reads well to me.

**Comment by kocur4d** [comment]
Yes renaming it to `renderTask` from a beginning is a best option otherwise you will have to show a lot of unnecessary changes.

As of `render` it self I like ternary operators but your suggestion looks good as well.

What is you opinion on using `Array.filter()` inside of `noteEdit` and `noteDelete` instead of `findNote`?

Your delete:

```javascript
deleteNote = (id) => {
  const notes = this.state.notes;
  const noteIndex = this.findNote(id);
  if(noteIndex < 0) { return; }
  this.setState({
    notes: notes.slice(0, noteIndex).concat(notes.slice(noteIndex + 1))
  }); 
}
```
Using `filter`

```javascript
deleteNote = (id) => { 
  const { notes } = this.state 
  this.setState({
    notes: notes.filter((note) => note.id !== id) 
  }) 
}
```

I am not to sure about performance but it looks a bit cleaner to me;)

**Comment by bebraw** [comment]
> Yes renaming it to renderTask from a beginning is a best option otherwise you will have to show a lot of unnecessary changes.

Good point. I have to give a proper beauty pass at these chapters soon. :+1:

About delete, I've actually simplified it at `dev` version. Here's what it looks like now:

```
deleteNote = (id) => {
  this.setState({
    notes: this.state.notes.filter(note => note.id !== id)
  });
}
```

That's pretty much what you were suggesting. :)

**Comment by kocur4d** [comment]
Nice! I very like your book and your commitment to make it better is great! 

Speak to you soon. Have a good one mate!
