### ISSUE TITLE
ERROR in Entry module not found: Error: Cannot resolve 'file' or 'directory'

### ISSUE THREAD

**Issue by matt212** [survivejs/webpack_react#295]
Hi, 
iam refereing line no 19
of below file 
https://github.com/survivejs/webpack_react/blob/master/project_source/08_building_kanban/kanban_app/webpack.config.js
i am  getting below error 
ERROR in Entry module not found: Error: Cannot resolve 'file' or 'directory'
my code is 
var path = require('path');

module.exports = {
  
  entry: path.join(__dirname, 'assets'),
  output: {
    filename: 'bundle.js'       
  }

   
};

**Comment by bebraw** [comment]
`entry: PATHS.app` points at a directory which has an `index.js(x)`. Normally it's not possible to pass a directory there.

It's better to continue at https://github.com/webpack/webpack/issues/1732 . I'll write an expanded answer there.
