### ISSUE TITLE
alt installation as @late leads to ERROR❗️

### ISSUE THREAD

**Issue by KSMorozov** [survivejs/webpack_react#296]
## Chapter: Developing Kanban Application React and Flux
> ### recommended installation: 
```
npm i alt --save
```

### webpack build leads to 
> ERROR in ./app/libs/persist.js
Module not found: Error: Cannot resolve module 'alt/utils/makeFinalStore' in /app/libs
 @ ./app/libs/persist.js 9:30-65

## ✅Solved by installing alt as 
```
npm i alt@^0.17.4 -S
```
@bebraw please update, and while i am at it ty for free React learning resource 💯

**Comment by bebraw** [comment]
Hi,

I have fixed it in dev. See
https://github.com/survivejs/webpack_react/commit/b8877524f2ee0b1593c15c1e3943915865600223
 .

I'll release a fixed version tomorrow.

**Comment by KSMorozov** [comment]
ty for the response, once a again great work much appreciated, have a good day.👍

**Comment by bebraw** [comment]
Safe to close now that a new release is out there.
