### ISSUE TITLE
Developing with Webpack -

### ISSUE THREAD

**Issue by WhatFreshHellIsThis** [survivejs/webpack_react#297]
Section "Setting Up webpack-dev-server"

I'm following along with the tutorial and getting increasingly lost as it's not clear what needs to be typed, what will be generated and what is simply an example.

In this section it introduces what looks to be an entirely new webpack.config.js file from the prior one we just made but it also has several ellipses ... in it so perhaps it's indicating to add new stuff to the existing file but then it also has the same const defined so????

I'll hit up the repo and try to figure out what was meant but the areas where files are created and we are to make entries in them needs to be a *whole* lot clearer on what we type and where and most importantly WHY which seems to be missing from this starting out section and I hope is just glossed over because it's not relevant to the main point of the tutorial.

**Comment by bebraw** [comment]
Yeah, that's a valid point. Maybe the cleanest way would be just to skip the ellipsis in this case? It's 20 extra lines or so, but at least it would be unambiguous.

**Comment by WhatFreshHellIsThis** [comment]
Traditionally in these circumstances you would show the file with the new text changes highlighted so it's clear what stays what goes and what is inserted since it's a small file.  If it were huge then you would use ellipses but would include a fragment of the original in muted font so we could see where exactly to insert the new text.

Also that exact section  where you say:

"Hit npm start and surf to localhost:8080. You should see something familiar there. Try modifying app/component.js while the server is running and see what happens. Quite neat, huh?"

I just get a bunch of errors at this point and now I guess I'm going to self learn what can go wrong trying to set up this stuff. :)

**Comment by WhatFreshHellIsThis** [comment]
Skipping the ellipses and leaving as is would clearly be worse, maybe you are too close to this material to view it as a beginner.

**Comment by bebraw** [comment]
> Skipping the ellipses and leaving as is would clearly be worse, maybe you are too close to this material to view it as a beginner.

Absolutely.

My formatting options are somewhat limited. Options:

1. [Marking lines as deleted or added](https://leanpub.com/help/manual#leanpub-auto-marking-lines-as-deleted-or-added-to-a-code-block)
2. `diff` - The problem with this is that it loses formatting.
3. Ellipsis

Most likely adopting `1.` would be the ticket. I have heard it can be problematic in certain PDF readers, though, but this is something that needs to be fixed.

**Comment by bebraw** [comment]
@WhatFreshHellIsThis Would this work for you?

![screenshot 2015-12-11 20 40 56](https://cloud.githubusercontent.com/assets/166921/11752310/8b27ba1e-a047-11e5-810c-205c2afc3427.png)

**Comment by WhatFreshHellIsThis** [comment]
It's better but not ideal as it does not indicate in all cases even a snippet of the original text immediately before and immediately after the stuff we are to type in all cases which is what is required to know clearly where stuff is meant to go.

I think you intend the ellipses to be self evident, however they are not without a snippet of the text that goes with them.

**Comment by bebraw** [comment]
> I think you intend the ellipses to be self evident, however they are not without a snippet of the text that goes with them.

Ok. Maybe it makes sense to set up some rules for the usage. I can, for instance, always spell out method signatures. Ellipsis would go inside those if they haven't changed.

In this particular case I would add

```javascript
module.exports = {
  entry: PATHS.app,
  output: {
    path: PATHS.build,
    filename: 'bundle.js'
  },
  ...
```

to the beginning to make it unambiguous. You can now see all the fields that are needed, the new parts will get bolded. We'll end up just with that import and `plugins` ellipses.

It's important to get some conventions in place so this can be dealt with correctly.

**Comment by bebraw** [comment]
@WhatFreshHellIsThis I got a little idea we could try. Perhaps we can solve the problem for this chapter structurally? By changing the ordering a bit, we just might make it more approachable. How would a structure like this sound?

1. Explain how to structure your Webpack configuration and add initial "slots" for *build* and *dev* configuration. We'll fill those slots next.
2. Explain how to set up a basic *build* configuration. I would mention here that we will expand it somewhat in the chapter dedicated to the topic.
3. Explain how to set up a basic *dev* configuration.

The end result would be more or less the same as now. You would get a minimal *build* configuration, though, but that's not bad. The biggest benefit is that the code changes would become far easier to make. I know there has been some confusion over the current setup so this might clear that up.

**Comment by WhatFreshHellIsThis** [comment]
Yes that might help.  One thing I felt as I initially started that section is that it rushed too quickly through this area and that in fact it's actually a very important part of the whole tutorial since the first teaching goal listed is "Set up a Webpack based development and production environment. ".

Perhaps it needs more words or less concepts in that first chunk and spread out more?

**Comment by bebraw** [comment]
Yeah, this was literally one of the first chapters I wrote and since then it has grown organically. I'll prepare an improved version for you to look at.

I deferred actual build related aspects to a chapter of its own as it gets quite complex fast. That said, we can spend more time on getting things set up here.

Thanks for your commentary. This is very helpful.

**Comment by bebraw** [comment]
@WhatFreshHellIsThis I streamlined the chapter. The structure feels more natural to me now. It would be awesome if you could check out the [dev version](https://github.com/survivejs/webpack_react/blob/dev/manuscript/02_developing_with_webpack.md) and let me know what you think.

**Comment by bebraw** [comment]
@WhatFreshHellIsThis Hey, do you want to have a look at the current version? I pushed out a [new version](http://survivejs.com/blog/survivejs200-rc1/).

**Comment by bebraw** [comment]
Closing. Feel free to open again if you have time to check out at a later time.
