### ISSUE TITLE
typo in code examples

### ISSUE THREAD

**Issue by KSMorozov** [survivejs/webpack_react#298]
##### @bebraw Typo in code line 28
*webpack_react/project_source/***06_from_notes_to_kanban***/kanban_app/app/stores/***LaneStore.js**
https://github.com/survivejs/webpack_react/blob/dev/project_source/06_from_notes_to_kanban/kanban_app/app/stores/LaneStore.js#L28

```
update({id, name}) {
    const lanes = this.lanes.map((lane) => {
      if(lane.id === id) {
        lane.name = name;
      }

      return note;
    });

    this.setState({lanes});
}
```

***fix:*** replace *note* with **lane**. ✅ 

```
update({id, name}) {
    const lanes = this.lanes.map((lane) => {
      if(lane.id === id) {
        lane.name = name;
      }

      return lane;
    });

    this.setState({lanes});
}
```
please update.

**Comment by KSMorozov** [comment]
@bebraw btw should i just PR next time tho?
i just don't know whats your opinion on contributions?

**Comment by bebraw** [comment]
Contributions are fine. I'm actually just fixing this so no need in this case. :+1:

**Comment by KSMorozov** [comment]
cool cheers.

**Comment by bebraw** [comment]
Deployed. Thanks again!
