### ISSUE TITLE
Isomorphism Chapter

### ISSUE THREAD

**Issue by bebraw** [survivejs/webpack_react#30]
The Node example is good but it would be a good idea to cover perhaps some other options.

**Comment by justjacksonn** [comment]
Thank you for adding this. Yes, I would love to see a bit more on the difference between the code you would write for SSR vs the client side code. For example, to me it seems like I would have to use the renderToString() and duplicate the class/code for a client side version. I know this is not the case, but it's unclear to me how we do this. In particular, does every single "bookmarkable" page need to be SSR AND client side capable? Or is it primarily just the opening application page?

**Comment by bebraw** [comment]
@christianalfoni If you have time, can you comment on this?

**Comment by christianalfoni** [comment]
Hi guys,

There are many ways to solve this. What I have primarily been focusing on is to make the components so pure that when the server requires the App top component it just brings in the sub components and maybe some mixin that extracts state from a store passed on the context when rendering the app to a string.

This gives some background on that: http://www.christianalfoni.com/articles/2015_03_01_True-isomorphic-apps-with-React-and-Baobab

Again, there is no "one specific" way, but I think a primary focus should be "how to inject stores" into the app and "pure components".

Hope this was of help.

**Comment by bebraw** [comment]
I'm going to close this as there's now a little snippet about [isomorphic rendering](http://survivejs.com/webpack_react/building_kanban/#isomorphic-rendering) at the book. I know it's not perfect but at least it should put the readers on the right track and illustrate the idea in a compact way.
