### ISSUE TITLE
Bug in Notes.jsx

### ISSUE THREAD

**Issue by og1** [survivejs/webpack_react#300]
Hi, in Notes.jsx there is a problem. First off, the code in GitHub differs from the example in the book. renderNote(note)  should be  renderNote = (note) => {. Secondly there is an error on line 15: "Cannot read property 'id' of undefined" which prevents the App from working. 

And finally some webpack suggestions when hitting npm run build:
The unused option is deprecated. Please use options.discardUnused instead.
The urls option is deprecated. Please use options.normalizeUrl instead.
The idents option is deprecated. Please use options.mergeIdents instead.
The idents option is deprecated. Please use options.reduceIdents instead.

Hope this helps.

**Comment by bebraw** [comment]
Thanks. I missed a spot at that `renderNote`. It should be `renderNote(note) {`.

`return <ul className="notes">{notes.map(this.renderNote, this)}</ul>;` binds the method to the right context so I opted for this instead of `renderNote = (note) => {`. Either should work. The benefit of binding at `map` is that you get something that works with hot loading.

> Secondly there is an error on line 15: "Cannot read property 'id' of undefined" which prevents the App from working.

Can you provide more information on this? Would it be possible for you to push your project to GitHub so I can have a better look? I can see this could happen if `note` is `undefined` or doesn't contain an `id`.

> And finally some webpack suggestions when hitting npm run build:
> ...

This has to do with [css-loader](https://github.com/webpack/css-loader/issues/126). I'll update the source dependencies to get rid of the warnings. Thanks.

**Comment by bebraw** [comment]
I fixed the *css-loader* glitch.

Let me know how you want to proceed with that `renderNote` one. Now that I think of it, I could revert it back to the old form.

That `"Cannot read property 'id' of undefined"` is also very curious. Maybe some data validation would be in order.

**Comment by og1** [comment]
Hi Juno,

I did no modifications other than switch from port 8080 to 3000. I am running on
a Windows server 2008. I will try to provide you some more info tomorrow.


Omar

Sent using CloudMagic Email
[https://cloudmagic.com/k/d/mailapp?ct=pa&cv=8.0.67&pv=5.1.1&source=email_footer_2] On za, dec. 12, 2015 at 4:06 PM, Juho Vepsäläinen < notifications@github.com [notifications@github.com] > wrote:
Thanks. I missed a spot at that renderNote . It should be renderNote(note) { .

return <ul className="notes">{notes.map(this.renderNote, this)}</ul>; binds the method to the right context so I opted for this instead of renderNote = (note) => { . Either should work. The benefit of binding at map is that you get something that works with hot loading.

Secondly there is an error on line 15: "Cannot read property 'id' of undefined"
which prevents the App from working.

Can you provide more information on this? Would it be possible for you to push
your project to GitHub so I can have a better look? I can see this could happen
if note is undefined or doesn't contain an id .

And finally some webpack suggestions when hitting npm run build:
...

This has to do with css-loader [https://github.com/webpack/css-loader/issues/126] . I'll update the source dependencies to get rid of the warnings. Thanks.

—
Reply to this email directly or view it on GitHub
[https://github.com/survivejs/webpack_react/issues/300#issuecomment-164160148] .[https://github.com/notifications/beacon/AITWZXMZ0OCgzERMw7yFKsUrbEQhYxnKks5pPC97gaJpZM4G0H7q.gif]

**Comment by IngenieroLata** [comment]
Once I replace the new code for the detachFromLane it just broked. Looks like  `"Cannot read property 'id' of undefined"` is because the detachFromLane method is not deleting the reference from the `lane.notes`.

**Comment by IngenieroLata** [comment]
I found an error in the detachFromLane method, but no sure if the book changed the way is referencing the notes into lanes. That method is filtering by `note.id !== removeIndex` but the lanes have an array of notes id, should be filtering by `note !== noteId` since removeIndex is validating the existance of the id inside the lane

```
...
if(removeIndex !== -1) {
  lane.notes = notes.filter((note) => note !== noteId);
} else {
  console.warn('Failed to remove note from a lane as it didn\'t exist', lanes);
}
...
```

**Comment by bebraw** [comment]
Thanks guys! Fixed.

**Comment by og1** [comment]
Eh, sorry. I still get the error. However, only when I npm start it. If I npm
run build it and open index.html from the build directory then it works. I
suspect the problem may be in the attach to Lane method.



Sent using CloudMagic Email
[https://cloudmagic.com/k/d/mailapp?ct=pa&cv=8.0.67&pv=5.1.1&source=email_footer_2] On zo, dec. 13, 2015 at 8:42 AM, Juho Vepsäläinen < notifications@github.com [notifications@github.com] > wrote:
Thanks guys! Fixed.

—
Reply to this email directly or view it on GitHub
[https://github.com/survivejs/webpack_react/issues/300#issuecomment-164235521] .[https://github.com/notifications/beacon/AITWZQvvjQ5ot0vF5DpXIO9I7mNwhtV1ks5pPRjagaJpZM4G0H7q.gif]

**Comment by IngenieroLata** [comment]
Could it be you have to clean the local storage, did you tried it?

**Comment by og1** [comment]
Yes just did, same error



Sent using CloudMagic Email
[https://cloudmagic.com/k/d/mailapp?ct=pa&cv=8.0.67&pv=5.1.1&source=email_footer_2] On zo, dec. 13, 2015 at 12:05 PM, Diego Toro < notifications@github.com [notifications@github.com] > wrote:
Could it be you have to clean the local storage, did you tried it?

—
Reply to this email directly or view it on GitHub
[https://github.com/survivejs/webpack_react/issues/300#issuecomment-164247426] .[https://github.com/notifications/beacon/AITWZfI7a3aWqDpLx-WGxZJ5VZu_LYbzks5pPUh3gaJpZM4G0H7q.gif]

**Comment by og1** [comment]
The problem appears to be in the get (ids) part of the Note Store. When I change
that to the previous version it works!



Sent using CloudMagic Email
[https://cloudmagic.com/k/d/mailapp?ct=pa&cv=8.0.67&pv=5.1.1&source=email_footer_2] On zo, dec. 13, 2015 at 12:05 PM, Diego Toro < notifications@github.com [notifications@github.com] > wrote:
Could it be you have to clean the local storage, did you tried it?

—
Reply to this email directly or view it on GitHub
[https://github.com/survivejs/webpack_react/issues/300#issuecomment-164247426] .[https://github.com/notifications/beacon/AITWZfI7a3aWqDpLx-WGxZJ5VZu_LYbzks5pPUh3gaJpZM4G0H7q.gif]

**Comment by bebraw** [comment]
@og1 Can you upload your project to GitHub? I'll have a good look.

**Comment by og1** [comment]
I could but it is the unmodified version of your latest upload.



Sent using CloudMagic Email
[https://cloudmagic.com/k/d/mailapp?ct=pa&cv=8.0.67&pv=5.1.1&source=email_footer_2] On zo, dec. 13, 2015 at 12:37 PM, Juho Vepsäläinen < notifications@github.com [notifications@github.com] > wrote:
@og1 [https://github.com/og1] Can you upload your project to GitHub? I'll have a good look.

—
Reply to this email directly or view it on GitHub
[https://github.com/survivejs/webpack_react/issues/300#issuecomment-164249094] .[https://github.com/notifications/beacon/AITWZXG_s7ZX0OUWPi3HpjGhAY3_Q9Dtks5pPVANgaJpZM4G0H7q.gif]

**Comment by bebraw** [comment]
@og1 Can you provide me minimal instructions on how to reproduce the error? If I do this, it just works:

1. `cd project_source/06_from_notes_to_kanban/kanban_app`
2. `npm start`
3. Surf to `http://localhost:8080/`
4. Added some lanes/notes + performed edit ops -> no error

I'm missing something here.

**Comment by og1** [comment]
I am sorry, I just found out I was clearing the local storage in the wrong
place. After clearing it in the right place it works as it should.



Sent using CloudMagic Email
[https://cloudmagic.com/k/d/mailapp?ct=pa&cv=8.0.67&pv=5.1.1&source=email_footer_2] On zo, dec. 13, 2015 at 3:06 PM, Juho Vepsäläinen < notifications@github.com [notifications@github.com] > wrote:
@og1 [https://github.com/og1] Can you provide me minimal instructions on how to reproduce the error? If I do
this, it just works:

 1. cd project_source/06_from_notes_to_kanban/kanban_app
 2. npm start
 3. Surf to http://localhost:8080/
 4. Added some lanes/notes + performed edit ops -> no error

I'm missing something here.

—
Reply to this email directly or view it on GitHub
[https://github.com/survivejs/webpack_react/issues/300#issuecomment-164262247] .[https://github.com/notifications/beacon/AITWZU8VXwO5UIhvrv4AUGcGJiDknE1Rks5pPXLRgaJpZM4G0H7q.gif]

**Comment by bebraw** [comment]
No worries. Thanks for confirming. :+1:
