### ISSUE TITLE
"Hit"?

### ISSUE THREAD

**Issue by saschwarz** [survivejs/webpack_react#301]
A very small point. You use the term "Hit" when I believe you mean "Type the following and press enter" as in: "Hit node_modules/.bin/webpack.” 

It is kind of jarring each time I encounter it as you don't explain your usage; I've never heard "hit" used like that. I've heard/used the term "hit" as in: "Hit Google.com to see if your wifi is working". To me "hit" means "type this URL in the browser or use curl to interact with the web server to get a response". You could (rightfully) say my usage of "hit" is just as idiosyncratic!

**Comment by bebraw** [comment]
Yeah, I think I got this idiom from Top Gun. Time to fix. Thanks for pointing it out!

**Comment by bebraw** [comment]
I ended up using *execute* and *trigger*. There are some *hit*s around still, but those had a different context so it made sense to retain them.
