### ISSUE TITLE
Webpack and React -

### ISSUE THREAD

**Issue by lightwave** [survivejs/webpack_react#309]
Hi,

First, I appreciate that you're making part of your book available online for free. I have the following feedback.

Throughout the book, you're spooning the reader a lot of "steps" to follow along without explaining in details what each step does. There are a lot of assumptions. For example, if I know Babel, I wouldn't need all the brief explanation. i.e., the brief explanation isn't explaining anything to the novice. It only adds to the confusion. For example, in the chapter of Webpack and React, "We also need to make Babel aware of HMR. First we should pass target environment to Babel through our Webpack configuration:"

webpack.config.js
...

process.env.BABEL_ENV = TARGET;

var common = {
  ...
};

...

Great, so why do the Babel needs the web pack target? And what the hack is web pack target. It wasn't explained clearly before.

The more I continue to read this book, the more frustrating I get. It keeps mentioning that it'd be explained later when it's relevant. If that's the case, why not just give me the entire files of babel and web pack configuration and then explain in details later in its relevant section in the book? It's a complete waste of time to follow along with the book to set up the configuration files without gaining any understanding of why I'm doing that. If I can get more information and RTFM myself, why should I continue to read the book?

I hope you don't take this the wrong way. I'm just trying to present the point of view of a novice user of Webpack and React. For someone who's already experienced or know "enough" of Webpack and React, they might be able to follow along just fine but this is not very useful for someone who's trying to learn.

**Comment by bebraw** [comment]
I appreciate the honest feedback. I agree the bit you mentioned needs clarification.

Would it be possible for you to outline parts like this you find lacking? I can tackle them for the next release.

Note that I have revamped the structure of [Developing with Webpack](https://github.com/survivejs/webpack_react/blob/dev/manuscript/02_developing_with_webpack.md) at *dev* so it should be a little easier to follow. There's also an upcoming [appendix on language features](https://github.com/survivejs/webpack_react/blob/dev/manuscript/14_language_features.md) used in the book to cover the blind spots in greater detail. I think these might be small steps towards something better. :)

**Comment by bebraw** [comment]
@lightwave I published [a new version](http://survivejs.com/blog/survivejs200-rc1/). There have been significant changes since the report (trying to simplify, make it more approachable). It would be great if you could have a look and let me know what you think!

**Comment by lightwave** [comment]
Thanks Juho. I'll take a look later.

Chris

**Comment by lightwave** [comment]
Hi Juho,

I'm starting to re-read the Webpack chapter. Here is my quick feedback.
Will send you more as I finish reading more.

In the Developing with Webpack chapter, I honestly don't think it has
improve. Let me be more specific. Let's use the following as an example.

We could create *index.html* by hand. Maintaining that could become
troublesome as the project grows, though. html-webpack-plugin
<https://www.npmjs.com/package/html-webpack-plugin> is able to generate an
*index.html* for us and create links to our assets keeping our life simple.
Execute

npm i html-webpack-plugin --save-dev

to install it to the project.

This is a rather common problem as I pointed out before. You introduce a
concept, which is pretty foreign to anyone who's never use webpack before.
I think you need to elaborate on why maintaining the index.html file can be
troublesome. What does the html-webpack-plugin do. Don't introduce a
plugin/concept without giving a more detailed conceptual overview.
html-webpack-plugin is hardly self-explanatory. Sure, it has something to
do with webpack and html. Duh... But, it left me guessing, what else can it
do or supposed to do. Is it just for creating index.html? Automatic
creation of index.html would certainly run into some limitation.  I could
try the command and take a detailed look into the generated index.html but
IMHO that's unnecessary distraction and context switching for the reader.
Perhaps, a more detailed overview of the plugin is needed so that the
reader can choose to look into it in the future.

Another example,

Sometimes, it may make sense to define context: <some absolute path>. After
this, you can write entries relative to the context
<https://webpack.github.io/docs/configuration.html#context> path rather
than using an absolute path for each entry. This is useful especially in
more complicated scenarios.


Why spend the energy and space to briefly introduce something called
context and not just use it? I found this feature to be a good practice
anyway. Way better than path.join to create absolute paths all over the
place.

Peter Hunt has it right. Don't focus on the tooling/bundler until after
learning React.js.

Chris

**Comment by lightwave** [comment]
One more example.

In order to make this work, we'll need to connect the generated bundle
running in-memory to the development server. Webpack uses WebSocket based
communication to achieve this. To keep things simple, we'll let Webpack to
generate the client portion for us through the development server *inline*
 option.

Beyond this we'll need to enable HotModuleReplacementPlugin to make the
setup work. In addition I am going to enable HTML5 History API fallback as
that is convenient default to have especially if you are dealing with
advanced routing. Here's the setup:
It should be "we'll let Webpack generate". Drop the "to" please.

The above paragraphs won't make any sense to a new webpack user/learner. I
hope the goal of the book is to teach. This is creating more questions in
one's head. Making the word "inline" italic doesn't do anything to explain
what inline option is.  I had to dig around in the webpack documentation to
find out that it's an option for the webpack-dev-server plugin. Perhaps
include the explanation from the official documentation. It's just one
sentence.


>    - Inline mode (a small webpack-dev-server client entry is added to the
>    bundle which refresh the page on change)
>
> Ah, now, that explains what you meant earlier when you said websocket and
other things. It gives context to the world inline mode.

Similar confusion for the historyApiFallback. Perhaps it's because I'm a
backend developer trying to learn this front-end technology.

Chris

**Comment by bebraw** [comment]
@lightwave Thanks a lot for your feedback. Comments below.

> In the Developing with Webpack chapter, I honestly don't think it has improve. Let me be more specific. Let's use the following as an example.

I will remove *html-webpack-plugin* from here and move it to the build chapter. So in the next edition we'll go with a static **index.html** till then and that's it. Less confusion

> inline/historyApiFallback

Very valid points. I'll add expanded explanations to those.

--

Now that I think of it, the ordering isn't correct from beginner's point of view. Introducing Webpack early on leads to unneeded complexity. Pete Hunt's recommendation touched on this. After I get a good 2.0 out with some immediate fixes, I'll modernize the content to use Redux. But once that work is done, I could spend some time addressing the ordering problem. Currently it's roughly like this:

0. Discuss Webpack and how it compares to other tools and how to get a development environment set up.
0. Discuss how to build the app using React and how to build it with Webpack
0. Discuss advanced development related topics

In the future, we might want to end up with something like this instead:

0. Discuss how to build the app using React and how to build it with Webpack
0. Discuss Webpack and how it compares to other tools and how to get a development environment set up.
0. Discuss advanced development related topics

This would mean that you would use some emerging tool to get a simple environment set up and just develop the application. After that the focus would be on Webpack for a while as now. I could also dig into some more advanced Webpack related topics in this ordering. It's almost starting to feel like a series of mini books. :smile:

I, amongst many other people, have been working on solutions for that environment problem. You can find the core idea at [webpack-presets](https://github.com/survivejs/webpack-presets). It looks a little complicated at the moment, but I think ideally you should be just able to do something like `webpack-presets react-hmr` to get a reasonable development environment. It's still missing that CLI part (not hard to do).

I'll keep an eye on emerging solutions and see if something sticks. Thanks for making me aware of the issue. I'll apply some bandaid over shorter term. Bigger, structural fixes are going to need some patience and/or tool development. :+1:

**Comment by lightwave** [comment]
Thanks great Juho!

I have to admit that once I started on the React part, I actually like the
book. I'm looking forward to the restructuring.

One little bug in http://survivejs.com/webpack_react/implementing_notes/

In Note.jsx, it shouldn't use placeholder in renderEdit. It should be
value={this.props.task}. Otherwise, when the user click on the task, it'd
just show an empty input text box.

Chris


Chris

**Comment by bebraw** [comment]
@lightwave Thanks. My apologies for the rough start. :+1:

I fixed most of the little issues (bandaid) today. There are still a couple of simplifications to do, but it's all for better.

I'll get that placeholder thing fixed as well. Nice catch. :smile:

**Comment by lightwave** [comment]
One thing you might want to throw in there in a sidebar is the following
syntax.

editNote = (id, task) => { const notes = this.state.notes.map((note) => { if
(note.id === id && task) { note.task = task; } return note; }); this.
setState({notes}); };


The ES6 destructuring syntax is confusing to me at the last line.
this.setState({notes}).

Is that equivalent to this.setState({notes: notes})? Seems like a strange
syntax. I'm coming from Clojure/Lisp functional programming background.
This syntax looks really weird...  I'm familiar with Clojure's
destructuring syntax and the concept itself but this syntax threw me off.
I'd imagine readers new to ES6 would find it a bit confusing too.

Chris

**Comment by bebraw** [comment]
> The ES6 destructuring syntax is confusing to me at the last line. this.setState({notes}).

Good catch. I'll add a comment there expanding on it.

> Is that equivalent to this.setState({notes: notes})?

Correct.

Note that the current version of the book contains a language feature appendix where I dig into deeper detail on the features used. That felt like a good move. :smile_cat:

**Comment by lightwave** [comment]
I just caught a problem.  Don't simply replace the placeholder to value=.
Because once you replace it with value={this.props.task}, React will want
you to have a onChange handler; otherwise, any typing you do on the input
box will have no effect. What's the proper solution for that?

Chris

Chris

**Comment by lightwave** [comment]
If I understand React correctly, the input element has become a control
element.

I think the proper solution is to have Note.jsx maintain a temp state to
hold the value being edited. Once it's blur/committed, the in-flight value
will be used in finishEdit to pass it back up to App in the onEdit callback.

Does this sound reasonable? Or is there a more "React.js" idiom to deal
with that?

Thanks
Chris


Chris

**Comment by bebraw** [comment]
> I think the proper solution is to have Note.jsx maintain a temp state to hold the value being edited. Once it's blur/committed, the in-flight value will be used in finishEdit to pass it back up to App in the onEdit callback.

> Does this sound reasonable? Or is there a more "React.js" idiom to deal with that?

Well, in the current design the input is **uncontrolled**. We show it as empty and pick up its value `onBlur` or if the user hits return. The input state exists in DOM during editing.

It's true this isn't the only way to design it. If we wanted to use an initial value, we could make it [controlled](https://facebook.github.io/react/docs/forms.html#controlled-components) and track the state ourselves. This way is more complex, but it also gives you more control.

It's worth covering this. I'll add a little section about an alternative design to `Editable` discussion (you might not be at that bit yet).

**Comment by lightwave** [comment]
I've just finished the Editable component and understand how it works. I
guess it boils down to personal preference. Is the pattern you use a React
idiom to handle editable control? I personally found it too tightly coupled
with the container/app. The editing state transition has nothing to do with
the App overall. It's an internal detail on how an Editable component
works. I feel that encapsulating the editing state and the in-flight value
is the way to go.  Besides, it seems that it's the easiest way to provide a
true editing experience so that the user doesn't have to type an entire new
name.

Thoughts?

Chris


Chris

**Comment by bebraw** [comment]
> Is the pattern you use a React idiom to handle editable control? ...

`Editable` actually maintained the editing state initially. This scheme breaks down if we want to create a new note and make it editable initially so you get the input straight away. If `Editable` maintains state itself, we don't have control over it. Based on this pushing the state out of the component felt like a good way to go.

It's not the only solution and maintaining the state internally actually worked well until this additional constraint came along.

> Besides, it seems that it's the easiest way to provide a true editing experience so that the user doesn't have to type an entire new name.

Yeah, this is a good point. I think I'll discuss this when I add a little section about controlled/uncontrolled fields there. `Editable` is pretty cool as it affords multiple different designs like this.

Thanks for the feedback!

**Comment by lightwave** [comment]
I think a simple compromise is to allow an optional prop to pass into
Editable to decide on its initial editing state. My thinking is that, if
we're naming the component Editable, it means the component encapsulate the
mechanics of wether it's editable or not. If the state management is pushed
up to the parent, then Editable simply becomes a convenient wrapper of
if-then-else statement. It's more like TextfieldOrStaticfield component.

Chris


Chris

**Comment by bebraw** [comment]
Yeah. That sounds good. I need to see what this would mean internally, but if it's not too bad, this could be a worthwhile change to make. Then you get something controllable/uncontrollable quite easily and the interface remains neat yet powerful.

**Comment by bebraw** [comment]
I found something that could fit this purpose perfectly: https://github.com/jquense/uncontrollable . This would allow us to make an uncontrolled version of `Editable` quite easily. I think I'll have a quick chat with the author to get a clearer idea. :+1:

**Comment by lightwave** [comment]
Actually, I think I'm fundamentally missing some important concept.  How's
an input component useful without being a controlled component in React. I
mean, what's the point of letting user enter/edit something into an input
box and not getting notified by an onChange handler to update the state at
the root or whereever.

Chris

**Comment by bebraw** [comment]
> Actually, I think I'm fundamentally missing some important concept.  How's
> an input component useful without being a controlled component in React. I
> mean, what's the point of letting user enter/edit something into an input
> box and not getting notified by an onChange handler to update the state at
> the root or whereever.

If you don't implement any event handlers at all, it's useless. Correct. We still have state, but in this case we let the DOM control it.

Note that React will allow you to get the input state through refs as well. Refs provide an escape hatch to the DOM API. I would rather solve problems without refs if possible, though, as using them ties the components to the DOM. Sometimes there's no way to avoid this (i.e., if you are measuring an element).

**Comment by bebraw** [comment]
Time to close. Thanks a lot for the feedback! I integrated a lot of ideas based on it. `refs` are covered in greater detail and so on.
