### ISSUE TITLE
Explain the process of "session state", login/logout, with ReactJS, SPA

### ISSUE THREAD

**Issue by justjacksonn** [survivejs/webpack_react#31]
You may cover this topic, not entirely sure, but one other area of confusion for me around SPA in general, but ReactJS in particular is handling login, logout, and maintaining session state. In particular, if a user's browser closes (accidentally, crashes, etc), and the user then restarts it and goes back to the site.. they should remain logged in. How does a ReactJS application manage the state, and return the user to where they were within the application?

This topic could also be applied to something similar, like a web cart... back in the day, web carts typically stored data in HttpSession on the server side, but today with our stateless Rest APIs and Ajax requests, how would a SPA and in this case ReactJS application maintain state across requests, browser restarts, etc.

**Comment by bebraw** [comment]
If we do #76 at some point, this discussion should go there. A good blog post topic as well. Closing.

In short, there are standard techniques (sessions, cookies, whatnot) that go beyond React. The same ideas apply here. In addition Relay/GraphQL and Falcor likely have something to say on this matter.
