### ISSUE TITLE
Edit callbacks - check if set

### ISSUE THREAD

**Issue by ghilios** [survivejs/webpack_react#312]
In chapter 4, the initial implementation before adding callback support for onEdit results in a failure, since it is not set. You correctly call this out in the text. However, I don't think you really should've had to.

Shouldn't callbacks be an optional capability? I think you could've either checked for the existence of this.props.onEdit before calling it. An even cleaner mechanism may have been defaulting it to doing nothing unless set by the parent. What do you think?

**Comment by bebraw** [comment]
Good catch. This was a good chance to point out the usage of `propTypes` (later chapter). I added a check there with a note.
