### ISSUE TITLE
Chapter 5, persist.js code issue

### ISSUE THREAD

**Issue by ghilios** [survivejs/webpack_react#314]
export default function(alt, storage, storeName) - should this instead have a function name of sorts? the call to persist() from index.jsx fails without one. I just created an arbitrary one (entry) and that fixed things

**Comment by bebraw** [comment]
This is a strange one. `export default` should be according to the spec. How does it fail for you? Are you running against `dev` branch?

I'll do some further research on this regardless.

**Comment by ghilios** [comment]
Ahh it is working for me now. I really don't know what changed between now and then. Perhaps some babel configuration? From what I recall, it failed with something like "persist function not found". Anyways, sorry for the false alarm!

**Comment by bebraw** [comment]
@ghilios No worries. Thanks a lot for the feedback! Do you want that I replace your GitHub nick with your real name at the book "thanks" section?

**Comment by ghilios** [comment]
Sure that'll work! Thanks for that. You've got a solid book going on here. I spent a few days and many browser tabs trying to wrap my head around what you succinctly were able to walk me through. My team at Indeed is moving our frontends over to React and I will likely get copies for everyone!

**Comment by bebraw** [comment]
@ghilios Ok, cool. Thanks again.

If you want to do a little testimonial about the book, send a sentence or two at my email (info at survivejs.com works). :+1:

Happy holidays! :christmas_tree:
