### ISSUE TITLE
React and Flux -

### ISSUE THREAD

**Issue by radeshrao** [survivejs/webpack_react#317]
I noticed that the leanpub-delete-insert and leanpub-delete-end markups are rendered as-is on the website. 

![screen shot 2015-12-29 at 3 56 41 pm](https://cloud.githubusercontent.com/assets/1417267/12042056/32b81714-ae45-11e5-9571-c363fa58e139.png)

**Comment by bebraw** [comment]
Yeah, this has been fixed at `dev`.

I think I'll do a hot fix for that to fix the outlook. Thanks!

**Comment by bebraw** [comment]
Fixed in online version. Leanpub will get the update once I do a new beta.
