### ISSUE TITLE
Hot Module Reload / End of chapter 3

### ISSUE THREAD

**Issue by beaugaines** [survivejs/webpack_react#318]
I'm following the LeanPub version of the text.  When I added the HMR related config it broke my app.  No errors in console or in dev tools.  I copy/pasted in the `.babelrc` and `package.json` from the repo here and now it works but that is pretty unsatisfying, especially given how different they are to what is in the text

**Comment by davegomez** [comment]
Can you provide an example code and the version of the packages you are currently using?

**Comment by bebraw** [comment]
@beaugaines Which version of the book are you reading? I launched a [beta](http://survivejs.com/blog/survivejs200-beta2/) recently. That introduced a big change to configuration (Babel 5 -> 6). You should be able to get the most recent version through Leanpub.

**Comment by beaugaines** [comment]
Ok.  I have the version published on 13 Dec.

**Comment by bebraw** [comment]
@beaugaines Ok, got it. You can get the newest one directly through Leanpub. Here are [the release notes](http://survivejs.com/blog/survivejs200-beta2/) with major changes. Even though it's a little rough at times, you have to keep up with the tech. Esp. that Babel change was big but necessary. I hope this helps.

**Comment by beaugaines** [comment]
Understood...thanks for following up

**Comment by bebraw** [comment]
@beaugaines No probs. Feel free to poke me if you find frustrating bits. That's the point of beta. :+1:
