### ISSUE TITLE
Errors running chapter 8

### ISSUE THREAD

**Issue by chasm** [survivejs/webpack_react#32]
When I do npm install in the chapter 8 code and then npm start, I get the following. This has been dogging me in my own version of the code as well. Is there a Lane somewhere else?

```sh
ERROR in ./app/components/Lane.jsx

/Users/aries/Workspace/webpack_react/project_source/08_kanban_style/kanban_app/app/components/Lane.jsx
  14:21  error  Lane is already declared in the upper scope  no-shadow

✖ 1 problem (1 error, 0 warnings)


ERROR in ./app/components/Notes.jsx

/Users/aries/Workspace/webpack_react/project_source/08_kanban_style/kanban_app/app/components/Notes.jsx
  14:21  error  Notes is already declared in the upper scope  no-shadow

✖ 1 problem (1 error, 0 warnings)
```

**Comment by bebraw** [comment]
Thanks for bringing this to my attention!

It was missing a linting rule. Currently decorators are a bit problematic that way. The current linting tech doesn't detect them correctly (I'm hoping this will get fixed soon).
