### ISSUE TITLE
React and Flux -

### ISSUE THREAD

**Issue by atleb** [survivejs/webpack_react#325]
loving the book, 
got a bit stumped on the flux implementation as editing broke. tracked it down to **import assign from 'object-assign';**
not in the skelton version, 
http://survivejs.com/webpack_react/react_and_flux/#setting-up-a-skeleton
but not bolded in the following create snippet:
http://survivejs.com/webpack_react/react_and_flux/#implementing-create-

_since it isn't used before the Update part, it might make sense to included it then instead, along with a short comment?_

**Comment by bebraw** [comment]
Thanks for spotting! This will be fixed in the next beta. :+1:
