### ISSUE TITLE
extract-text-webpack-plugin 1.0 needs webpack-sources

### ISSUE THREAD

**Issue by robertlyc** [survivejs/webpack_react#326]
extract-text-webpack-plugin 1.0 needs extract-text-webpack-plugin

sees https://github.com/webpack/extract-text-webpack-plugin/issues/143

so maybe it needs ` npm i webpack-sources --save`

**Comment by bebraw** [comment]
There's a [PR](https://github.com/webpack/extract-text-webpack-plugin/pull/142) waiting to get merged that will fix this. The author forgot to add `webpack-sources` as a dependency when making a little change to the package. Just hoping it will get merged soon.

I'll close this issue once the merge has gone through. Thanks for the report!

**Comment by bebraw** [comment]
@robertlyc The plugin has been updated. It doesn't need `webpack-sources` anymore. Closing.
