### ISSUE TITLE
Introduction -

### ISSUE THREAD

**Issue by idoan** [survivejs/webpack_react#327]
Your page doesn't load on ios7, the background pic is being processed indefinitely, so this blocks the page from loading. I think it is trying to fit the picture to the page, but all it does is zooming the page extreme amount.

**Comment by bebraw** [comment]
Thanks for letting me know! I guess the `cover` option is wreaking havoc. I need to simplify the CSS somehow and probably drop sass from it.

**Comment by comptrol** [comment]
To be more specific, it doesn't load on ipad , but it loads somehow on iphone 4 and when I rotate the iphone the same issue arises, the brown background image where a man is running can't be processed and stretched all the way down below.

Thabks for your generousity !

**Comment by bebraw** [comment]
@idoan Can you have a look now? I gave the site CSS a heavy refresh.

**Comment by bebraw** [comment]
Closing. Feel free to open again if you encounter issues. :+1:

**Comment by idoan** [comment]
Sorry, I just saw the mail. 

Yes it still stands, 3/5 of the page is stretched header image, the remaining 2/5 is the content . But this is better than previous case, as I can now scroll to the bottom to see the content.

**Comment by bebraw** [comment]
No probs. I need to figure out a proper way to debug this. Can you get a screenshot of the situation?

**Comment by bebraw** [comment]
Hi,

I moved this issue to https://github.com/survivejs/site/issues/27 .
