### ISSUE TITLE
Isomorphic Rending Problem

### ISSUE THREAD

**Issue by maxehnert** [survivejs/webpack_react#334]
First just wanted to say thanks for everything you have done and published. 

I'm having an issue with the markup being duplicated by React. The react devtools are giving me an error stating that the server side rendered content changed and the client side reran the render and is producing duplication. 
When I click the button to add a new note, it is producing 2 notes. One on the server and on on the client side. 
Perhaps it is from my lack of experience working with react, but I cannot find a problem in the code in the tutorial that would cause this other than perhaps the way webpack config is setup. 

To put this into context, it has had this problem form the beginning and I am currently on this page where the problem continues to persist (after initial setup of alt but before using AltContainer as there is another err) [http://survivejs.com/webpack_react/react_and_flux/](http://survivejs.com/webpack_react/react_and_flux/)

This is the error I am seeing in the console:

```
Warning: React attempted to reuse markup in a container but the checksum was invalid. 
This generally means that you are using server rendering and the markup generated on the server was not what the client was expecting. 
React injected new markup to compensate which works but you have lost many of the benefits of server rendering. 
Instead, figure out why the markup being generated is different on the client or server:
 (client) <div data-reactid="
 (server) <div data-reactid="
```

The `reactid`s are different when I inspected those.

**Comment by bebraw** [comment]
Hi,

Can you link me to your project so I can have a good look?

Isomorphic rendering has certain challenges of its own. I don't discuss it in detail as it would require a real backend to be really useful. Now the benefits would be minimal at best given we deal with data strictly on frontend.

Viktor Turskyi has written a really nice [blog post](http://blog.koorchik.com/isomorphic-react/) about the topic btw.

**Comment by maxehnert** [comment]
Here is the link to the project. [https://github.com/maxehnert/react-kanban](https://github.com/maxehnert/react-kanban)
I have gotten a little farther along in the tutorial at this point but still see the same error message and duplication problem.
Thanks!

**Comment by bebraw** [comment]
The problem is that the version of html-webpack-plugin (2.0.0 based on package.json) you are using injects *bundle.js* twice -> React gets evaluated twice -> chaos ensues.

You could try reverting to a stable version like this:

```diff
diff --git a/package.json b/package.json
index 2752da8..ff18293 100644
--- a/package.json
+++ b/package.json
@@ -23,8 +23,8 @@
     "babel-preset-react": "^6.3.13",
     "babel-preset-react-hmre": "^1.0.1",
     "css-loader": "^0.23.1",
-    "html-webpack-plugin": "^2.0.0",
-    "html-webpack-template": "^3.0.1",
+    "html-webpack-plugin": "^1.7.0",
+    "html-webpack-template": "^2.5.2",
     "style-loader": "^0.13.0",
     "webpack": "^1.12.10",
     "webpack-dev-server": "^1.14.0",
```

Before patching, remember to remove the updated packages from your *node_modules*. `npm install` should get the versions we need after that.

I think I'll move the plugin to the build chapter in the next version to decrease the risk for breakage like this. A little easier to follow as well (less steps early on).

Let me know how it goes. :+1:

**Comment by maxehnert** [comment]
Great I'll try that out today and close out the issue if it's fixed. I didn't realize I was on the wrong version. Thanks for the quick response!
