### ISSUE TITLE
Implementing a Basic Note Application - Arrow function

### ISSUE THREAD

**Issue by eks1985** [survivejs/webpack_react#337]
Here is possible to omit round brackets because of single argument of function 

```
<ul>{notes.map((note) =>
      <li key={note.id}>{note.task}</li>
)}</ul>
```

Improved version looks less noisy
```
<ul>{notes.map(note =>
      <li key={note.id}>{note.task}</li>
)}</ul>
```
Or in one line
```
<ul>
  {notes.map(note => <li key={note.id}>{note.task}</li>)}
</ul>
```

**Comment by bebraw** [comment]
Yeah. That could be a worthwhile change. It's definitely less noisy. So far I have preferred `()` format since you need to go that way if you add parameters, but I don't mind showcasing this alternative. Thanks!
