### ISSUE TITLE
HtmlwebpackPlugin needs config option inject:false

### ISSUE THREAD

**Issue by mrbinky3000** [survivejs/webpack_react#340]
While following section 4.4 Adding New Items to the List, I noticed that clicking the + button once inserted the item twice.

That's because bundle.js is getting included twice.
See jaketrent/html-webpack-template#5

**Comment by bebraw** [comment]
Thanks for the report!

The fix will make it to the next version (trying to get that out today). I've pushed the html-webpack-plugin bits to the build chapter so it's harder to break it in the future. :+1:
