### ISSUE TITLE
10.4 Converting propTypes to Flow Checks  v2.0.0.0rc3

### ISSUE THREAD

**Issue by mrbinky3000** [survivejs/webpack_react#346]
Minor bug.  When porting app/Editable.js and app/Note.js from propType to Flow, the code samples might want to reflect that flow won't see them unless you add 

```javascript
/* @flow */
```

to the top of the script, like we did in demo.js a little earlier in the chapter.  It's just not immediately evident that this needs to happen.  If they don't do it, they will receive a false answer of 0 type errors even if there are errors.

**Comment by bebraw** [comment]
Nice catch! I'll fix that. :+1:

**Comment by bebraw** [comment]
Fixed. The change will make it to the next version.
