### ISSUE TITLE
How to Succeed at Technical Books? -

### ISSUE THREAD

**Issue by wilsonmar** [survivejs/webpack_react#347]
Great article here.
There are some minor grammar items.

1) "You can sell the result through Gumroad, DPD and such."
I would put a comma after DPD.

2) "rather than shoot for the moon on the first go."
there is an American saying 
"rather than shoot for the moon from the get-go."
http://www.merriam-webster.com/dictionary/get–go

**Comment by bebraw** [comment]
Thanks. Fixed at https://github.com/survivejs/site/commit/68b773947bb887f0cdd04e7d44282b731e863cf2 .
