### ISSUE TITLE
Improve State change communication

### ISSUE THREAD

**Issue by eMerzh** [survivejs/webpack_react#350]
it might be me but i have a couple of request for the section "[Communicating Note State Changes](http://survivejs.com/webpack_react/implementing_notes/#communicating-note-state-changes)".
First, it might be a good idea to describe that before this point, the onblur does not work (as you ask to "edit" to test the changes).

then, i think that the logic about why this pattern is used, must really be more explained.
i didn't catch why we need set the state from Note => Notes => App... and why the setState on Note only doesn't work...is it only because App is the root component? or smth else ?

**Comment by bebraw** [comment]
Thanks for pointing this out! I'll clarify the section.
