### ISSUE TITLE
Developing with Webpack - Add note that React Dev Tools don't work w/ iframe path

### ISSUE THREAD

**Issue by thehunmonkgroup** [survivejs/webpack_react#351]
https://github.com/webpack/webpack/issues/247 indicates that the React Developer Tools don't work when using the iframe approach for loading webpack-dev-server (localhost:8080/webpack-dev-server/ in the example you provide).

It might be nice in the note where you mention that approach to also note that the React Dev Tools don't work in that config -- I spent a fair amount of time trying to figure out why I couldn't get them to work because I didn't have that information.

**Comment by bebraw** [comment]
@thehunmonkgroup Ah, that's a great point. I'll get this fixed!
