### ISSUE TITLE
Editable component onClick not bound

### ISSUE THREAD

**Issue by wzrd-clss** [survivejs/webpack_react#352]
http://survivejs.com/webpack_react/from_notes_to_kanban/#connecting-lane-with-editable-
there is no onclick event bound to the Editable component in this section like the sentence at the end of it suggests

this calls activateLaneEdit()
```html
<Editable className="lane-name" editing={lane.editing}
value={lane.name} onEdit={this.editName} />
```
```javascript

  editName(id, e, name) {
    console.log(`edit lane ${id} name using ${name}`);
  }
```
this calls editName()
```html
<Editable className="lane-name" onClick={this.editName} editing={lane.editing}
value={lane.name} onEdit={this.editName} />
```
```javascript

  editName(id, e, name) {
    e.stopPropagation();
    console.log(`edit lane ${id} name using ${name}`);
  }
```

e.stopPropagation(); needs to be called inside editName() else activateLaneEdit() will also be called

**Comment by bebraw** [comment]
Thanks for the report! I'll get that sorted out.

The `dev` version of the chapter has received a few tweaks but it's quite possible this one is missing.

**Comment by wzrd-clss** [comment]
if you fix it in the way that i have it above, the following sections will break. you may have to find another way to fix it
