### ISSUE TITLE
Introduction, Webpack Config and Basic Note Application

### ISSUE THREAD

**Issue by saviomuc** [survivejs/webpack_react#354]
Hi, so far I like your book and I relly appreciate your effort. But there is one thing which really makes it hard for me to stick with it.

In the introductory chapter you write: 

`I expect that you have a basic knowledge of JavaScript and Node.js. You should be able to use npm on an elementary level. If you know something about Webpack or React, that's great. By reading this book you will deepen your understanding of these tools.
`
when actually what you mean is: The reader should have a basic understanding of ES6 and React. 

## Implementing a Basic Note Application - Adding new items to the list not clear

`Currently the state of our application is tied to render(). In order to make it possible to modify it, we'll need to convert it into component state. After that, we can define operations to alter it. As the state changes, React will update the list automatically for us. 
`
 I am lost at this point. You make many assumptions:

- The reader understands what state means in the context of React
- The reader understands what a component state is and why only then you can define operations to alter it
- The reader understands the difference between 'state is tied to render()' and 'component state'
- The reader understands why React will update the list automatically
- The reader understands what `constructor` is, where it's coming from and why you need it.

All of that is not explained in previous chapters.  It would be great if you'd add a brief explanation or summary on these concepts.

**Comment by bebraw** [comment]
Thanks for bringing this up! I'll try to get this sorted out for the final. Esp. those bullets.

**Comment by bebraw** [comment]
I'll sort this out tomorrow. Feel free to drop issues like this in the meantime. They are of great help!
