### ISSUE TITLE
Implementing a Basic Note Application - Improving Component Hierarchy not clear.

### ISSUE THREAD

**Issue by saviomuc** [survivejs/webpack_react#355]
The whole section is a little bit confusing. 

1. `By looking at our application, we can see there's a component hierarchy like this` > It's the classical case of 'Clearly, evidently and as you can see'. I can see what you mean but it really is not clear.
2. Also it's not clear from the beginning why we should do that. I suggest a rewrite like (I'm not a native speaker):

`To avoid code duplication and promote reuse it's best to split the component into hierachical parts. One possible use case is to create multiple notes list per app. The component hierarchy could look like that:

App - Retains application state and high level logic
Notes - A wrapper used to render individual notes.
Note - Contains all functions related to editing, deleting and adding notes.
`

Note that I left out 'Lanes' because that information doesn't add anything to the context at this point.

**Comment by bebraw** [comment]
Cool points. Thanks again!
