### ISSUE TITLE
From Notes to Kanban - LeanPub Tag Issue?

### ISSUE THREAD

**Issue by john-benson** [survivejs/webpack_react#362]
Hey,

Love your Webpack + ReactJS!

Going through the "From Notes to Kanaban" chapter I noticed these weird text strings under the app/main.css changes:

http://imgur.com/qnBshpl

I have no knowledge of LeanPub or I'd offer a PR to fix :(

**Comment by bebraw** [comment]
Thanks for bringing this up! I'll get it fixed. It has most likely something to do with my site generator. :+1:

**Comment by john-benson** [comment]
No problem. Loving the content so far, just purchased a copy of the book.

**Comment by bebraw** [comment]
This should be fixed now.

If you notice anything else, let me know. I hope you enjoy the book. :+1:
