### ISSUE TITLE
Introduction -

### ISSUE THREAD

**Issue by ramn** [survivejs/webpack_react#366]
The Submit feedback banner covers a large part of the content on mobile

**Comment by bebraw** [comment]
Good point. Maybe just decrease feedback banner size 50% for mobile or just drop it there?

**Comment by ramn** [comment]
Personally, I'd prefer to not have it on mobile since the screen is so small already

**Comment by bebraw** [comment]
Fair enough. I'll drop it there. :+1:

**Comment by bebraw** [comment]
This should be fixed now. Thanks for letting me know!
