### ISSUE TITLE
Webpack and React - Small suggestion regarding order of App.jsx and Note.jsx

### ISSUE THREAD

**Issue by saviomuc** [survivejs/webpack_react#370]
I think it would be a better idea to first introduce Note.jsx and then App.jsx.

While I do understand, that App.jsx is the entry point of the whole application, it might be better to introduce it a little bit later from an educational point of view. 

Reason:
Creating App.jsx first and importing Note.jsx throws an error because the latter doesn't exist at that point. Also it is irritating to the reader because at that point he might think that he missed something. ("Huh? Where is the Note.jsx now coming from?"). One of the most annoying things in any tutorial.

Suggestion:
Introduce the simple Note.jsx first. Then show the reader how to render the component via the App.jsx. Btw. You already do the same with the index.jsx.

Effect:
There is a clear logical progression from small component to "big picture". Note.jsx > App.jsx > index.jsx as opposed to App.jsx > Note.jsx > index.jsx

**Comment by bebraw** [comment]
This is a cool idea, yeah. I'll get back to this once I have my Webpack specific book bits done (still editing + content work left).

**Comment by saviomuc** [comment]
Thanks. Good luck on your Webpack book! =)

**Comment by anweshm4** [comment]
+ 1 to the suggestion.
