### ISSUE TITLE
Setting Up Assets - Code Error

### ISSUE THREAD

**Issue by lucasfcosta** [survivejs/webpack_react#371]
Task List:
- [ ] `component.js` file should export the result of invoking the function which builds an HTMLObject or just the object itself instead of exporting a function

---------------------

Hello guys, I was reading your book and at the chapter [Setting Up Assets](http://survivejs.com/webpack_react/developing_with_webpack/#setting-up-assets) there's a problem with the code.

```js
// Here you are exporting a function
module.exports = function () {
  var element = document.createElement('h1');

  element.innerHTML = 'Hello world';

  return element;
};
```

As you can see above, you are exporting a function and then, at this:

```js
var component = require('./component');
var app = document.createElement('div');

document.body.appendChild(app);

app.appendChild(component());
```

You will try to append to the document's body that function you just returned and it won't work, because it's not an `HTMLElement`, it is a `function` 

To fix this you should export the result of invoking that function. It would be something like:

```js
module.exports = (function() {
    var element = document.createElement('h1');

    element.innerHTML = 'Hello World';

    return element;
})();
```

You could also export the element object only, the result would be the same.

Thanks for your book, it's been awesome until now :smile:

**Comment by bebraw** [comment]
Hi,

The key part is in `component()`. As we invoke the function, we get a `HTMLElement`. It would fail without that invocation.

Reading the code I realized we can simplify the solution simply to this:

```javascript
var component = require('./component');

document.body.appendChild(component());
```

We could also do

```javascript
document.body.appendChild(require('./component')());
```

but that would be golfing it.

I hope this clears it up. :+1:
