### ISSUE TITLE
Question: What should go in the Note.jsx 

### ISSUE THREAD

**Issue by diegodesouza** [survivejs/webpack_react#374]
Hello, thanks for sharing this book with us, I've learned a lot from it. 
I was looking over your master branch, and it seems like you've left the code you extracted to `Editable` in the `Note.jsx` still. But it seems like it's not be used at all since we implemented the Editable instead. I'm guessing nothing goes in the `Note` module anymore?

cheers

**Comment by bebraw** [comment]
It's safe to remove, yeah. I'll fix this. Thanks. :+1:
