### ISSUE TITLE
Chap 3 "Key" paragraph on IDE's

### ISSUE THREAD

**Issue by gkedge** [survivejs/webpack_react#375]
At the start of Chap 3, a 'key' paragraph suggests various editors and IDE's geared toward React programming.  Since the book also focuses on Webpack and really emphasizes webpack's hot module replacement, user's of WebStorm may be confused at the erratic '_sometimes it will replace; sometimes it won't_' behavior.  This is likely due to a file saving feature called 'safe save' that needs turning off.

'Safe save' works by first saving a changed file to a temporary file. If the save operation succeeds, the file being saved is replaced with the saved file. (Technically, the original file is deleted and the temporary file is renamed.).  That plays havoc with HMR.

With such a visible book, it might be worth a mention there in Chap 3 when discussing IDE's or in the HMR section.

**Comment by bebraw** [comment]
Thanks! Added a mention.
