### ISSUE TITLE
Developing with Webpack - webpack -d is needed to enable sourcemap

### ISSUE THREAD

**Issue by queirozfcom** [survivejs/webpack_react#376]
I'm following the tutorial and, when I ran `npm run build` after adding `devtool: 'eval-source-map',`to my config as instructed, no source map was generated. 

I googled a little bit and arrived at [this so answer](http://stackoverflow.com/a/32298725/436721) which suggested that I used `webpack -d` instead, and it worked.

**Comment by bebraw** [comment]
Thanks again!
