### ISSUE TITLE
Developing with Webpack -

### ISSUE THREAD

**Issue by vaichidrewar** [survivejs/webpack_react#379]
In the chapter 'Developing with Webpack' 
Subsection: 'Adding a Build Shortcut'
Book says to use 'npm run' shorcut. But it worked only when I ran 'npm run build' . 
Is this an error in the book?

**Comment by bebraw** [comment]
I will make that a little clearer, thanks.

The idea is that you can run any `package.json` script through `npm run`. Cases like `npm start` and `npm test` are exceptions. You can execute these too through `npm run`, though, so `npm start` and `npm run start` would be equivalent.
