### ISSUE TITLE
Strange tags in the middle of the quoted code.

### ISSUE THREAD

**Issue by PedroD** [survivejs/webpack_react#380]
If you look at this file: https://github.com/survivejs/webpack_react/blob/dev/manuscript/02_developing_with_webpack.md

You can see that there are some strange tags `leanpub-start-*` `leanpub-end-*` which seem to be delimiting possible changes. Is that normal?

**Comment by bebraw** [comment]
Hi,

The problem is that GitHub cannot display Leanpub specific syntax like that. It's better to read the book content through the [site](http://survivejs.com/webpack_react/introduction/).

Thanks for asking, though. :+1:

**Comment by PedroD** [comment]
Ah ok. Sorry hehe

Keep up the amazing work! Can't wait to buy your book in printed version :)
