### ISSUE TITLE
broken link to babel experimental doc in 03_webpack_and_react

### ISSUE THREAD

**Issue by deepak** [survivejs/webpack_react#381]
broken link for [babel experimental doc](https://babeljs.io/docs/usage/experimental/) in 
https://github.com/survivejs/webpack_react/blob/384b004edc8fa73d263f89b8dfd91d3e3766a9e5/manuscript/03_webpack_and_react.md#babel

as far as I can make out, this is because the experimental option was removed in https://github.com/babel/babel/commit/0916e2d189f8ec605ea0dcf9f6e4f86e5f3387d7#diff-eb45b4cccecac47c30867487e4ff3eb3R13

experimental was [removed](https://github.com/babel/babel/blob/83301afb6ea221118a7ea60e2b3a879030a3e1ee/CHANGELOG.md#500) in favour of stage
and stage was [removed](https://github.com/babel/babel/blob/83301afb6ea221118a7ea60e2b3a879030a3e1ee/CHANGELOG.md#more-helpful-error-messages) in favour of presets

so book should link to [Stage-X presets](http://babeljs.io/docs/plugins/#stage-x-experimental-presets-) now i guess

**Comment by bebraw** [comment]
Thanks! I think the page got removed during the Babel 5 -> 6 transition. Lots of broken link on the net due to that.
