### ISSUE TITLE
Compatibility with Safari

### ISSUE THREAD

**Issue by anweshm4** [survivejs/webpack_react#382]
The background seems to be continuously processing, especially if you resize the browser. Can be seen on iOS 9.

**Comment by bebraw** [comment]
I wonder what's up with that. It's really hard for me to debug this as I don't have an iPhone. I have xcode, though.

The background is literally just an image (small texture, standard CSS). Perhaps this can be simplified somehow.

Thanks for letting me know. :+1:

**Comment by bebraw** [comment]
Moved to https://github.com/survivejs/site/issues/27 .
