### ISSUE TITLE
can mention that componentWillMount will not re-render

### ISSUE THREAD

**Issue by deepak** [survivejs/webpack_react#384]
can mention in [Understanding React Components](https://github.com/survivejs/webpack_react/blob/08708baba4dfe8908b20688cd39b26bc2d7621dd/manuscript/04_implementing_notes.md#understanding-react-components) that setting state is performant

it says:

`componentWillMount()` gets triggered once before any rendering. One way to use it would be to load data asynchronously there and force rendering through `setState`.

as a newbie, it was not clear if "force rendering" is good or bad

the (react docs)[http://facebook.github.io/react/docs/component-specs.html#mounting-componentwillmount) clarify that:

```
Invoked once .... immediately before the initial rendering occurs. If you call setState within this method, render() will see the updated state and will be executed only once despite the state change.
```

can clarify the sentence to:

```
`componentWillMount()` gets triggered once before any rendering. One way to use it would be to load data asynchronously there and force rendering through `setState`. `render()` will see the updated state and will be executed only once despite the state change.
```

and can add a link to the docs 

also is there an order to these lifecycle methods being called ?
maybe clarify with a diagram ?

**Comment by bebraw** [comment]
Good points. I'll clarify that and try to get some kind of a diagram done. That section could be better.

**Comment by bebraw** [comment]
There's a [diagram](https://github.com/survivejs/webpack_react/blob/dev/manuscript/images/lifecycle.png) now. It gets the order and main phases.
