### ISSUE TITLE
3.3 Defining Your Own Babel Presets

### ISSUE THREAD

**Issue by adamskriger** [survivejs/webpack_react#385]
Great book. Thank you for all. 
- 
I just completed section "3.3 Defining Your Own Babel Presets" and I am getting the following error:

<img width="1235" alt="screen shot 2016-04-22 at 10 37 21 am" src="https://cloud.githubusercontent.com/assets/16260612/14744805/557f77ca-0876-11e6-8873-6c65e81c0cf7.png">

this is what my index.js file looks like:

```
require('./main.css');

var component = require('./component');

document.body.appendChild(component());

module.exports = {
  plugins: [
    require('babel-plugin-syntax-class-properties'),
    require('babel-plugin-syntax-decorators'),
    require('babel-plugin-syntax-object-rest-spread'),

    //We can pass parameters using an array syntax
    [
      require('babel-plugin-transform-regenerator'),
      {
        async: false,
        asyncGenerators: false
      }
    ]
  ]
};

```

this is what my .babelrc file looks like : 

```
{
  "presets": [
    "es2015",
    "react",
    "survivejs-kanban"
  ]
}

```

**Comment by bebraw** [comment]
There's definitely something funky going on. I wonder why it depends on that `globals.json`. One way to fix it would be to set up [json-loader](https://www.npmjs.com/package/json-loader) perhaps but that doesn't feel right.

Can you set up a standalone project to showcase the error? I'll look into it in detail then.

It's nice to hear you found the book useful. I am currently in the process of pushing all the webpack bits to [a book of its own](http://survivejs.com/webpack/introduction/). This gives me room to expand on both topics. 👍

**Comment by bebraw** [comment]
Ah, got it...

The problem is that all that

```
module.exports = {
  plugins: [
    require('babel-plugin-syntax-class-properties'),
    require('babel-plugin-syntax-decorators'),
    require('babel-plugin-syntax-object-rest-spread'),

    //We can pass parameters using an array syntax
    [
      require('babel-plugin-transform-regenerator'),
      {
        async: false,
        asyncGenerators: false
      }
    ]
  ]
};
```

should go to a project of its own. So you would have *index.js* and *package.json* at a new project root.

**Comment by bebraw** [comment]
That is to say you could do something like this:

1. `mkdir babel-preset-demo`
2. `cd babel-preset-demo`
3. `npm init -y`
4. Paste that `module.exports` bit to `index.js`
5. Install dependencies needed by that (`npm i <dep name> -S`)

I'm not sure if this will work through `npm link`. But you should be able to consume the package through GitHub at least if you push it there. The npm chapter has more info.

Let me know how it goes.

**Comment by adamskriger** [comment]
Yes, I definitely find the book to be great! It really is the first time
I've ever been able to understand the webpack set up. Thanks for publishing
this!

I resolved the error by doing as you suggested. I created a separate
index.js file in my root directory and moved the following code there. Now,
I have a separate index.js in my app directory and at my root directory as
shown in the attached screenshot! Is this correct?

Thanks for your help.

```
module.exports = {

  plugins: [
    require('babel-plugin-syntax-class-properties'),
    require('babel-plugin-syntax-decorators'),
    require('babel-plugin-syntax-object-rest-spread'),

    //We can pass parameters using an array syntax
    [
      require('babel-plugin-transform-regenerator'),
      {
        async: false,
        asyncGenerators: false
      }
    ]
  ]
};


```



*Adam Kriger*
*-*
*Front End Web Engineer | Full Stack Web Developer*
*-*
Javascript, React, Ruby on Rails, jQuery, HTML5/CSS3, Node.js + Express
Server, AJAX + Routing, SQL databases.
*-*
LinkedIn <http://www.linkedin.com/in/adamkriger> | Github
<https://github.com/adamskriger> | GA Profile
<https://profiles.generalassemb.ly/profiles/adamkriger>
*-*
Recent Projects:
Popstar App <https://popstar-app.herokuapp.com/> | Plantee App
<http://45.55.179.238:3000/> | ABC Apparel <https://vpv.herokuapp.com/>


On Fri, Apr 22, 2016 at 10:51 AM, Juho Vepsäläinen <notifications@github.com

**Comment by bebraw** [comment]
Looks alright, yeah. Can you push your preset to GitHub so I give it a go?

Here's the [book preset](https://github.com/survivejs/babel-preset-survivejs-kanban) for reference by the way. I know those `default`'s at **index.js** are a little weird. I had to hack around a little to make it work. 😦

**Comment by adamskriger** [comment]
Hi Juho,

Thanks for passing along the book preset. I created a repo for you to check
out my code here <https://github.com/adamskriger/webpack_react_JV>.

I'd be interested to know what you think.

It runs fine over here but please let me know that you're able to
access/clone the github repo.

Thanks,

Adam

*Adam Kriger*
*-*
*Front End Web Engineer | Full Stack Web Developer*
*-*
Javascript, React, Ruby on Rails, jQuery, HTML5/CSS3, Node.js + Express
Server, AJAX + Routing, SQL databases.
*-*
LinkedIn <http://www.linkedin.com/in/adamkriger> | Github
<https://github.com/adamskriger> | GA Profile
<https://profiles.generalassemb.ly/profiles/adamkriger>
*-*
Recent Projects:
Popstar App <https://popstar-app.herokuapp.com/> | Plantee App
<http://45.55.179.238:3000/> | ABC Apparel <https://vpv.herokuapp.com/>


On Fri, Apr 22, 2016 at 11:41 AM, Juho Vepsäläinen <notifications@github.com

**Comment by bebraw** [comment]
I understand better now. Let me expand on the idea.

The idea of Babel presets is that they are npm packages allowing you to share common Babel configuration across multiple projects. So in this case you would set up a separate repository and push your current **index.js** there. It's important to include the Babel plugins the preset depends on there through **package.json** (`npm install` them there as usual).

After you have define the preset this way, you can start depending on it at your boilerplate as a regular npm development dependency. It's important that you add it to your Babel configuration as well so it finds your preset.

I hope this clears up how it's supposed to work. The Babel handbook has [more information](https://github.com/thejameskyle/babel-handbook/blob/master/translations/en/user-handbook.md#making-your-own-preset).

**Comment by adamskriger** [comment]
I see. I am beginning to understand what you mean but not quite
knowledgeable enough to know how to implement it myself. In any case, thank
you for taking the time to explain this to me.

Is this at all related to why I might be receiving the attached error after
modifying my index.jsx file?

*Adam Kriger*
*-*
*Front End Web Engineer | Full Stack Web Developer*
*-*
Javascript, React, Ruby on Rails, jQuery, HTML5/CSS3, Node.js + Express
Server, AJAX + Routing, SQL databases.
*-*
LinkedIn <http://www.linkedin.com/in/adamkriger> | Github
<https://github.com/adamskriger> | GA Profile
<https://profiles.generalassemb.ly/profiles/adamkriger>
*-*
Recent Projects:
Popstar App <https://popstar-app.herokuapp.com/> | Plantee App
<http://45.55.179.238:3000/> | ABC Apparel <https://vpv.herokuapp.com/>


On Fri, Apr 22, 2016 at 12:20 PM, Juho Vepsäläinen <notifications@github.com

**Comment by bebraw** [comment]
@adamskriger Yeah. Babel preset simply won't fit there as it goes against the idea. The key point is that they enable sharing. That's why they are wrapped as npm packages. See [Babel presets at npm](https://www.npmjs.com/search?q=babel+preset) for more examples. The idea is always the same. 👍

By the way, if you have smaller questions related to the book content, feel free to join us at the [book chat](https://gitter.im/survivejs/webpack_react).

**Comment by adamskriger** [comment]
Thank you for all and thank you for the invitation to the bookchat. I look
forward to seeing you there.

Best,

Adam

*Adam Kriger*
*-*
*Front End Web Engineer | Full Stack Web Developer*
*-*
Javascript, React, Ruby on Rails, jQuery, HTML5/CSS3, Node.js + Express
Server, AJAX + Routing, SQL databases.
*-*
LinkedIn <http://www.linkedin.com/in/adamkriger> | Github
<https://github.com/adamskriger> | GA Profile
<https://profiles.generalassemb.ly/profiles/adamkriger>
*-*
Recent Projects:
Popstar App <https://popstar-app.herokuapp.com/> | Plantee App
<http://45.55.179.238:3000/> | ABC Apparel <https://vpv.herokuapp.com/>
