### ISSUE TITLE
Hot Module Replacement is disabled error. 

### ISSUE THREAD

**Issue by siegesmund** [survivejs/webpack_react#389]
I'm getting this error in the Chrome console: 
`Uncaught Error: [HMR] Hot Module Replacement is disabled.`

It's referenced in this issue, and the solution offered here solves the problem.
https://github.com/webpack/webpack/issues/1151

Still, it seems a little nicer to have those settings in the config file. 

Using Node 4.3.1 and Chrome 50.0.2661.86

**Comment by bebraw** [comment]
How did you end up fixing it? The thread is a little confusing and webpack source conflicts with some of that these days.

**Comment by siegesmund** [comment]
I added the hot and inline flags to the npm start script in package.json, and commented them out in the webpack config file. Those options are now invoked with:
`webpack-dev-server --hot --inline`

**Comment by bebraw** [comment]
There's actually a little inconsistency in webpack here. I read from the source that it sets `HotModuleReplacementPlugin` **only** through cli. If you use `webServer` field, it has to be set explicitly.

I'll be moving the book to use a [little boilerplate](https://github.com/survivejs/react-boilerplate) in the near future. That will solve this issue as we get something consistent to run.

Thanks for the report.

**Comment by bebraw** [comment]
`dev` is running boilerplate now. Release soon. 👍
