### ISSUE TITLE
npm --save-exact

### ISSUE THREAD

**Issue by tomByrer** [survivejs/webpack_react#390]
> “If you want to save an exact version of a dependency, use --save-exact. The shortcut for this is -E. If you install a dependency like this, npm skips using the default SemVer operator.”

A bit of a jump.  Though most programmers know what a 'version' is, if you have to explain what `npm` is, they are unlikely to know what 'SemVer' is & what that carrot means.  Likely will need a page of its own; or just remove to prevent rabbit trails.

(Do you say [rabbit trail](http://andtodaysidiomis.blogspot.com/2010/12/rabbit-trail.html) in Finland?)

**Comment by bebraw** [comment]
This is a valid point, yeah. It could easily go to the npm specific chapter at the second book as that's the right context.

Thanks for bringing this up.

**Comment by bebraw** [comment]
Moved to https://github.com/survivejs/webpack/issues/84 as this book doesn't have the mention anymore.
