### ISSUE TITLE
[Improvement] NoteStore.getNotesByIds

### ISSUE THREAD

**Issue by vjancik** [survivejs/webpack_react#393]
The current implementation ([Code link](https://github.com/survivejs/webpack_react/blob/dev/project_source/06_from_notes_to_kanban/kanban_app/app/stores/NoteStore.js#L42-L46)):
```javascript
getNotesByIds(ids) {
  return (ids || []).map(
    id => this.notes.filter(note => note.id === id)
  ).filter(a => a.length).map(a => a[0]);
}
```

Can be written much simpler as:
```javascript
getNotesByIds(ids) {
    return this.notes.filter(note =>
      (ids || []).includes(note.id));
  }
```

In book (v2.1.0): page 105

**Comment by bebraw** [comment]
I remember trying something simpler like this. There's one huge gotcha if I remember right. `getNotesByIds` must be ordered based on `ids`. That's why we need to do it in a little convoluted way.

Let's keep this open, though, as I want to revisit this and document better what's going on. 👍

**Comment by tomByrer** [comment]
> getNotesByIds must be ordered based on ids

Do you mean "sort smallest `id` is earliest in list"?  If so, perhaps you should have the `sortNotesByIds` function separate, which is called after `getNotesByIds`?  Or if @vjancik does collect the notes sorted by smallest first naturally, then add a test to prove it, that way the test acts like an intention documentation.

If there was a need for more performant code, sometime I'll leave in the older slow-but-clear code in as a comment, & faster but confusing code after.

**Comment by tomByrer** [comment]
> getNotesByIds must be ordered based on ids

Do you mean "sort smallest `id` is earliest in list"?  If so, perhaps you should have the `sortNotesByIds` function separate, which is called after `getNotesByIds`?  Or if @vjancik does collect the notes sorted by smallest first naturally, then add a test to prove it, that way the test acts like an intention documentation.

If there was a need for more performant code, sometime I'll leave in the older slow-but-clear code in as a comment, & faster but confusing code after.

**Comment by bebraw** [comment]
Splitting up the problem could work. We would get a simple filter at `getNotesByIds` as suggested. We would then apply the order on that. That sounds sane to me. 👍

**Comment by bebraw** [comment]
I ended up doing

```javascript
getNotesByIds(ids) {
  // `reduce` is a powerful method that allows us to
  // fold data. You can implement `filter` and `map`
  // through it. Here we are using it to concatenate
  // notes matching to the ids.
  return (ids || []).reduce((notes, id) =>
    // Concatenate possible matching ids to the result
    notes.concat(
      this.notes.filter(note => note.id === id)
    )
  , []);
}
```

That's a little neater than the old solution while retaining the order. 👍
