### ISSUE TITLE
[Mistake] TypeError: _this.props.onValueClick is not a function

### ISSUE THREAD

**Issue by vjancik** [survivejs/webpack_react#394]
Because the `activateLaneEdit` handler is attached [here](https://github.com/survivejs/webpack_react/blob/dev/project_source/06_from_notes_to_kanban/kanban_app/app/components/Lane.jsx#L15), instead of [here](https://github.com/survivejs/webpack_react/blob/dev/project_source/06_from_notes_to_kanban/kanban_app/app/components/Lane.jsx#L19-L20) as:
```javascript
<Editable
  className="lane-name"
  editing={lane.editing}
  value={lane.name}
  onValueClick={this.activateLaneEdit}
  onEdit={this.editName}
/>
```
There is an error [here](https://github.com/survivejs/webpack_react/blob/dev/project_source/06_from_notes_to_kanban/kanban_app/app/components/Editable.jsx#L29):
`Uncaught TypeError: _this.props.onValueClick is not a function`

Lane name editing still works because the changes go through the store.

**Comment by bebraw** [comment]
`onValueClick` needs to become optional as the editing state is handled differently there.

Good catch! Thanks.

**Comment by bebraw** [comment]
There's a check in place for this case now. Thanks.
