### ISSUE TITLE
[Bug] isDragging in Note.jsx

### ISSUE THREAD

**Issue by vjancik** [survivejs/webpack_react#396]
[Code](https://github.com/survivejs/webpack_react/blob/dev/project_source/07_implementing_dnd/kanban_app/app/components/Note.jsx#L41)

A Note maintains it's 0 opacity only as long as you drag it inside the same lane. If you drag it outside, then drag it back, it no longer has opacity 0.
My best guess as to why this happens is that while in the same Lane, React just swaps around existing DOM nodes. But when moving across DOM branches (Lanes), React destroys and recreates the Note DOM components and the reference of that Note being the "DragSource" is lost.

If I'm right, then one way to fix this would be to preserve the isDragging state through the store and pass it down as a prop.

**Comment by bebraw** [comment]
I'm not sure if losing the information after dragging a note from lane to lane is a problem, though. We are only interested in hiding the target to get that blank note we want.

Let's leave this open, though, as it might take some experimentation to figure out the right way to deal with this.

**Comment by vjancik** [comment]
But we are checking `isDragging` on the `DragSource` not `DropTarget` We are hiding the source, because we are holding it under the cursor, to create the illusion we are moving it.

**Comment by vjancik** [comment]
I just found a great way to solve this. :)
Change [this](https://github.com/survivejs/webpack_react/blob/dev/project_source/07_implementing_dnd/kanban_app/app/components/Note.jsx#L25-L45), to this:
```javascript
@DragSource(ItemTypes.NOTE, noteSource, (connect, monitor) => ({
  connectDragSource: connect.dragSource(),
  isDragging: monitor.isDragging()
}))
@DropTarget(ItemTypes.NOTE, noteTarget, (connect, monitor) => ({
  connectDropTarget: connect.dropTarget(),
  isOver: monitor.isOver()
}))
export default class Note extends React.Component {
  render() {
    const {connectDragSource, connectDropTarget, isDragging,
      isOver, onMove, id, editing, ...props} = this.props;
    // Pass through if we are editing
    const dragSource = editing ? a => a : connectDragSource;

    return dragSource(connectDropTarget(
      <li style={{
        opacity: isDragging || isOver ? 0 : 1
      }} {...props}>{props.children}</li>
    ));
  }
}
```

**Comment by bebraw** [comment]
Great idea! That will make it to the next release. 👍
