### ISSUE TITLE
[Mistake] path.join

### ISSUE THREAD

**Issue by vjancik** [survivejs/webpack_react#397]
Same as https://github.com/survivejs/webpack/issues/78. [Here](https://github.com/survivejs/webpack_react/blob/dev/project_source/08_building_kanban/kanban_app/webpack.config.js#L15).

If linux behavior:
```
> path.join('smth','too\else')
'smth/tooelse'
```
 is any indication of what would happen on Windows, then this would happen on Windows:
```
> path.join('smth', 'app/main.css')
'smth\appmain.css'
```
Didn't actually test it though.

**Comment by bebraw** [comment]
Yeah, I'll get these sorted out. Thanks. 👍

**Comment by bebraw** [comment]
There is only one `path.join` left in this book now and even that is in the correct format.

Thanks for the report. Closing!
