### ISSUE TITLE
[Suggestion] Linting problem

### ISSUE THREAD

**Issue by vjancik** [survivejs/webpack_react#398]
There's an issue with `ESLint`: https://github.com/eslint/eslint/issues/6001 https://github.com/eslint/eslint/issues/5679

and using [this](https://github.com/survivejs/webpack_react/blob/dev/project_source/package.json#L9) causes the linter to run for over 10 seconds (if your node_modules are populated, on OS X for sure, not sure what other platforms) .
I solved it by changing it to:
`"lint": "eslint ./app --ext .js --ext .jsx --cache",`

You may consider adding `webpack.config.js` too to replicate original behavior.

**Comment by bebraw** [comment]
Thanks. This chapter is going to the webpack book really soon. I've added `--cache` to the dev version there.

I'll close this once that has been published.

**Comment by vjancik** [comment]
The problem is in the dot `.` not in `--cache`. Replace `.` with `./app`. Sorry if I just said the obvious, from your response it seemed like you missed the point.

**Comment by bebraw** [comment]
Missed the point, yeah. Thanks for highlighting that.

**Comment by bebraw** [comment]
I'm tracking https://github.com/eslint/eslint/issues/5679 . If they can resolve the issue, perhaps the book doesn't need an update for this after all.

**Comment by bebraw** [comment]
Solved at `dev`. Given the release is so near, closing.

**Comment by bebraw** [comment]
@vjancik Looks like they did a fix. See https://github.com/eslint/eslint/issues/5679 . That could help. 👍
