### ISSUE TITLE
04 chapter

### ISSUE THREAD

**Issue by vitaliy-kotov** [survivejs/webpack_react#4]
>This will get problematic with our import TodoItem from './TodoItem'; statement.

Todo is mentioned for the first and the last time.

Through out the chapter it was difficult to understand **where** to insert some code into the Config. Code examples should be easier to understand.

**Comment by bebraw** [comment]
Great points! I'll clarify these in the next revision.

**Comment by bebraw** [comment]
@vitaliy-kotov I fixed the `TodoItem` glitch and added context to those configuration bits. Please check the repository version. If that looks good to you, let's go with this.

**Comment by vitaliy-kotov** [comment]
looks way better

**Comment by bebraw** [comment]
Awesome, thanks.

Keep the reports coming. :+1:
