### ISSUE TITLE
React and Flux -

### ISSUE THREAD

**Issue by ankitml** [survivejs/webpack_react#402]
Trying to replicate http://survivejs.com/webpack_react/react_and_flux/

ERROR in ./app/actions/NoteActions.js
Module not found: Error: Cannot resolve 'file' or 'directory' ../libs/alt in /Users/ankit/Documents/repos/sandbox/kanban/app/actions

Same error for NoteStores/.js.

This gets resolved by changing ../libs/alt to only alt in both the file/module(s). 

Thanks

**Comment by bebraw** [comment]
@ankitml How did you solve it? Missing file?

**Comment by ankitml** [comment]
That was a terrible mistake from my side. Please ignore.
