### ISSUE TITLE
Colors

### ISSUE THREAD

**Issue by P58603649** [survivejs/webpack_react#44]
would be great to know how to get the colors back for the output from scripts

**Comment by bebraw** [comment]
I probably should attach `stats: { colors: true }` to `WebpackDevServer` as colors aren't enabled by default. On a related note passing `--colors` to `webpack` would be another nice one.

Thanks for the heads up!

**Comment by gilesbradshaw** [comment]
great did 

````
new WebpackDevServer(webpack(config), {
    contentBase: __dirname,
    stats: { colors: true }, 
    publicPath: config.output.publicPath,
````

and it works

**Comment by bebraw** [comment]
Cool, I'll add a snippet about this to the book.

On a related note I've been thinking of showing how to implement a little plugin to ring system bell in case the build fails. It's a little thing that can help.

**Comment by gilesbradshaw** [comment]
Good idea.  Something I'd like to see (not sure if it's there) is isomorphic javascript - I'e been looking at flummox but took a step back to this to learn about web pack &c better.
