### ISSUE TITLE
npm install error

### ISSUE THREAD

**Issue by gchaintiou** [survivejs/webpack_react#449]
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: react-boilerplate@2.5.6
npm ERR! Found: webpack@1.15.0
npm ERR! node_modules/webpack
npm ERR!   dev webpack@"^1.13.1" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer webpack@"^2.0.0 || ^3.0.0 || ^4.0.0" from expose-loader@0.7.5
npm ERR! node_modules/expose-loader
npm ERR!   dev expose-loader@"^0.7.1" from the root project
npm ERR!
npm ERR! this command with --force or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.

**Comment by bebraw** [comment]
The boilerplate is out of date. It's much better to start from create-react-app or Vite from example.
