### ISSUE TITLE
bewidlered by constructor parameters

### ISSUE THREAD

**Issue by gilesbradshaw** [survivejs/webpack_react#46]
what is this??  I assume it's an ES6 thing but confused..

  constructor(props: {
    task: string;
    onEdit: Function;
  })

**Comment by bebraw** [comment]
Those type declarations come from [Flow](http://flowtype.org/). In this case we're using [flowcheck](https://github.com/gcanti/flowcheck) which is more or less compatible with it.

An alternative would be to go with [PropTypes](https://facebook.github.io/react/docs/reusable-components.html) but as you can see from that page the syntax is quite cumbersome. Flow annotations read much better while giving the same effect (development time type checks).

I may need to rethink the way I approach Flow. Maybe it will make sense to show **how** to possibly integrate it and skip it on the project. Not sure yet. In any case I need to expand the discussion. Thanks for bringing this to my attention.

**Comment by gilesbradshaw** [comment]
Ah yes I realise flow is using them - however they work even without flow?  That's where I am confused because they don't look like valid javascript to me on their own (ES5/6/7) without flow?  I assume I am wrong.

Your book is excellent btw - would also make a very good training course.

**Comment by bebraw** [comment]
> however they work even without flow?

Babel will strip the annotations for you by default. I don't think things will work that smoothly outside of Babel, though, given it's a non-standard feature. I hope that answers your question. :)

> Your book is excellent btw - would also make a very good training course.

Thanks! The design is very modular and would no doubt fit something like this. I have to explore options just like this as I get the core done (target: end of June). I'm currently in middle of some client work so things have been slower than I would like.
