### ISSUE TITLE
html-webpak-plugin templates

### ISSUE THREAD

**Issue by jantimon** [survivejs/webpack_react#53]
Hi,

I just came across this repo and saw that you are preferring setting all scripts/links using blueimp over the inject option.
Is there a specific reason for it because I believe that the inject options simplifies the app development a lot?

https://github.com/survivejs/webpack_react/blob/master/project_source/05_webpack_and_react/kanban_app/app/index.tpl

Could easily be 

https://github.com/ampedandwired/html-webpack-plugin/blob/master/default_inject_index.html

**Comment by bebraw** [comment]
Cool, thanks for pointing that out! I'll get this fixed.

**Comment by bebraw** [comment]
@jantimon Thanks! I simplified the section a lot (realized no template is needed in this case). Speaking of which is there a nice way to generate dev server index.html through html-webpack-plugin dynamically? It's not nice having to drag that in the project.

**Comment by jantimon** [comment]
Hm actually I meant you might want to use `inject:true` for custom templates ;)  
I don't understand however what you mean by dynamically generated dev files - the plugin adds it to the webpack assets. So it should be there on the dev server too. Is it missing?

**Comment by bebraw** [comment]
> Hm actually I meant you might want to use inject:true for custom templates ;)

Ah. Anyway, **much** simpler now. :+1: 

> I don't understand however what you mean by dynamically generated dev files - the plugin adds it to the webpack assets. So it should be there on the dev server too. Is it missing?

If you look at [my boilerplate](https://github.com/survivejs/react-component-boilerplate), you can see there's `dev-server/index.html` hanging around. That's something I want to eliminate. I have a feeling [export-files-webpack-plugin](https://github.com/alexkuz/export-files-webpack-plugin) might be needed here. Just playing around with this.

**Comment by bebraw** [comment]
If you check out that plugin, you can see the core of the issue:

> You might use some file-generating plugins on production (e.g. HTML Webpack Plugin), but it would be useless on development, as dev-server is not actually saving any files on the disk.

**Comment by jantimon** [comment]
Should not be needed should work right away without your `dev-server/index.html` just open the index.html in the same folder where your javascript is

**Comment by bebraw** [comment]
@jantimon Can you hit me through gitter? Opened a chat there. We can probably resolve the issue faster that way. Likely just missing something simple here.
