### ISSUE TITLE
ESLint peer dependency issue

### ISSUE THREAD

**Issue by dustinsmith1024** [survivejs/webpack_react#60]
Looks like theres a conflict between `eslint-plugin-react` and `eslint`.  I had to specify `"eslint": "0.23.0",` in my package.json to get passed the peer dependency error.

I don't know if you want to specify versions in the book or not, but it might help get around some of these issues in the future.

**Comment by bebraw** [comment]
It looks like today's release of `eslint` broke `eslint-loader` as it uses a very strict definition for its peer dependency... I set up an issue to track this: https://github.com/MoOx/eslint-loader/issues/49 . ESlint will reach 1.0 soon so I think things will start to stabilize a bit.

In other news npm reached [3.0.0](https://github.com/npm/npm/releases/tag/v3.0.0). It's still considered beta. In the future peer dependencies won't be as strictly handled and as a result we'll avoid nasty issues like this.

That said it would be nice to find a good solution for this as it's painful to encounter breakage like this. I've been thinking of doing a debugging chapter (#59) and this sort of thing would fit there well. As you said locking the dependencies to some particular version could work but in theory semver should handle all of this for us. But as you can see it's not quite working out ideally. One too strict peer dep somewhere and we're in a mess. :)

**Comment by dustinsmith1024** [comment]
I don't know if you can really expect every npm module to support semvar correctly.  For production apps I usually lock them.

This is a bit of a different situation though.  Honestly, just coming and looking through the issues for others having a problem is probably sufficient.  As long as people actually log issues when problems arise...

Enjoying the book so far though.  Thanks :+1:   Feel free to close the issue if you want.

**Comment by bebraw** [comment]
@dustinsmith1024 Thanks! I set up a `Troubleshooting` chapter so it's easier to keep track of these things. I'll try to cover some common issues and solutions for them there.
