### ISSUE TITLE
Clean up `this.props.items.map`

### ISSUE THREAD

**Issue by bebraw** [survivejs/webpack_react#69]
> I would suggest using the convention {this.items.map(this.renderItem)} from the start, it reads and looks better :)

**Comment by bebraw** [comment]
Just realized this isn't straightforward in ES6 without using a solution like [autobind decorator](https://github.com/andreypopp/autobind-decorator). Perhaps better to leave this open till a good compromise is found.

What kind of convention do you like to use for `map` and such?

**Comment by mathieumg** [comment]
If I want to bind inline, I use:

```js
{this.items.map(::this.renderItem)}
```

(see: https://github.com/zenparsing/es-function-bind)

But if I want to bind when declarating, I use:

```js
renderItem = () => {
  // ...
}
```

As suggested in the React blog post.

**Comment by bebraw** [comment]
@mathieumg Thanks! Esp. that inline binding looks nice. Latter relies on class property initializers. I would have to enable stage 0 for Babel and I'm a bit hesitant to do that as I have a feeling that could be a bad idea. I like to keep stage 1 as an absolute minimum.

I think I'll leave it as is for now unless someone comes up with a better idea. If/when the features go forward I'll update the book to use newer conventions at least.
