### ISSUE TITLE
Add screenshots to show progress

### ISSUE THREAD

**Issue by bebraw** [survivejs/webpack_react#74]
Easier to keep track of what the app should look like and when.

**Comment by Foxandxss** [comment]
You will see pain my friend. Remember my words :P

There is nothing worst than leanpub and images.

**Comment by bebraw** [comment]
Done. If it doesn't look great, we can revisit this. Going through PDF gave enough DPI I think. I can still manipulate the PNGs if needed. I think I saw some artefacts there...
