### ISSUE TITLE
ERROR in multi main

### ISSUE THREAD

**Issue by guyellis** [survivejs/webpack_react#78]
In this section:  
https://github.com/survivejs/webpack_react/blob/master/manuscript/04_webpack_and_react.md#installing-react

After I rename `main.js` to `main.jsx` I start seeing this error:
```
ERROR in multi main
Module not found: Error: Cannot resolve 'file' or 'directory' /home/some-path/app/main in /home/some-path
 @ multi main
```

**Comment by bebraw** [comment]
Thanks! I added a note against that. The configuration it needs is introduced in the next section. That said perhaps the early part should be rewritten and Babel should be discussed first. Might be more natural.

**Comment by zweicoder** [comment]
@bebraw I'm at Chapter 3.4 now trying to render to `index.jsx`, but getting the same error after following the Babel setup:

```
ERROR in multi main
Module not found: Error: Cannot resolve 'file' or 'directory' /home/user/code/tutorials/kanban_app/app in /home/user/code/tutorials/kanban_app
 @ multi main
```

You can see my repo [here](https://github.com/zweicoder/kanban-react). Would appreciate some help if possible :)

**Comment by bebraw** [comment]
@zweicoder You are missing a bit of configuration from 3.2. Add

```javascript
resolve: {
  extensions: ['', '.js', '.jsx']
},
```

I'll move the Webpack bits later in a future version so it's faster to get started with the actual coding.

**Comment by sudanvellakovilkanakavel** [comment]
Hi i am getting the following error. I have only fle main.jsx, i dont have file main.js should i want to crate a file main.js??  i am new to Node and react JS. I am trying to install react js. kindly help

ERROR in multi main
Module not found: Error: Can't resolve './main.js' in '/Users/kanaks/Desktop/reactApp'
 @ multi main
webpack: bundle is now VALID.

**Comment by bebraw** [comment]
@sudanvellakovilkanakavel Can you link to your project? It's hard to say anything concrete otherwise. Before doing that, compare against [the reference source](https://github.com/survivejs/webpack_react/tree/dev/project_source). That might point out the issue. It could have something to do with webpack configuration.

**Comment by sudanvellakovilkanakavel** [comment]
Hi It worked
when I add main.js and App.js 
 further when i copied source code of main.jsx to main.js 
and on copying source code of App.jsx to App.js it work fine. It seems webpack by default looking for main.js file,when i have only main.jsx file,it doesn't work.

I am very new to node, thank you for your immediate response.

**Comment by bebraw** [comment]
@sudanvellakovilkanakavel Yeah. It won't find `jsx` without some extra setup. That's where the `extensions` configuration can be handy. Great to hear you got it to work. :+1:

**Comment by Mark-Brightcloud** [comment]
0. Restart Terminal(Mac) or whatever shell in your environment.

1. Add FIXFIX in package.json like this:
`"scripts": {
    "FIXFIX": "webpack --progress --profile --colors --display-error-details --display-cached",
  },`

2. Run this: (Yes, with sudo!)
`sudo node run FIXFIX`

3. Now run with your normal build see if it fixed.
